/*
 Core JS for Betterlink

 Copyright 2013, Ben Getson. All rights reserved.
 Version: 0.3
 Build date: 5 September 2013
*/
function m(b){throw b;}var p=!0,v=null,E=!1;function aa(b){return function(){return b}}var ba;
ba=window.betterlink||function(){function b(){if(!B){B=p;if(!u.initialized&&!u.initialized){var c,d;for(d in l)(c=l[d])instanceof q&&c.Z();h.$d||y()}s(A)}}function a(c,a){var H=typeof c[a];return H==d||!!(H==e&&c[a])||"unknown"==H}function g(c,d){return!!(typeof c[d]==e&&c[d])}function k(d,e){return typeof d[e]!=c}function n(c){return function(d,e){for(var w=e.length;w--;)if(!c(d,e[w]))return E;return p}}function q(c,d){this.name=c;this.G=this.g=E;this.Z=d}function s(c){for(var d=0,e=c.length;d<e;++d)try{c[d](u)}catch(w){t("Betterlink listener threw an exception. Continuing. Detail: "+
(w.message||w.description||String(w)))}}function y(){u.initialized||(u.initialized=p,s(L))}function t(c){g(window,"console")&&a(window.console,"log")&&window.console.log(c)}function x(c){u.initialized=p;u.G=E;t("Betterlink is not supported on this page in your browser. Reason: "+c)}function z(c){t("Betterlink warning: "+c)}var u={version:"0.3",initialized:E},h={$d:p};u.config={};h.b={};var e="object",d="function",c="undefined";h.ra=a;h.rb=g;h.Ha=k;h.da=n(a);h.bd=n(g);h.Ra=n(k);var l={};h.wc=l;q.prototype=
{r:function(c){this.g=p;this.G=E;m(Error("Module '"+this.name+"' failed to load: "+c))},warn:function(c){u.warn("Module "+this.name+": "+c)},Ca:function(c,d){u.warn("DEPRECATED: "+c+" in module "+this.name+"is deprecated. Please use "+d+" instead")},l:function(c){return Error("Error in "+this.name+" module: "+c)}};u.i=function(c,d){if(!l[c]){var e=new q(c,function(){if(!e.g){e.g=p;try{d(u,h,e),e.G=p}catch(w){h.hd("Module '"+c+"' failed to load: "+(w.message||w.description||String(w)))}}});l[c]=e}};
u.q=function(c){for(var d=0,e=c.length,w,a;d<e;++d)a=c[d],w=l[a],(!w||!(w instanceof q))&&m(Error("required module '"+a+"' not found")),w.Z(),w.G||m(Error("required module '"+a+"' not supported"))};var f;a(document,"addEventListener")?f=function(c,d,e){c.addEventListener(d,e,E)}:a(document,"attachEvent")?f=function(c,d,e){c.attachEvent("on"+d,e)}:x("Document does not have required addEventListener or attachEvent method");h.addListener=f;var A=[];h.Hb=function(c){B?c(u):A.push(c)};var B=E;if(typeof window==
c)x("No window found");else if(typeof document==c)x("No document found");else{a(document,"addEventListener")&&document.addEventListener("DOMContentLoaded",b,E);f(window,"load",b);u.init=y;var L=[];h.Pa=function(c){u.initialized?c(u):L.push(c)};h.hd=t;h.r=x;h.warn=z;!u.initialized&&"complete"===document.readyState&&(u.$b=b);return u}}();window.betterlink=ba;ba.i("HTTP",function(b,a){function g(d,c,l){if(t)u.push(arguments);else{var f=e.He;e.test&&(c.test=1);f&&(c.verbose=1);l&&!y?(c.callback=l,d+=".js"):d+=".json";c._=(new Date).getTime().toString();d+="?"+a.b.s.cd(c);if(y){var b=new XMLHttpRequest;b.open("GET",d,p);b.withCredentials=p;b.onreadystatechange=function(){if(4===b.readyState)if(201===b.status||200===b.status||204===b.status)l&&l(E,b.responseText);else{var c="Bad HTTP status: "+b.status+" "+b.statusText;l&&(f?l({status:p,error:c}):l(p))}};
b.send(v)}else{var g=window.document.createElement("script");g.type="text/javascript";g.async=p;g.defer=p;g.src=d;var k=window.document.getElementsByTagName("script")[0];k.parentNode.insertBefore(g,k)}}}function k(d,c){if(a.b.O(d))return v;if(y)return function(e,a){d(e,a,c)};var l=""+Math.floor(1E8*Math.random()),f=e.dd+'["'+l+'"]';h[l]=function(e,a){delete h[l];201===a||200===a?d(E,e,c):d(p)};return f}function n(){a.b.forEach(u,function(d){g.call(d)});delete u}b.q(["Util","Util.HTTP","Util.DOM"]);
var q=window.navigator.userAgent,s=window.document.referrer,y=window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest,t=!y&&-1==q.indexOf("MSIE"),x=/(google web preview|baiduspider|yandexbot)/i.test(q),z=a.b.B.Hd(),u=[],h=[],e={He:p,xa:("https:"==window.document.location.protocol?"https://":"http://")+"localhost:3000",ve:"/selection_submissions/submit",Ie:"/selection_views/submit",re:"/selections/%%route:id%%",Fe:"/selection_submissions/%%route:id%%/update_submission_url",test:p,dd:"betterlink._jcb"};
a.Hb(function(){t=E;n()});a.we=function(d,c){if(!a.b.O(typeof d))if(x)a.b.O(typeof c)||c(0);else{var l=a.b.extend({},{useragent:encodeURIComponent(q),referrer:encodeURIComponent(s),href:encodeURIComponent(window.document.location.href),domain:encodeURIComponent(window.document.location.hostname)},d);z&&(l.script_source=encodeURIComponent(z));var f=a.b.s.vc(l),f=a.b.s.Db(f),f=a.b.s.Jb(f);g(e.xa+e.ve,{data:f},k(c,l))}};a.getSelection=function(d,c){if(!a.b.O(typeof d))if(x)a.b.O(typeof c)||c(0);else{var l=
{},f=a.b.s.kc(e.re,{id:d});g(e.xa+f,l,k(c,l));return l}};a.xe=function(d,c){if(!a.b.O(typeof d))if(x)a.b.O(typeof c)||c(0);else{var l=a.b.extend({},{useragent:encodeURIComponent(q),referrer:encodeURIComponent(s)},{selection_id:d});z&&(l.script_source=encodeURIComponent(z));var f=a.b.s.vc(l),f=a.b.s.Db(f),f=a.b.s.Jb(f);g(e.xa+e.Ie,{data:f},k(c,l))}};a.Ee=function(d,c){if(!a.b.O(typeof d)){c=a.b.s.Db(encodeURIComponent(c));var l={url:c},f=a.b.s.kc(e.Fe,{id:d});g(e.xa+f,l,k(void 0,l))}};a.cg=g;b._jcb=
h});ba.i("Range Manager",function(b,a){function g(){a.d.la||(la?(a.d.la=la,la=v):m(Error("Range Manager not found")))}function k(){return!a.d.g?v:a.d.la.getSelection()}a.d={};a.Hb(g);a.Pa(function(){if(!a.d.g){a.d.g=p;a.d.la||g();a.d.la.Z();var b=a.d.la;a.d.cb=b.cb;a.d.Ma=b.Ma;a.d.hb=b.hb;a.d.createRange=b.createRange;a.bb=b.bb;a.ab=b.ab}});a.d.of=function(){var a=k();return a?a.isCollapsed:p};a.d.ke=function(){var a=k();a&&a.removeAllRanges()};a.d.Id=function(){var a=k();return a?a.X():[]}});ba.i("Util",function(b,a){a.b={O:function(a){return void 0===a},uc:function(a){return"[object String]"==Object.prototype.toString.call(a)},isArray:Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)},Xd:function(b){return b===Object(b)&&!a.b.isArray(b)},forEach:function(a,b,n){if(a!==v)if(Array.prototype.forEach&&a.forEach===Array.prototype.forEach)a.forEach(b,n);else if(a.length===+a.length)for(var q=0,s=a.length;q<s;q++)b.call(n,a[q],q,a);else for(q in a)Object.prototype.hasOwnProperty.call(a,
q)&&b.call(n,a[q],q,a)},extend:function(b){a.b.forEach(Array.prototype.slice.call(arguments,1),function(k){for(var n in k)a.b.O(k[n])||(b[n]=k[n])});return b},truncate:function(b,k){var n;a.b.uc(b)?n=b.slice(0,k):a.b.isArray(b)?(n=[],a.b.forEach(b,function(b){n.push(a.b.truncate(b,k))})):a.b.Xd(b)?(n={},a.b.forEach(b,function(b,g){n[g]=a.b.truncate(b,k)})):n=b;return n},Tf:function(b){var k={};a.b.forEach(b,function(b,g){a.b.uc(b)&&0<b.length&&(k[g]=b)});return k}}});ba.i("Util.DOM",function(b,a){var g="";a.b.B={$e:function(a,b){var g=a.childNodes.length;if(0===g)a.appendChild(b);else if(1===g)a.replaceChild(b,a.childNodes[0]);else{for(;a.hasChildNodes();)a.removeChild(a.lastChild);a.appendChild(b)}},ff:function(a,b,g){var s=window.document.createElement("a");s.appendChild(document.createTextNode(a));s.href=b;g&&(s.target=g);return s},Ye:function(b,g,q){b="."+b+" "+g;q&&(b=q+b);return a.b.B.Wb(b)},Ze:function(b,g){return a.b.B.Wb("#"+b+" "+g)},Wb:function(a){var b=
document.head||document.getElementsByTagName("head")[0],g=document.createElement("style");g.type="text/css";g.styleSheet?g.styleSheet.cssText=a:g.appendChild(document.createTextNode(a));b.appendChild(g);return g},Hd:function(){if(!g)for(var a=document.getElementsByTagName("script"),b=0,q=a.length;b<q;b++)if(-1!==a[b].src.indexOf("betterlink-no-interface-0.3.js"))return g=a[b].getAttribute("data-script_source");return""}}});ba.i("Util.HTTP",function(b,a){b.q(["Util"]);a.b.s={Fd:function(a){var b={};a=decodeURIComponent((a?a:window.location.search).substr(1)).split("&");for(var n,q=a.length,s=0;s<q;s++)n=a[s].split("="),b[n[0]]=n[1];return b},cd:function(b){var k,n,q,s=[];"undefined"===typeof k&&(k="&");a.b.forEach(b,function(a,b){n=encodeURIComponent(a.toString());q=encodeURIComponent(b);s[s.length]=q+"="+n});return s.join(k)},kc:function(a,b){return a.replace(/%%route:([^%]+)%%/g,function(a,g){return b[g]})},Bc:function(a){return"object"===
typeof a?a:JSON.parse(a)},vc:function(a){function b(a){var g=/[\\\"\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,k={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};g.lastIndex=0;return g.test(a)?'"'+a.replace(g,function(a){var b=k[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function n(a,g){var y="",t=0,x=t="",x=0,z=y,u=[],h=g[a];h&&("object"===
typeof h&&"function"===typeof h.toJSON)&&(h=h.toJSON(a));switch(typeof h){case "string":return b(h);case "number":return isFinite(h)?String(h):"null";case "boolean":case "null":return String(h);case "object":if(!h)return"null";y+="    ";u=[];if("[object Array]"===Object.prototype.toString.apply(h)){x=h.length;for(t=0;t<x;t+=1)u[t]=n(t,h)||"null";return x=0===u.length?"[]":y?"[\n"+y+u.join(",\n"+y)+"\n"+z+"]":"["+u.join(",")+"]"}for(t in h)Object.hasOwnProperty.call(h,t)&&(x=n(t,h))&&u.push(b(t)+(y?
": ":":")+x);return x=0===u.length?"{}":y?"{\n"+y+u.join(",\n"+y)+"\n"+z+"}":"{"+u.join(",")+"}"}}return n("",{"":a})},Jb:function(a){var b,n,q,s,y=0,t=0,x="",x=[];if(!a)return a;do b=a.charCodeAt(y++),n=a.charCodeAt(y++),q=a.charCodeAt(y++),s=b<<16|n<<8|q,b=s>>18&63,n=s>>12&63,q=s>>6&63,s&=63,x[t++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(n)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(q)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(s);while(y<a.length);x=x.join("");a=a.length%3;return(a?x.slice(0,a-3):x)+"===".slice(a||3)},Db:function(a){return unescape(encodeURIComponent(a))},og:function(a){return decodeURIComponent(escape(a))}}});ba.i("Event Messaging",function(b,a){function g(b){var g=Array.prototype.slice.call(arguments,1);a.b.forEach(b,function(a){a.na.apply(a.pa,g)})}b.q(["Util"]);a.f={};var k=[],n=[],q=[],s=[],y=[];a.f.fb=function(a){g(k,a)};a.f.je=function(a){k.push({pa:this,na:a})};a.f.xd=function(){g(n)};a.f.he=function(a){n.push({pa:this,na:a})};a.f.yd=function(){g(q)};a.f.ie=function(a){q.push({pa:this,na:a})};a.f.vd=function(){g(s)};a.f.fe=function(a){s.push({pa:this,na:a})};a.f.wd=function(a){g(y,a)};a.f.ge=function(a){y.push({pa:this,
na:a})}});ba.i("Sharing",function(b,a){function g(){if(b.initialized){var g="",x=q(n());a.we(x,function(b,u){if(b)g="There was a problem building your share link",a.f.fb({success:E,message:g});else{var h=a.b.s.Bc(u);if(Object.hasOwnProperty.call(h,y)){var e=h[s],h=k(h[y]);a.f.fb({success:p,message:h});a.Ee(e,h)}else g="There was a problem building your share link",a.f.fb({success:E,message:g})}})}else a.warn("not yet initialized")}function k(a){function g(c,d){return d+a}var z=b.config.highlightQueryParam,
u=z+"="+a,h=b.config.permalink?b.config.permalink:window.location.toString(),e=RegExp("([?&]"+z+"=)[^&#!]+"),d=/#[^&#]+$/,c,z=h;b.config.preserveHash&&(c=d.exec(h));z=z.replace(d,"");e.test(z)?z=z.replace(e,g):(h=z.indexOf("?"),z=-1!==h?z+(z.substr(h).indexOf("&"===-1)?"&"+u:"?"+u):z+("?"+u));c&&(z+=c);return z}function n(){var b=a.d.Id()[0],g=b.text(),b=a.d.Ma(b),z=/{.*?}/.exec(b)[0];return{serialization:b.substr(0,b.indexOf(z)),checksum:z.replace(/[{}]/g,""),text_content:g}}function q(a){b.config.permalink&&
(a.permalink=b.config.permalink);return a}b.q(["Util.HTTP","HTTP","Range Manager","Event Messaging","Highlighting"]);var s="id",y="selection_id";a.f.he(g);b.shareSelectedText=g});ba.i("Highlighting",function(b,a){function g(b){a.o.g?(a.o.Oc={g:p,options:b},a.nb.Wc(a.ab(b.cssClass,{qa:b.elementTagName,ic:p,ba:b.tagsToPreserve,T:b.elementProperties})),k()):s()}function k(b){a.o.g?q(function(b){if(b){var g=b.yb,e=b.Cb,d=p,c;if(c=b.Va!==a.d.hb(document.documentElement)){var l;try{l=a.d.qd(g)}catch(f){l=E}c=!(l&&l.text()===e)}if(c&&(d=E,c=a.d.createRange(),c.selectNodeContents(document.body),e=c.findText(e)?c:E))g=a.d.Ma(e),d=p;if(d){try{var A=a.d.cb(g);a.o.Oc&&a.nb.Ld(a.o.Oc.options.cssClass,
A);a.f.yd()}catch(B){}a.d.ke();n(b.qe)}}},b):s()}function n(b){a.xe(b,function(){})}function q(g,k){var h=k?k:a.b.s.Fd()[b.config.highlightQueryParam];h&&a.getSelection(h,function(b,d){if(b)g(E);else{var c;c=a.b.s.Bc(d);(c=Object.hasOwnProperty.call(c,y)&&Object.hasOwnProperty.call(c,t)&&Object.hasOwnProperty.call(c,x)?{yb:c[y],Va:c[t],Cb:c[x]}:E)?g({qe:h,yb:c.yb,Va:c.Va,Cb:c.Cb}):g(E)}})}function s(){a.warn("Highlighting not yet initialized")}b.q(["HTTP","Util.HTTP","Event Messaging","Range Manager"]);
b.config.highlightQueryParam="hl";var y="serialization",t="checksum",x="text_content";a.o={};a.Pa(function(){if(!a.o.g){a.o.g=p;a.f.ge(g);var b;b=a.bb();a.nb=b;a.f.vd()}});b.highlightRequestedSelections=k;b.removeHighlightFromSelectedText=function(){a.o.g?a.nb.De():s()}});ba.i("Exports for Public Interface",function(b,a){b.q(["Event Messaging"]);b.registerObserverForSubmissionDisplay=a.f.je;b.fireNewSubmission=a.f.xd;b.registerObserverForSelectionHighlighted=a.f.ie;b.registerObserverForHighlighterInitialized=a.f.fe;b.fireHighlighterStylesInitialized=a.f.wd});"object"!==typeof JSON&&(JSON={});
(function(){function b(a){return 10>a?"0"+a:a}function a(a){n.lastIndex=0;return n.test(a)?'"'+a.replace(n,function(a){var b=y[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function g(b,k){var n,h,e,d,c=q,l,f=k[b];f&&("object"===typeof f&&"function"===typeof f.toJSON)&&(f=f.toJSON(b));"function"===typeof t&&(f=t.call(k,b,f));switch(typeof f){case "string":return a(f);case "number":return isFinite(f)?String(f):"null";case "boolean":case "null":return String(f);
case "object":if(!f)return"null";q+=s;l=[];if("[object Array]"===Object.prototype.toString.apply(f)){d=f.length;for(n=0;n<d;n+=1)l[n]=g(n,f)||"null";e=0===l.length?"[]":q?"[\n"+q+l.join(",\n"+q)+"\n"+c+"]":"["+l.join(",")+"]";q=c;return e}if(t&&"object"===typeof t){d=t.length;for(n=0;n<d;n+=1)"string"===typeof t[n]&&(h=t[n],(e=g(h,f))&&l.push(a(h)+(q?": ":":")+e))}else for(h in f)Object.prototype.hasOwnProperty.call(f,h)&&(e=g(h,f))&&l.push(a(h)+(q?": ":":")+e);e=0===l.length?"{}":q?"{\n"+q+l.join(",\n"+
q)+"\n"+c+"}":"{"+l.join(",")+"}";q=c;return e}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+b(this.getUTCMonth()+1)+"-"+b(this.getUTCDate())+"T"+b(this.getUTCHours())+":"+b(this.getUTCMinutes())+":"+b(this.getUTCSeconds())+"Z":v},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var k=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
n=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,q,s,y={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},t;"function"!==typeof JSON.stringify&&(JSON.stringify=function(a,b,n){var h;s=q="";if("number"===typeof n)for(h=0;h<n;h+=1)s+=" ";else"string"===typeof n&&(s=n);(t=b)&&("function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))&&m(Error("JSON.stringify"));return g("",{"":a})});
"function"!==typeof JSON.parse&&(JSON.parse=function(a,b){function g(a,d){var c,l,f=a[d];if(f&&"object"===typeof f)for(c in f)Object.prototype.hasOwnProperty.call(f,c)&&(l=g(f,c),void 0!==l?f[c]=l:delete f[c]);return b.call(a,d,f)}var n;a=String(a);k.lastIndex=0;k.test(a)&&(a=a.replace(k,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return n=eval("("+a+")"),"function"===typeof b?g({"":n},""):n;m(new SyntaxError("JSON.parse"))})})();var la;
la=la||function(){function b(){T||(T=p,F.g||x())}function a(a,c){var b=typeof a[c];return b==h||!!(b==u&&a[c])||"unknown"==b}function g(a,c){return!!(typeof a[c]==u&&a[c])}function k(a,c){return typeof a[c]!=e}function n(a){return function(c,b){for(var d=b.length;d--;)if(!a(c,b[d]))return E;return p}}function q(a){return a&&A(a,f)&&B(a,l)}function s(a){return g(a,"body")?a.body:a.getElementsByTagName("body")[0]}function y(c){g(window,"console")&&a(window.console,"log")&&window.console.log(c)}function t(a){F.g=
p;F.G=E;a="RangeManager is not supported on this page in your browser. Reason: "+a;F.ea.Xc?window.alert(a):y(a)}function x(){if(!F.g){var b,e=E,w=E;a(document,"createRange")&&(b=document.createRange(),A(b,c)&&B(b,d)&&(e=p),b.detach());b=s(document);if(!b||"body"!=b.nodeName.toLowerCase())t("No body element found");else if(b&&a(b,"createTextRange")&&(b=b.createTextRange(),q(b)&&(w=p)),!e&&!w)t("Neither Range nor TextRange are available");else{F.g=p;F.M={ha:e,Md:w};var f,l;for(l in L)(f=L[l])instanceof z&&
f.Z();w=0;for(f=H.length;w<f;++w)try{H[w](F)}catch(g){e="RangeManager init listener threw an exception. Continuing. Detail: "+(g.message||g.description||String(g)),y(e)}}}}function z(a,b){this.name=a;this.G=this.g=E;this.Z=b}var u="object",h="function",e="undefined",d="startContainer startOffset endContainer endOffset collapsed commonAncestorContainer".split(" "),c="setStart setStartBefore setStartAfter setEnd setEndBefore setEndAfter collapse selectNode selectNodeContents compareBoundaryPoints deleteContents extractContents cloneContents insertNode surroundContents cloneRange toString detach".split(" "),
l="boundingHeight boundingLeft boundingTop boundingWidth htmlText text".split(" "),f="collapse compareEndPoints duplicate moveToElementText parentElement select setEndPoint getBoundingClientRect".split(" "),A=n(a),B=n(k),L={},F={version:"1.3alpha.772",g:E,G:p,b:{ra:a,rb:g,Ha:k,da:A,bd:n(g),Ra:B,Kf:q,Y:s},M:{},wc:L,ea:{Xc:p,Yc:E,Dc:E}};F.r=t;F.warn=function(a){a="RangeManager warning: "+a;F.ea.Yc?window.alert(a):y(a)};({}).hasOwnProperty?F.b.extend=function(a,b,c){var d,e,w;for(w in b)b.hasOwnProperty(w)&&
(d=a[w],e=b[w],c&&(d!==v&&"object"==typeof d&&e!==v&&"object"==typeof e)&&F.b.extend(d,e,p),a[w]=e);return a}:t("hasOwnProperty not supported");(function(){var a=document.createElement("div");a.appendChild(document.createElement("span"));var b=[].slice,c;try{1==b.call(a.childNodes,0)[0].nodeType&&(c=function(a){return b.call(a,0)})}catch(d){}c||(c=function(a){for(var b=[],c=0,d=a.length;c<d;++c)b[c]=a[c];return b});F.b.ye=c})();var G;a(document,"addEventListener")?G=function(a,b,c){a.addEventListener(b,
c,E)}:a(document,"attachEvent")?G=function(a,b,c){a.attachEvent("on"+b,c)}:t("Document does not have required addEventListener or attachEvent method");F.b.addListener=G;var H=[];F.Z=x;F.Pa=function(a){F.g?a(F):H.push(a)};var w=[];F.Gb=function(a){w.push(a)};F.lf=function(a){a=a||window;x();for(var b=0,c=w.length;b<c;++b)w[b](a)};z.prototype={r:function(a){this.g=p;this.G=E;m(Error("Module '"+this.name+"' failed to load: "+a))},warn:function(a){F.warn("Module "+this.name+": "+a)},Ca:function(a,b){F.warn("DEPRECATED: "+
a+" in module "+this.name+"is deprecated. Please use "+b+" instead")},l:function(a){return Error("Error in RangeManager "+this.name+" module: "+a)}};F.i=function(a,b){var c=new z(a,function(){if(!c.g){c.g=p;try{b(F,c),c.G=p}catch(d){y("Module '"+a+"' failed to load: "+(d.message||d.description||String(d)))}}});L[a]=c};F.q=function(a){for(var b=0,c=a.length,d,e;b<c;++b)e=a[b],d=L[e],(!d||!(d instanceof z))&&m(Error("required module '"+e+"' not found")),d.Z(),d.G||m(Error("required module '"+e+"' not supported"))};
var T=E;if(typeof window==e)t("No window found");else if(typeof document==e)t("No document found");else return a(document,"addEventListener")&&document.addEventListener("DOMContentLoaded",b,E),G(window,"load",b),F}();
la.i("DomUtil",function(b,a){function g(a,b){for(var c=a.length;c--;)if(a[c]===b)return p;return E}function k(a){for(var b=0;a=a.previousSibling;)++b;return b}function n(a,b){var c=[],d;for(d=a;d;d=d.parentNode)c.push(d);for(d=b;d;d=d.parentNode)if(g(c,d))return d;return v}function q(a,b,c){for(b=c?b:b.parentNode;b;){if(b===a)return p;b=b.parentNode}return E}function s(a,b,c){for(c=c?a:a.parentNode;c;){a=c.parentNode;if(a===b)return c;c=a}return v}function y(a){a=a.nodeType;return 3==a||4==a||8==
a}function t(a,b){var c=b.nextSibling,d=b.parentNode;c?d.insertBefore(a,c):d.appendChild(a);return a}function x(b){if(9==b.nodeType)return b;if(typeof b.ownerDocument!=A)return b.ownerDocument;if(typeof b.document!=A)return b.document;if(b.parentNode)return x(b.parentNode);m(a.l("getDocument: no document found for node"))}function z(b){b=x(b);if(typeof b.defaultView!=A)return b.defaultView;if(typeof b.parentWindow!=A)return b.parentWindow;m(a.l("Cannot get a window object for node"))}function u(b){if(typeof b.contentDocument!=
A)return b.contentDocument;if(typeof b.contentWindow!=A)return b.contentWindow.document;m(a.l("getIframeDocument: No Document object found for iframe element"))}function h(a){return a&&B.ra(a,"setTimeout")&&B.rb(a,"document")}function e(a){try{return a.parentNode,E}catch(b){return p}}function d(a){return!a?"[No node]":F&&e(a)?"[Broken node]":y(a)?'"'+a.data+'"':1==a.nodeType?"<"+a.nodeName+(a.id?' id="'+a.id+'"':"")+">["+a.childNodes.length+"]["+a.innerHTML.slice(0,20)+"]":a.nodeName}function c(a){this.A=
this.root=a}function l(a,b){this.a=a;this.offset=b}function f(a){this.code=this[a];this.Ya=a;this.message="DOMException: "+this.Ya}var A="undefined",B=b.b;B.da(document,["createDocumentFragment","createElement","createTextNode"])||a.r("document missing a Node creation method");B.ra(document,"getElementsByTagName")||a.r("document missing getElementsByTagName method");var L=document.createElement("div");B.da(L,["insertBefore","appendChild","cloneNode"])||a.r("Incomplete Element implementation");B.Ha(L,
"innerHTML")||a.r("Element is missing innerHTML property");B.da(document.createTextNode("test"),["splitText","deleteData","insertData","appendData","cloneNode"])||a.r("Incomplete Text Node implementation");var F=E;(function(){var a=document.createElement("b");a.innerHTML="1";var c=a.firstChild;a.innerHTML="<br>";F=e(c);b.M.ld=F})();var G;typeof window.getComputedStyle!=A?G=function(a,b){return z(a).getComputedStyle(a,v)[b]}:typeof document.documentElement.currentStyle!=A?G=function(a,b){return a.currentStyle[b]}:
a.r("No means of obtaining computed style properties found");c.prototype={u:v,next:function(){var a=this.u=this.A,b;if(this.u){b=a.firstChild;if(!b)for(b=v;a!==this.root&&!(b=a.nextSibling);)a=a.parentNode;this.A=b}return this.u},detach:function(){this.u=this.A=this.root=v}};l.prototype={W:function(a){return!!a&&this.a===a.a&&this.offset==a.offset},w:function(){return"[DomPosition("+d(this.a)+":"+this.offset+")]"},toString:function(){return this.w()}};f.prototype={};f.prototype.toString=function(){return this.message};
b.B={Sa:g,pc:function(a){var b;return typeof a.namespaceURI==A||(b=a.namespaceURI)===v||"http://www.w3.org/1999/xhtml"==b},parentElement:function(a){a=a.parentNode;return 1==a.nodeType?a:v},k:k,Ea:function(a){switch(a.nodeType){case 7:case 10:return 0;case 3:case 8:return a.length;default:return a.childNodes.length}},gb:n,mc:q,tb:function(a,b){return q(a,b,p)},zd:s,N:y,Jf:function(a){if(!a)return E;a=a.nodeType;return 3==a||8==a},Od:t,ue:function(a,b,c){var d=a.cloneNode(E);d.deleteData(0,b);a.deleteData(b,
a.length-b);t(d,a);if(c)for(var e=0,f;f=c[e++];)f.a==a&&f.offset>b?(f.a=d,f.offset-=b):f.a==a.parentNode&&f.offset>k(a)&&++f.offset;return d},m:x,mb:z,Bd:function(b){if(typeof b.contentWindow!=A)return b.contentWindow;if(typeof b.contentDocument!=A)return b.contentDocument.defaultView;m(a.l("getIframeWindow: No Window object found for iframe element"))},tf:u,Y:B.Y,Yd:h,dc:function(a,b,c){var d;a?B.Ha(a,"nodeType")?d=1==a.nodeType&&"iframe"==a.tagName.toLowerCase()?u(a):x(a):h(a)&&(d=a.document):d=
document;d||m(b.l(c+"(): Parameter must be a Window object or DOM node"));return d},Gd:function(a){for(var b;b=a.parentNode;)a=b;return a},Za:function(b,c,d,e){var f;if(b==d)return c===e?0:c<e?-1:1;if(f=s(d,b,p))return c<=k(f)?-1:1;if(f=s(b,d,p))return k(f)<e?-1:1;c=n(b,d);b=b===c?c:s(b,c,p);d=d===c?c:s(d,c,p);b===d&&m(a.l("comparePoints got to case 4 and childA and childB are the same!"));for(c=c.firstChild;c;){if(c===b)return-1;if(c===d)return 1;c=c.nextSibling}},Rd:e,ia:d,cc:G,Yb:function(a){for(var b=
x(a).createDocumentFragment(),c;c=a.firstChild;)b.appendChild(c);return b},nd:function(a){return new c(a)},ka:l};b.Eb=f});
la.i("DomRange",function(b){function a(a,b){return 3!=a.nodeType&&(Z(a,b.startContainer)||Z(a,b.endContainer))}function g(a){return a.document||da(a.startContainer)}function k(a){return new ea(a.parentNode,D(a))}function n(a){return new ea(a.parentNode,D(a)+1)}function q(a,b,c){var d=11==a.nodeType?a.firstChild:a;M(b)?c==b.length?I.Od(a,b):b.parentNode.insertBefore(a,0==c?b:ia(b,c)):c>=b.childNodes.length?b.appendChild(a):b.insertBefore(a,b.childNodes[c]);return d}function s(a,b,c){w(a);w(b);g(b)!=
g(a)&&m(new O("WRONG_DOCUMENT_ERR"));var d=Q(a.startContainer,a.startOffset,b.endContainer,b.endOffset);a=Q(a.endContainer,a.endOffset,b.startContainer,b.startOffset);return c?0>=d&&0<=a:0>d&&0<a}function y(a){for(var b,c,d=g(a.aa).createDocumentFragment();c=a.next();)b=a.Ia(),c=c.cloneNode(!b),b&&(b=a.Fa(),c.appendChild(y(b)),b.detach(p)),10==c.nodeType&&m(new O("HIERARCHY_REQUEST_ERR")),d.appendChild(c);return d}function t(a,b,c){var d,r;for(c=c||{stop:E};d=a.next();)if(a.Ia())if(b(d)===E){c.stop=
p;break}else{if(d=a.Fa(),t(d,b,c),d.detach(p),c.stop)break}else for(d=I.nd(d);r=d.next();)if(b(r)===E){c.stop=p;return}}function x(a){for(var b;a.next();)a.Ia()?(b=a.Fa(),x(b),b.detach(p)):a.remove()}function z(a){for(var b,c=g(a.aa).createDocumentFragment(),d;b=a.next();)a.Ia()?(b=b.cloneNode(E),d=a.Fa(),b.appendChild(z(d)),d.detach(p)):a.remove(),10==b.nodeType&&m(new O("HIERARCHY_REQUEST_ERR")),c.appendChild(b);return c}function u(a,b,c){var d=!(!b||!b.length),r,C=!!c;d&&(r=RegExp("^("+b.join("|")+
")$"));var J=[];t(new e(a,E),function(a){(!d||r.test(a.nodeType))&&(!C||c(a))&&J.push(a)});return J}function h(a){return"["+("undefined"==typeof a.getName?"Range":a.getName())+"("+I.ia(a.startContainer)+":"+a.startOffset+", "+I.ia(a.endContainer)+":"+a.endOffset+")]"}function e(a,b){this.aa=a;this.Qb=b;if(!a.collapsed){this.t=a.startContainer;this.ta=a.startOffset;this.C=a.endContainer;this.fa=a.endOffset;var c=a.commonAncestorContainer;this.t===this.C&&M(this.t)?(this.tc=p,this.P=this.Q=this.A=this.t):
(this.P=this.A=this.t===c&&!M(this.t)?this.t.childNodes[this.ta]:ja(this.t,c,p),this.Q=this.C===c&&!M(this.C)?this.C.childNodes[this.fa-1]:ja(this.C,c,p))}}function d(a){this.code=this[a];this.Ya=a;this.message="RangeException: "+this.Ya}function c(a){return function(b,c){for(var d,r=c?b:b.parentNode;r;){d=r.nodeType;if($(a,d))return r;r=r.parentNode}return v}}function l(a,b){r(a,b)&&m(new d("INVALID_NODE_TYPE_ERR"))}function f(a){a.startContainer||m(new O("INVALID_STATE_ERR"))}function A(a,b){$(b,
a.nodeType)||m(new d("INVALID_NODE_TYPE_ERR"))}function B(a,b){(0>b||b>(M(a)?a.length:a.childNodes.length))&&m(new O("INDEX_SIZE_ERR"))}function L(a,b){ma(a,p)!==ma(b,p)&&m(new O("WRONG_DOCUMENT_ERR"))}function F(a){oa(a,p)&&m(new O("NO_MODIFICATION_ALLOWED_ERR"))}function G(a,b){a||m(new O(b))}function H(a){return ka&&I.Rd(a)||!$(fa,a.nodeType)&&!ma(a,p)}function w(a){f(a);(!a.startContainer||!a.endContainer||H(a.startContainer)||H(a.endContainer)||!(a.startOffset<=(M(a.startContainer)?a.startContainer.length:
a.startContainer.childNodes.length))||!(a.endOffset<=(M(a.endContainer)?a.endContainer.length:a.endContainer.childNodes.length)))&&m(Error("Range error: Range is no longer valid after DOM mutation ("+a.w()+")"))}function T(a,b){w(a);var c=a.startContainer,d=a.startOffset,r=a.endContainer,C=a.endOffset,e=c===r;M(r)&&(0<C&&C<r.length)&&ia(r,C,b);M(c)&&(0<d&&d<c.length)&&(c=ia(c,d,b),e?(C-=d,r=c):r==c.parentNode&&C>=D(c)&&C++,d=0);a.n(c,d,r,C)}function R(){}function V(a){a.START_TO_START=pa;a.START_TO_END=
sa;a.END_TO_END=xa;a.END_TO_START=ta;a.Qe=ua;a.Pe=va;a.Re=wa;a.Se=qa}function K(a){V(a);V(a.prototype)}function Y(a,b){return function(){w(this);var c=this.startContainer,d=this.startOffset,r=this.commonAncestorContainer,C=new e(this,p);c!==r&&(c=ja(c,r,p),d=n(c),c=d.a,d=d.offset);t(C,F);C.reset();r=a(C);C.detach();b(this,c,d,c,d);return r}}function S(b,c,d){function r(a,b){return function(c){f(this);A(c,ga);A(X(c),fa);c=(a?k:n)(c);(b?C:J)(this,c.a,c.offset)}}function C(a,b,d){var r=a.endContainer,
e=a.endOffset;if(b!==a.startContainer||d!==a.startOffset){if(X(b)!=X(r)||1==Q(b,d,r,e))r=b,e=d;c(a,b,d,r,e)}}function J(a,b,d){var r=a.startContainer,C=a.startOffset;if(b!==a.endContainer||d!==a.endOffset){if(X(b)!=X(r)||-1==Q(b,d,r,C))r=b,C=d;c(a,r,C,b,d)}}b.prototype=new R;P.extend(b.prototype,{setStart:function(a,b){f(this);l(a,p);B(a,b);C(this,a,b)},setEnd:function(a,b){f(this);l(a,p);B(a,b);J(this,a,b)},n:function(){f(this);var a=arguments,b=a[0],d=a[1],r=b,C=d;switch(a.length){case 3:C=a[2];
break;case 4:r=a[2],C=a[3]}c(this,b,d,r,C)},se:function(a,b,c){this["set"+(c?"Start":"End")](a,b)},setStartBefore:r(p,p),setStartAfter:r(E,p),setEndBefore:r(p,E),setEndAfter:r(E,E),collapse:function(a){w(this);a?c(this,this.startContainer,this.startOffset,this.startContainer,this.startOffset):c(this,this.endContainer,this.endOffset,this.endContainer,this.endOffset)},selectNodeContents:function(a){f(this);l(a,p);c(this,a,0,a,ca(a))},selectNode:function(a){f(this);l(a,E);A(a,ga);var b=k(a);a=n(a);c(this,
b.a,b.offset,a.a,a.offset)},extractContents:Y(z,c),deleteContents:Y(x,c),Lb:function(){w(this);F(this.startContainer);F(this.endContainer);var b=new e(this,p),c=b.P&&a(b.P,this)||b.Q&&a(b.Q,this);b.detach();return!c},detach:function(){d(this)},eg:function(){T(this)},Nc:function(a){T(this,a)},Of:function(){function a(b){var c=b.previousSibling;if(c&&c.nodeType==b.nodeType){d=b;var J=b.length;r=c.length;b.insertData(0,c.data);c.parentNode.removeChild(c);d==C?(e+=r,C=d):C==b.parentNode&&(c=D(b),e==c?
(C=b,e=J):e>c&&e--)}}function b(a){var c=a.nextSibling;c&&c.nodeType==a.nodeType&&(C=a,e=a.length,a.appendData(c.data),c.parentNode.removeChild(c))}w(this);var d=this.startContainer,r=this.startOffset,C=this.endContainer,e=this.endOffset,J=p;M(C)?C.length==e&&b(C):(0<e&&(J=C.childNodes[e-1])&&M(J)&&b(J),J=!this.collapsed);J?M(d)?0==r&&a(d):r<d.childNodes.length&&(J=d.childNodes[r])&&M(J)&&a(J):(d=C,r=e);c(this,d,r,C,e)},Rb:function(a,b){f(this);l(a,p);B(a,b);this.n(a,b)}});K(b)}function N(a){a.collapsed=
a.startContainer===a.endContainer&&a.startOffset===a.endOffset;a.commonAncestorContainer=a.collapsed?a.startContainer:I.gb(a.startContainer,a.endContainer)}function W(a,b,c,d,r){a.startContainer=b;a.startOffset=c;a.endContainer=d;a.endOffset=r;a.document=I.m(b);N(a)}function U(a){this.startContainer=a;this.startOffset=0;this.endContainer=a;this.endOffset=0;this.document=a;N(this)}b.q(["DomUtil"]);var I=b.B,P=b.b,ea=I.ka,O=b.Eb,M=I.N,D=I.k,Z=I.tb,da=I.m,Q=I.Za,ia=I.ue,ja=I.zd,ca=I.Ea,$=I.Sa,X=I.Gd,
ka=b.M.ld;e.prototype={u:v,A:v,P:v,Q:v,tc:E,reset:function(){this.u=v;this.A=this.P},next:function(){var a=this.u=this.A;a&&(this.A=a!==this.Q?a.nextSibling:v,M(a)&&this.Qb&&(a===this.C&&(a=a.cloneNode(p)).deleteData(this.fa,a.length-this.fa),this.u===this.t&&(a=a.cloneNode(p)).deleteData(0,this.ta)));return a},remove:function(){var a=this.u,b,c;M(a)&&(a===this.t||a===this.C)?(b=a===this.t?this.ta:0,c=a===this.C?this.fa:a.length,b!=c&&a.deleteData(b,c-b)):a.parentNode&&a.parentNode.removeChild(a)},
Ia:function(){return a(this.u,this.aa)},Fa:function(){var a;if(this.tc)a=this.aa.cloneRange(),a.collapse(E);else{a=new U(g(this.aa));var b=this.u,c=b,d=0,r=b,C=ca(b);Z(b,this.t)&&(c=this.t,d=this.ta);Z(b,this.C)&&(r=this.C,C=this.fa);W(a,c,d,r,C)}return new e(a,this.Qb)},detach:function(a){a&&this.aa.detach();this.aa=this.u=this.A=this.P=this.Q=this.t=this.ta=this.C=this.fa=v}};d.prototype={};d.prototype.toString=function(){return this.message};var ga=[1,3,4,5,7,8,10],fa=[2,9,11],C=[1,3,4,5,7,8,10,
11],ha=[1,3,4,5,7,8],ma=c([9,11]),oa=c([5,6,10,12]),r=c([6,10,12]),J=document.createElement("style"),na=E;try{J.innerHTML="<b>x</b>",na=3==J.firstChild.nodeType}catch(ya){}b.M.xf=na;var ra="startContainer startOffset endContainer endOffset collapsed commonAncestorContainer".split(" "),pa=0,sa=1,xa=2,ta=3,ua=0,va=1,wa=2,qa=3;R.prototype={compareBoundaryPoints:function(a,b){w(this);L(this.startContainer,b.startContainer);var c=a==ta||a==pa?"start":"end",d=a==sa||a==pa?"start":"end";return Q(this[c+
"Container"],this[c+"Offset"],b[d+"Container"],b[d+"Offset"])},insertNode:function(a){w(this);A(a,C);F(this.startContainer);Z(a,this.startContainer)&&m(new O("HIERARCHY_REQUEST_ERR"));a=q(a,this.startContainer,this.startOffset);this.setStartBefore(a)},cloneContents:function(){w(this);var a,b;if(this.collapsed)return g(this).createDocumentFragment();if(this.startContainer===this.endContainer&&M(this.startContainer))return a=this.startContainer.cloneNode(p),a.data=a.data.slice(this.startOffset,this.endOffset),
b=g(this).createDocumentFragment(),b.appendChild(a),b;b=new e(this,p);a=y(b);b.detach();return a},Lb:function(){w(this);F(this.startContainer);F(this.endContainer);var b=new e(this,p),c=b.P&&a(b.P,this)||b.Q&&a(b.Q,this);b.detach();return!c},surroundContents:function(a){A(a,ha);this.Lb()||m(new d("BAD_BOUNDARYPOINTS_ERR"));var b=this.extractContents();if(a.hasChildNodes())for(;a.lastChild;)a.removeChild(a.lastChild);q(a,this.startContainer,this.startOffset);a.appendChild(b);this.selectNode(a)},cloneRange:function(){w(this);
for(var a=new U(g(this)),b=ra.length,c;b--;)c=ra[b],a[c]=this[c];return a},toString:function(){w(this);var a=this.startContainer;if(a===this.endContainer&&M(a))return 3==a.nodeType||4==a.nodeType?a.data.slice(this.startOffset,this.endOffset):"";var b=[],a=new e(this,p);t(a,function(a){(3==a.nodeType||4==a.nodeType)&&b.push(a.data)});a.detach();return b.join("")},compareNode:function(a){w(this);var b=a.parentNode,c=D(a);b||m(new O("NOT_FOUND_ERR"));a=this.comparePoint(b,c);b=this.comparePoint(b,c+
1);return 0>a?0<b?wa:ua:0<b?va:qa},comparePoint:function(a,b){w(this);G(a,"HIERARCHY_REQUEST_ERR");L(a,this.startContainer);return 0>Q(a,b,this.startContainer,this.startOffset)?-1:0<Q(a,b,this.endContainer,this.endOffset)?1:0},createContextualFragment:na?function(a){var b=this.startContainer,c=da(b);b||m(new O("INVALID_STATE_ERR"));var d=v;1==b.nodeType?d=b:M(b)&&(d=I.parentElement(b));d=d===v||"HTML"==d.nodeName&&I.pc(da(d).documentElement)&&I.pc(d)?c.createElement("body"):d.cloneNode(E);d.innerHTML=
a;return I.Yb(d)}:function(a){f(this);var b=g(this).createElement("body");b.innerHTML=a;return I.Yb(b)},ze:function(){w(this);var a=this.commonAncestorContainer.parentNode.cloneNode(E);a.appendChild(this.cloneContents());return a.innerHTML},intersectsNode:function(a,b){w(this);G(a,"NOT_FOUND_ERR");if(da(a)!==g(this))return E;var c=a.parentNode,d=D(a);G(c,"NOT_FOUND_ERR");var r=Q(c,d,this.endContainer,this.endOffset),c=Q(c,d+1,this.startContainer,this.startOffset);return b?0>=r&&0<=c:0>r&&0<c},isPointInRange:function(a,
b){w(this);G(a,"HIERARCHY_REQUEST_ERR");L(a,this.startContainer);return 0<=Q(a,b,this.startContainer,this.startOffset)&&0>=Q(a,b,this.endContainer,this.endOffset)},lc:function(a){return s(this,a,E)},Qd:function(a){return s(this,a,p)},Ga:function(a){if(this.lc(a)){var b=Q(this.startContainer,this.startOffset,a.startContainer,a.startOffset),c=Q(this.endContainer,this.endOffset,a.endContainer,a.endOffset),d=this.cloneRange();-1==b&&d.setStart(a.startContainer,a.startOffset);1==c&&d.setEnd(a.endContainer,
a.endOffset);return d}return v},Tc:function(a){if(this.Qd(a)){var b=this.cloneRange();-1==Q(a.startContainer,a.startOffset,this.startContainer,this.startOffset)&&b.setStart(a.startContainer,a.startOffset);1==Q(a.endContainer,a.endOffset,this.endContainer,this.endOffset)&&b.setEnd(a.endContainer,a.endOffset);return b}m(new d("Ranges do not intersect"))},containsNode:function(a,b){return b?this.intersectsNode(a,E):this.compareNode(a)==qa},jb:function(a,b){w(this);return u(this,a,b)},m:function(){return g(this)},
fd:function(a){f(this);this.setStartAfter(a);this.collapse(p)},getBookmark:function(a){var c=g(this),d=b.createRange(c);a=a||I.Y(c);d.selectNodeContents(a);var c=this.Ga(d),r=0,C=0;c&&(d.setEnd(c.startContainer,c.startOffset),r=d.toString().length,C=r+c.toString().length,d.detach());return{start:r,end:C,Tb:a}},moveToBookmark:function(a){var b=a.Tb,c=0;this.setStart(b,0);this.collapse(p);for(var b=[b],d,r=E,C=E,e,J;!C&&(d=b.pop());)if(3==d.nodeType)e=c+d.length,!r&&(a.start>=c&&a.start<=e)&&(this.setStart(d,
a.start-c),r=p),r&&(a.end>=c&&a.end<=e)&&(this.setEnd(d,a.end-c),C=p),c=e;else{J=d.childNodes;for(e=J.length;e--;)b.push(J[e])}},getName:aa("DomRange"),W:function(a){return U.xb(this,a)},w:function(){return h(this)}};S(U,W,function(a){f(a);a.startContainer=a.startOffset=a.endContainer=a.endOffset=a.document=v;a.collapsed=a.commonAncestorContainer=v});b.Hc=R.prototype;P.extend(U,{de:ra,Ue:e,kd:K,od:S,w:h,lb:g,xb:function(a,b){return a.startContainer===b.startContainer&&a.startOffset===b.startOffset&&
a.endContainer===b.endContainer&&a.endOffset===b.endOffset}});b.Oa=U;b.Te=d});
la.i("WrappedRange",function(b,a){b.q(["DomUtil","DomRange"]);var g,k,n=b.B,q=b.b,s=n.ka,y=b.Oa,t=n.Y,x=n.dc,z=n.N;b.M.ha&&function(){function d(a){for(var b=e.length,c;b--;)c=e[b],a[c]=a.c[c];a.collapsed=a.startContainer===a.endContainer&&a.startOffset===a.endOffset}var c,e=y.de,f;g=function(b){b||m(a.l("WrappedRange: Range must be specified"));this.c=b;d(this)};y.od(g,function(a,b,c,d,e){var f=a.endContainer!==d||a.endOffset!=e,l=!a.W(a.c);if(a.startContainer!==b||a.startOffset!=c||f||l)a.setEnd(d,
e),a.setStart(b,c)},function(a){a.c.detach();a.rd=p;for(var b=e.length;b--;)a[e[b]]=v});c=g.prototype;c.selectNode=function(a){this.c.selectNode(a);d(this)};c.cloneContents=function(){return this.c.cloneContents()};c.surroundContents=function(a){this.c.surroundContents(a);d(this)};c.collapse=function(a){this.c.collapse(a);d(this)};c.cloneRange=function(){return new g(this.c.cloneRange())};c.refresh=function(){d(this)};c.toString=function(){return this.c.toString()};var A=document.createTextNode("test");
t(document).appendChild(A);var B=document.createRange();B.setStart(A,0);B.setEnd(A,0);try{B.setStart(A,1),c.setStart=function(a,b){this.c.setStart(a,b);d(this)},c.setEnd=function(a,b){this.c.setEnd(a,b);d(this)},f=function(a){return function(b){this.c[a](b);d(this)}}}catch(h){c.setStart=function(a,b){try{this.c.setStart(a,b)}catch(c){this.c.setEnd(a,b),this.c.setStart(a,b)}d(this)},c.setEnd=function(a,b){try{this.c.setEnd(a,b)}catch(c){this.c.setStart(a,b),this.c.setEnd(a,b)}d(this)},f=function(a,
b){return function(c){try{this.c[a](c)}catch(e){this.c[b](c),this.c[a](c)}d(this)}}}c.setStartBefore=f("setStartBefore","setEndBefore");c.setStartAfter=f("setStartAfter","setEndAfter");c.setEndBefore=f("setEndBefore","setStartBefore");c.setEndAfter=f("setEndAfter","setStartAfter");B.selectNodeContents(A);c.selectNodeContents=B.startContainer==A&&B.endContainer==A&&0==B.startOffset&&B.endOffset==A.length?function(a){this.c.selectNodeContents(a);d(this)}:function(a){this.n(a,0,n.Ea(a))};B.selectNodeContents(A);
B.setEnd(A,3);f=document.createRange();f.selectNodeContents(A);f.setEnd(A,4);f.setStart(A,2);-1==B.compareBoundaryPoints(B.START_TO_END,f)&&1==B.compareBoundaryPoints(B.END_TO_START,f)?c.compareBoundaryPoints=function(a,b){b=b.c||b;a==b.START_TO_END?a=b.END_TO_START:a==b.END_TO_START&&(a=b.START_TO_END);return this.c.compareBoundaryPoints(a,b)}:c.compareBoundaryPoints=function(a,b){return this.c.compareBoundaryPoints(a,b.c||b)};var k=document.createElement("div");k.innerHTML="123";var s=k.firstChild,
u=t(document);u.appendChild(k);B.setStart(s,1);B.setEnd(s,2);B.deleteContents();"13"==s.data&&(c.deleteContents=function(){this.c.deleteContents();d(this)},c.extractContents=function(){var a=this.c.extractContents();d(this);return a});u.removeChild(k);u=v;q.ra(B,"createContextualFragment")&&(c.createContextualFragment=function(a){return this.c.createContextualFragment(a)});t(document).removeChild(A);B.detach();f.detach();c.getName=aa("WrappedRange");b.wa=g;b.Ba=function(b){b=x(b,a,"createNativeRange");
return b.createRange()}}();if(b.M.Md){var u=function(a,b,e,f,g){var h=a.duplicate();h.collapse(e);var k=h.parentElement();n.tb(b,k)||(k=b);if(!k.canHaveHTML)return k=new s(k.parentNode,n.k(k)),{ya:k,zc:{yc:k.offset,Sb:k.a}};b=n.m(k).createElement("span");b.parentNode&&b.parentNode.removeChild(b);var q,t=e?"StartToStart":"StartToEnd",u=g&&g.Sb==k?g.yc:0,w=k.childNodes.length,x=w;for(g=x;;){g==w?k.appendChild(b):k.insertBefore(b,k.childNodes[g]);h.moveToElementText(b);q=h.compareEndPoints(t,a);if(0==
q||u==x)break;else if(-1==q)if(x==u+1)break;else u=g;else x=x==u+1?u:g;g=Math.floor((u+x)/2);k.removeChild(b)}t=b.nextSibling;if(-1==q&&t&&z(t)){h.setEndPoint(e?"EndToStart":"EndToEnd",a);if(/[\r\n]/.test(t.data)){e=h.duplicate();f=e.text.replace(/\r\n/g,"\r").length;for(f=e.moveStart("character",f);-1==e.compareEndPoints("StartToEnd",e);)f++,e.moveStart("character",1)}else f=h.text.length;e=new s(t,f)}else a=(f||!e)&&b.previousSibling,e=(e=(f||e)&&b.nextSibling)&&z(e)?new s(e,0):a&&z(a)?new s(a,
a.data.length):new s(k,n.k(b));b.parentNode.removeChild(b);return{ya:e,zc:{yc:g,Sb:k}}},h=function(a,b){var e,f,g=a.offset,k=n.m(a.a),h=t(k).createTextRange(),q=z(a.a);q?(e=a.a,f=e.parentNode):(e=a.a.childNodes,e=g<e.length?e[g]:v,f=a.a);k=k.createElement("span");k.innerHTML="&#feff;";e?f.insertBefore(k,e):f.appendChild(k);h.moveToElementText(k);h.collapse(!b);f.removeChild(k);if(q)h[b?"moveStart":"moveEnd"]("character",g);return h};k=function(a){this.ca=a;this.refresh()};k.prototype=new y(document);
k.prototype.refresh=function(){var a,b,e;e=this.ca;a=e.parentElement();var f=e.duplicate();f.collapse(p);b=f.parentElement();f=e.duplicate();f.collapse(E);e=f.parentElement();b=b==e?b:n.gb(b,e);e=b==a?b:n.gb(a,b);0==this.ca.compareEndPoints("StartToEnd",this.ca)?b=a=u(this.ca,e,p,p).ya:(b=u(this.ca,e,p,E),a=b.ya,b=u(this.ca,e,E,E,b.zc).ya);this.setStart(a.a,a.offset);this.setEnd(b.a,b.offset)};k.prototype.getName=aa("WrappedTextRange");y.kd(k);k.ee=function(a){if(a.collapsed)return h(new s(a.startContainer,
a.startOffset),p);var b=h(new s(a.startContainer,a.startOffset),p),e=h(new s(a.endContainer,a.endOffset),E);a=t(y.lb(a)).createTextRange();a.setEndPoint("StartToStart",b);a.setEndPoint("EndToEnd",e);return a};b.We=k;if(!b.M.ha||b.ea.Dc){var e=function(){return this}();"undefined"==typeof e.Fb&&(e.Fb=k);b.Ba=function(b){b=x(b,a,"createNativeRange");return t(b).createTextRange()};b.wa=k}}b.createRange=function(d){d=x(d,a,"createRange");return new b.wa(b.Ba(d))};b.pd=function(b){b=x(b,a,"createRangeManagerRange");
return new y(b)};b.jf=function(d){a.Ca("createIframeRange()","createRange(iframeEl)");return b.createRange(d)};b.kf=function(d){a.Ca("createIframeRangeManagerRange()","createRangeManagerRange(iframeEl)");return b.pd(d)};b.Gb(function(a){var c=a.document;"undefined"==typeof c.createRange&&(c.createRange=function(){return b.createRange(c)});c=a=v})});
la.i("WrappedSelection",function(b,a){function g(a,c){var d=a.X();a.removeAllRanges();for(var e=0,r=d.length;e<r;++e)b.xb(c,d[e])||a.addRange(d[e]);a.rangeCount||x(a)}function k(a){if(a&&a instanceof c)return a.refresh(),a;a=q(a,"getNativeSelection");var b=f(a),d=Y(a),e=ea?y(a):v;b?(b.p=d,b.j=e,b.refresh()):(b=new c(d,e,a),X.push({z:a,selection:b}));return b}function n(a){return"string"==typeof a?"backward"==a:!!a}function q(b,d){if(b){if(G.Yd(b))return b;if(b instanceof c)return b.z;var e=G.dc(b,
a,d);return G.mb(e)}return window}function s(a){return q(a,"getWinSelection").getSelection()}function y(a){return q(a,"getDocSelection").document.selection}function t(a,b,c){var d=c?"end":"start";c=c?"start":"end";a.anchorNode=b[d+"Container"];a.anchorOffset=b[d+"Offset"];a.focusNode=b[c+"Container"];a.focusOffset=b[c+"Offset"]}function x(a){a.anchorNode=a.focusNode=v;a.anchorOffset=a.focusOffset=0;a.rangeCount=0;a.isCollapsed=p;a.e.length=0}function z(a){var c;a instanceof T?(c=b.Ba(a.m()),c.setEnd(a.endContainer,
a.endOffset),c.setStart(a.startContainer,a.startOffset)):a instanceof R?c=a.c:N.ha&&a instanceof G.mb(a.startContainer).Fb&&(c=a);return c}function u(b){var c=b.jb(),d;a:if(!c.length||1!=c[0].nodeType)d=E;else{d=1;for(var e=c.length;d<e;++d)if(!G.mc(c[0],c[d])){d=E;break a}d=p}d||m(a.l("getSingleElementFromRange: range "+b.w()+" did not consist of a single element"));return c[0]}function h(a,b){var c=new R(b);a.e=[c];t(a,c,E);a.rangeCount=1;a.isCollapsed=c.collapsed}function e(a){a.e.length=0;if("None"==
a.j.type)x(a);else{var c=a.j.createRange();if(c&&"undefined"!=typeof c.text)h(a,c);else{a.rangeCount=c.length;for(var d,e=W(c.item(0)),r=0;r<a.rangeCount;++r)d=b.createRange(e),d.selectNode(c.item(r)),a.e.push(d);a.isCollapsed=1==a.rangeCount&&a.e[0].collapsed;t(a,a.e[a.rangeCount-1],E)}}}function d(b,c){for(var d=b.j.createRange(),f=u(c),r=W(d.item(0)),r=U(r).createControlRange(),J=0,na=d.length;J<na;++J)r.add(d.item(J));try{r.add(f)}catch(P){m(a.l("addRange(): Element within the specified Range could not be added to control selection (does it have layout?)"))}r.select();
e(b)}function c(a,b,c){this.p=a;this.j=b;this.e=[];this.z=c;this.refresh()}function l(a){a.z=a.anchorNode=a.focusNode=a.e=v;a.rangeCount=a.anchorOffset=a.focusOffset=0;a.rd=p}function f(a,b){for(var c=X.length,d,r;c--;)if(d=X[c],r=d.selection,"deleteAll"==b)l(r);else if(d.z==a)return"delete"==b?(X.splice(c,1),p):r;"deleteAll"==b&&(X.length=0);return v}function A(b,c){for(var d=W(c[0].startContainer),d=U(d).createControlRange(),f=0,r;f<c.length;++f){r=u(c[f]);try{d.add(r)}catch(J){m(a.l("setRanges(): Element within the one of the specified Ranges could not be added to control selection (does it have layout?)"))}}d.select();
e(b)}function B(a,b){a.z.document!=W(b)&&m(new V("WRONG_DOCUMENT_ERR"))}function L(a){return function(c,d){var e;this.rangeCount?(e=this.getRangeAt(0),e["set"+(a?"Start":"End")](c,d)):(e=b.createRange(this.z.document),e.n(c,d));this.ja(e,this.$())}}function F(a){var b=[],c=new K(a.anchorNode,a.anchorOffset),d=new K(a.focusNode,a.focusOffset),r="function"==typeof a.getName?a.getName():"Selection";if("undefined"!=typeof a.rangeCount)for(var e=0,f=a.rangeCount;e<f;++e)b[e]=T.w(a.getRangeAt(e));return"["+
r+"(Ranges: "+b.join(", ")+")(anchor: "+c.w()+", focus: "+d.w()+"]"}b.q(["DomUtil","DomRange","WrappedRange"]);b.ea.ed=p;var G=b.B,H=b.b,w=H.ra,T=b.Oa,R=b.wa,V=b.Eb,K=G.ka,Y,S,N=b.M,W=G.m,U=G.Y,I=T.xb,P=w(window,"getSelection"),ea=H.rb(document,"selection");N.Af=P;var O=(N.zf=ea)&&(!P||b.ea.Dc);O?(Y=y,b.sc=function(a){a=q(a,"isSelectionValid").document;var b=a.selection;return"None"!=b.type||W(b.createRange().parentElement())==a}):P?(Y=s,b.sc=aa(p)):a.r("Neither document.selection or window.getSelection() detected.");
b.vf=Y;var P=Y(),M=b.Ba(document),D=U(document),Z=H.Ra(P,["anchorNode","focusNode","anchorOffset","focusOffset"]);N.Zf=Z;var da=w(P,"extend");N.$f=da;var Q="number"==typeof P.rangeCount;N.ag=Q;var ia=E,ja=p;H.da(P,["addRange","getRangeAt","removeAllRanges"])&&("number"==typeof P.rangeCount&&N.ha)&&function(){var a=window.getSelection();if(a){var b=U(document),c=b.appendChild(document.createElement("div"));c.contentEditable="false";var d=c.appendChild(document.createTextNode("\u00a0\u00a0\u00a0")),
r=document.createRange();r.setStart(d,1);r.collapse(p);a.addRange(r);ja=1==a.rangeCount;a.removeAllRanges();var e=r.cloneRange();r.setStart(d,0);e.setEnd(d,3);e.setStart(d,2);a.addRange(r);a.addRange(e);ia=2==a.rangeCount;b.removeChild(c);a.removeAllRanges();r.detach();e.detach()}}();N.bg=ia;N.ef=ja;var ca=E;D&&w(D,"createControlRange")&&(D=D.createControlRange(),H.Ra(D,["item","add"])&&(ca=p));N.yf=ca;S=Z?function(a){return a.anchorNode===a.focusNode&&a.anchorOffset===a.focusOffset}:function(a){return a.rangeCount?
a.getRangeAt(a.rangeCount-1).collapsed:E};var $;w(P,"getRangeAt")?$=function(a,b){try{return a.getRangeAt(b)}catch(c){return v}}:Z&&($=function(a){var c=W(a.anchorNode),c=b.createRange(c);c.n(a.anchorNode,a.anchorOffset,a.focusNode,a.focusOffset);c.collapsed!==this.isCollapsed&&c.n(a.focusNode,a.focusOffset,a.anchorNode,a.anchorOffset);return c});var X=[];b.getSelection=k;b.uf=function(c){a.Ca("getIframeSelection()","getSelection(iframeEl)");return b.getSelection(G.Bd(c))};D=c.prototype;if(!O&&Z&&
H.da(P,["removeAllRanges","addRange"])){D.removeAllRanges=function(){this.p.removeAllRanges();x(this)};var ka=function(a,c){var d=T.lb(c),d=b.createRange(d);d.Rb(c.endContainer,c.endOffset);a.p.addRange(z(d));a.p.extend(c.startContainer,c.startOffset);a.refresh()};D.addRange=Q?function(a,c){if(ca&&ea&&"Control"==this.j.type)d(this,a);else if(n(c)&&da)ka(this,a);else{var e;ia?e=this.rangeCount:(this.removeAllRanges(),e=0);this.p.addRange(z(a).cloneRange());this.rangeCount=this.p.rangeCount;this.rangeCount==
e+1?(b.ea.ed&&(e=$(this.p,this.rangeCount-1))&&!I(e,a)&&(a=new R(e)),this.e[this.rangeCount-1]=a,t(this,a,fa(this.p)),this.isCollapsed=S(this)):this.refresh()}}:function(a,b){n(b)&&da?ka(this,a):(this.p.addRange(z(a)),this.refresh())};D.Na=function(a){if(ca&&1<a.length)A(this,a);else{this.removeAllRanges();for(var b=0,c=a.length;b<c;++b)this.addRange(a[b])}}}else if(w(P,"empty")&&w(M,"select")&&ca&&O)D.removeAllRanges=function(){try{if(this.j.empty(),"None"!=this.j.type){var a;if(this.anchorNode)a=
W(this.anchorNode);else if("Control"==this.j.type){var b=this.j.createRange();b.length&&(a=W(b.item(0)))}a&&(U(a).createTextRange().select(),this.j.empty())}}catch(c){}x(this)},D.addRange=function(a){"Control"==this.j.type?d(this,a):(R.ee(a).select(),this.e[0]=a,this.rangeCount=1,this.isCollapsed=this.e[0].collapsed,t(this,a,E))},D.Na=function(a){this.removeAllRanges();var b=a.length;1<b?A(this,a):b&&this.addRange(a[0])};else return a.r("No means of selecting a Range or TextRange was found"),E;D.getRangeAt=
function(a){(0>a||a>=this.rangeCount)&&m(new V("INDEX_SIZE_ERR"));return this.e[a].cloneRange()};var ga;if(O)ga=function(a){var c;b.sc(a.z)?c=a.j.createRange():(c=U(a.z.document).createTextRange(),c.collapse(p));"Control"==a.j.type?e(a):c&&"undefined"!=typeof c.text?h(a,c):x(a)};else if(w(P,"getRangeAt")&&"number"==typeof P.rangeCount)ga=function(a){if(ca&&ea&&"Control"==a.j.type)e(a);else if(a.e.length=a.rangeCount=a.p.rangeCount,a.rangeCount){for(var c=0,d=a.rangeCount;c<d;++c)a.e[c]=new b.wa(a.p.getRangeAt(c));
t(a,a.e[a.rangeCount-1],fa(a.p));a.isCollapsed=S(a)}else x(a)};else if(Z&&"boolean"==typeof P.isCollapsed&&"boolean"==typeof M.collapsed&&N.ha)ga=function(a){var b;b=a.p;b.anchorNode?(b=$(b,0),a.e=[b],a.rangeCount=1,b=a.p,a.anchorNode=b.anchorNode,a.anchorOffset=b.anchorOffset,a.focusNode=b.focusNode,a.focusOffset=b.focusOffset,a.isCollapsed=S(a)):x(a)};else return a.r("No means of obtaining a Range or TextRange from the user's selection was found"),E;D.refresh=function(a){var b=a?this.e.slice(0):
v,c=this.anchorNode,d=this.anchorOffset;ga(this);if(a){a=b.length;if(a!=this.e.length||this.anchorNode!=c||this.anchorOffset!=d)return p;for(;a--;)if(!I(b[a],this.e[a]))return p;return E}};D.removeRange=ca?function(a){if("Control"==this.j.type){var b=this.j.createRange();a=u(a);for(var c=W(b.item(0)),c=U(c).createControlRange(),d,r=E,J=0,f=b.length;J<f;++J)d=b.item(J),d!==a||r?c.add(b.item(J)):r=p;c.select();e(this)}else g(this,a)}:function(a){g(this,a)};var fa;!O&&Z&&N.ha?(fa=function(a){var b=E;
a.anchorNode&&(b=1==G.Za(a.anchorNode,a.anchorOffset,a.focusNode,a.focusOffset));return b},D.$=function(){return fa(this)}):fa=D.$=aa(E);D.Bf=D.$;D.toString=function(){for(var a=[],b=0,c=this.rangeCount;b<c;++b)a[b]=""+this.e[b];return a.join("")};D.collapse=function(a,c){B(this,a);var d=b.createRange(a);d.Rb(a,c);this.ja(d);this.isCollapsed=p};D.collapseToStart=function(){if(this.rangeCount){var a=this.e[0];this.collapse(a.startContainer,a.startOffset)}else m(new V("INVALID_STATE_ERR"))};D.collapseToEnd=
function(){if(this.rangeCount){var a=this.e[this.rangeCount-1];this.collapse(a.endContainer,a.endOffset)}else m(new V("INVALID_STATE_ERR"))};D.selectAllChildren=function(a){B(this,a);var c=b.createRange(a);c.selectNodeContents(a);this.removeAllRanges();this.addRange(c)};D.deleteFromDocument=function(){if(ca&&ea&&"Control"==this.j.type){for(var a=this.j.createRange(),b;a.length;)b=a.item(0),a.remove(b),b.parentNode.removeChild(b);this.refresh()}else if(this.rangeCount&&(a=this.X(),a.length)){this.removeAllRanges();
b=0;for(var c=a.length;b<c;++b)a[b].deleteContents();this.addRange(a[c-1])}};D.Da=function(a,b){for(var c=0,d=this.e.length;c<d;++c)if(a(this.getRangeAt(c)))return b};D.X=function(){var a=[];this.Da(function(b){a.push(b)});return a};D.ja=function(a,b){this.removeAllRanges();this.addRange(a,b)};D.Kb=function(a,b){var c=[];this.Da(function(d){c.push(d[a].apply(d,b))});return c};D.setStart=L(p);D.setEnd=L(E);b.Hc.select=function(a){k(this.m()).ja(this,a)};D.Nb=function(a){var b=[],c=this.$();this.Da(function(c){a(c);
b.push(c)});this.removeAllRanges();c&&1==b.length?this.addRange(b[0],"backward"):this.Na(b)};D.containsNode=function(a,b){return this.Da(function(c){return c.containsNode(a,b)},p)};D.getBookmark=function(a){return{ma:this.$(),ce:this.Kb("getBookmark",[a])}};D.moveToBookmark=function(a){for(var c=[],d=0,e,r;e=a.ce[d++];)r=b.createRange(this.z),r.moveToBookmark(e),c.push(r);a.ma?this.ja(c[0],"backward"):this.Na(c)};D.ze=function(){return this.Kb("toHtml").join("")};D.getName=aa("WrappedSelection");
D.w=function(){return F(this)};D.detach=function(){f(this.z,"delete");l(this)};c.qf=function(){f(v,"deleteAll")};c.w=F;c.Ud=n;b.Vc=c;b.pe=D;b.Gb(function(a){"undefined"==typeof a.getSelection&&(a.getSelection=function(){return k(a)});a=v})});la.i("CssClassApplier",function(b,a){function g(a,b){return a.className&&RegExp("(?:^|\\s)"+b+"(?:\\s|$)").test(a.className)}function k(a,b){a.className?g(a,b)||(a.className+=" "+b):a.className=b}function n(a){return a.split(/\s+/).sort().join(" ")}function q(a,b){return n(a.className)==n(b.className)}function s(a,b,c,d){-1==c&&(c=b.childNodes.length);for(var e=a.parentNode,f=H.k(a),g=0,l;l=d[g++];){var k=l.a,h=l.offset,n=k,A=h;k==b&&h>c&&A++;if(k==e&&(h==f||h==f+1))n=b,A+=c-f;k==e&&h>f+1&&A--;l.a=
n;l.offset=A}b.childNodes.length==c?b.appendChild(a):b.insertBefore(a,b.childNodes[c])}function y(a,b){for(var c=a.parentNode,d=H.k(a),e,f=[];e=a.firstChild;)s(e,c,d++,b),f.push(e);a.parentNode.removeChild(a);return f}function t(a,b){var c=a.cloneRange();c.selectNodeContents(b);var d=c.Ga(a),d=d?d.toString():"";c.detach();return""!=d}function x(a){for(var b=a.jb([3]),c=0,d;(d=b[c])&&!t(a,d);)++c;for(var e=b.length-1;(d=b[e])&&!t(a,d);)--e;return b.slice(c,e+1)}function z(a,b){if(a.attributes.length!=
b.attributes.length)return E;for(var c=0,d=a.attributes.length,e,f;c<d;++c)if(e=a.attributes[c],f=e.name,"class"!=f&&(f=b.attributes.getNamedItem(f),e.specified!=f.specified||e.specified&&e.nodeValue!==f.nodeValue))return E;return p}function u(a,b){for(var c=0,d=a.attributes.length,e;c<d;++c)if(e=a.attributes[c].name,(!b||!T(b,e))&&a.attributes[c].specified&&"class"!=e)return p;return E}function h(a,b){var c,d;for(d in b)if(b.hasOwnProperty(d))if(c=b[d],"object"==typeof c){if(!h(a[d],c))return E}else if(a[d]!==
c)return E;return p}function e(a){var b;return a&&1==a.nodeType&&((b=a.parentNode)&&9==b.nodeType&&"on"==b.designMode||K(a)&&!K(a.parentNode))}function d(a){return(K(a)||1!=a.nodeType&&K(a.parentNode))&&!e(a)}function c(a){return a&&1==a.nodeType&&!Y.test(V(a,"display"))}function l(a){if(0==a.data.length)return p;if(S.test(a.data))return E;switch(V(a.parentNode,"whiteSpace")){case "pre":case "pre-wrap":case "-moz-pre-wrap":return E;case "pre-line":if(/[\r\n]/.test(a.data))return E}return c(a.previousSibling)||
c(a.nextSibling)}function f(a){var b=[],c,d;for(c=0;d=a[c++];)b.push(new w(d.startContainer,d.startOffset),new w(d.endContainer,d.endOffset));return b}function A(a,b){for(var c=0,d,e,f,g=a.length;c<g;++c)d=a[c],e=b[2*c],f=b[2*c+1],d.n(e.a,e.offset,f.a,f.offset)}function B(b,c,d,e){var f,g;g=0==d;if(H.mc(c,b))return b;H.N(c)&&(f=H.k(c),0==d?d=f:d==c.length?d=f+1:m(a.l("splitNodeAt() should not be called with offset in the middle of a data node ("+d+" in "+c.data)),c=c.parentNode);if(H.N(c)?0==d?c.previousSibling:
d==c.length?c.nextSibling:1:0<d&&d<c.childNodes.length){f=c.cloneNode(E);g=c.parentNode;f.id&&f.removeAttribute("id");for(var l,k=0;l=c.childNodes[d];)s(l,f,k++,e);s(f,g,H.k(c)+1,e);return c==b?f:B(b,g,H.k(f),e)}return b!=c?(f=c.parentNode,c=H.k(c),g||c++,B(b,f,c,e)):b}function L(a){var b=a?"nextSibling":"previousSibling";return function(c,d){var e=c.parentNode,f=c[b];if(f){if(f&&3==f.nodeType)return f}else if(d&&(f=e[b])&&1==f.nodeType&&e.tagName==f.tagName&&q(e,f)&&z(e,f)&&"inline"==V(e,"display")&&
"inline"==V(f,"display"))return f[a?"firstChild":"lastChild"];return v}}function F(a){this.Vd=1==a.nodeType;this.J=[];(a=this.Vd?a.lastChild:a)&&(this.J[0]=a)}function G(a,b,c){this.V=a;var d,e,f=v;if("object"==typeof b&&b!==v){c=b.ba;f=b.T;for(d=0;e=U[d++];)b.hasOwnProperty(e)&&(this[e]=b[e]);d=b.normalize}else d=b;this.normalize="undefined"==typeof d?p:d;this.Ta=[];d=document.createElement(this.qa);this.T=this.Vb(f,d,p);this.td=this.T.hasOwnProperty("className")?this.T.className:a;this.Ib=E;a=typeof c;
if("string"==a)"*"==c?this.Ib=p:this.ba=c.toLowerCase().replace(/^\s\s*/,"").replace(/\s\s*$/,"").split(/\s*,\s*/);else if("object"==a&&"number"==typeof c.length){this.ba=[];d=0;for(a=c.length;d<a;++d)"*"==c[d]?this.Ib=p:this.ba.push(c[d].toLowerCase())}else this.ba=[this.qa]}b.q(["WrappedSelection","WrappedRange"]);var H=b.B,w=H.ka,T=H.Sa,R=function(){function a(b,c,d){return c&&d?" ":""}return function(b,c){b.className&&(b.className=b.className.replace(RegExp("(^|\\s)"+c+"(\\s|$)"),a))}}(),V=H.cc,
K;(function(){K="boolean"==typeof document.createElement("div").isContentEditable?function(a){return a&&1==a.nodeType&&a.isContentEditable}:function(a){return!a||1!=a.nodeType||"false"==a.contentEditable?E:"true"==a.contentEditable||K(a.parentNode)}})();var Y=/^inline(-block|-table)?$/i,S=/[^\r\n\t\f \u200B]/,N=L(E),W=L(p);F.prototype={sd:function(a){var b=this.J,c=b[0];if(1<b.length){for(var d=[],e=0,f,g,l=0,k=b.length,h;l<k;++l){f=b[l];g=f.parentNode;if(0<l&&(g.removeChild(f),g.hasChildNodes()||
g.parentNode.removeChild(g),a))for(g=0;h=a[g++];)h.a==f&&(h.a=c,h.offset+=e);d[l]=f.data;e+=f.data.length}c.data=d.join("")}return c.data},ib:function(){for(var a=this.J.length,b=0;a--;)b+=this.J[a].length;return b},toString:function(){for(var a=[],b=0,c=this.J.length;b<c;++b)a[b]="'"+this.J[b].data+"'";return"[Merge("+a.join(",")+")]"}};var U=["elementTagName","ignoreWhiteSpace","applyToEditableOnly","useExistingElements","removeEmptyElements"],I={};G.prototype={qa:"mark",T:{},ic:p,Zc:E,Ge:p,Kc:p,
Vb:function(a,b,c){var d,e,f={},g,l,h;for(h in a)if(a.hasOwnProperty(h))if(l=a[h],e=b[h],"className"==h)k(b,l),k(b,this.V),b[h]=n(b[h]),c&&(f[h]=b[h]);else if("style"==h){c&&(f[h]=g={});for(d in a[h])e[d]=l[d],c&&(g[d]=e[d]);this.Ta.push(h)}else b[h]=l,c&&(f[h]=b[h],l=I.hasOwnProperty(h)?I[h]:h,this.Ta.push(l));return c?f:""},gc:function(a){return 1==a.nodeType&&T(this.ba,a.tagName.toLowerCase())&&g(a,this.V)},ec:function(a){for(;a;){if(this.gc(a))return a;a=a.parentNode}return v},sb:function(a){return!this.Zc||
d(a)},Wd:function(a){return this.ic&&a&&3==a.nodeType&&l(a)},Cc:function(a,b,c,d){for(var e=a[0],f=a[a.length-1],g=[],l,h=e,k=f,n=0,A=f.length,q,B,s=0,t=a.length;s<t;++s)q=a[s],(B=N(q,!d))?(l||(l=new F(B),g.push(l)),l.J.push(q),q===e&&(h=l.J[0],n=h.length),q===f&&(k=l.J[0],A=l.ib())):l=v;if(a=W(f,!d))l||(l=new F(f),g.push(l)),l.J.push(a);if(g.length){s=0;for(t=g.length;s<t;++s)g[s].sd(c);b.n(h,n,k,A)}},md:function(a){a=a.createElement(this.qa);this.Vb(this.T,a,E);k(a,this.V);return a},ad:function(a){var b=
a.parentNode;1==b.childNodes.length&&this.Ge&&T(this.ba,b.tagName.toLowerCase())&&h(b,this.T)?k(b,this.V):(b=this.md(H.m(a)),a.parentNode.insertBefore(b,a),b.appendChild(a))},rc:function(a){return a.tagName.toLowerCase()==this.qa&&n(a.className)==this.td&&h(a,this.T)&&!u(a,this.Ta)&&this.sb(a)},oc:function(a){var b=a.childNodes.length;return 1==a.nodeType&&this.rc(a)&&(0==b||1==b&&this.oc(a.firstChild))},Jc:function(a){var b=this;a=a.jb([1],function(a){return b.oc(a)});for(var c=0,d;d=a[c++];)d.parentNode.removeChild(d)},
Ce:function(a,b,c,d){b.containsNode(c)||(a=b.cloneRange(),a.selectNode(c),a.isPointInRange(b.endContainer,b.endOffset)&&(B(c,b.endContainer,b.endOffset,d),b.setEndAfter(c)),a.isPointInRange(b.startContainer,b.startOffset)&&(c=B(c,b.startContainer,b.startOffset,d)));this.rc(c)?y(c,d):R(c,this.V)},$c:function(a,b){b=b||[];var c=f(b||[]);a.Nc(c);this.Kc&&this.Jc(a);var d=x(a);if(d.length){for(var e=0,l;l=d[e++];)!this.Wd(l)&&(!this.ec(l)&&this.sb(l))&&this.ad(l,c);l=d[d.length-1];a.n(d[0],0,l,l.length);
this.normalize&&this.Cc(d,a,c,E);A(b,c)}},Be:function(a,b){b=b||[];var c=f(b);a.Nc(c);this.Kc&&this.Jc(a,c);var d=x(a),e,l,g=d[d.length-1];if(d.length){for(var h=0,k=d.length;h<k;++h)e=d[h],(l=this.ec(e))&&this.sb(e)&&this.Ce(e,a,l,c),a.n(d[0],0,g,g.length);this.normalize&&this.Cc(d,a,c,p);A(b,c)}},detach:function(){}};G.b={gc:g,Xe:k,Sf:R,wf:q,Uf:y,sf:z,rf:u,fg:B,Gf:K,Hf:e,Ff:d};b.Ne=b.Me=G;b.ab=b.gf=function(a,b,c){return new G(a,b,c)}});la.i("Highlighter",function(b){function a(a,b){this.type=a;this.jd=b}function g(b,d){u[b]=new a(b,d)}function k(a,b){this.start=a;this.end=b}function n(a,b,c,l,f,g){f?(this.id=f,z=Math.max(z,f+1)):this.id=z++;this.L=b;this.S=a;this.Wa=c;this.Aa=l;this.$a=g||v;this.Qa=E}function q(b,d){this.S=b||document;this.Xa={};this.o=[];var c;var l=d||"textContent",f=u[l];f instanceof a?c=f.create():m(Error("Highlighter type '"+l+"' is not valid"));this.Aa=c}b.q(["CssClassApplier"]);var s=b.B,y=s.Sa,t=s.Y,x=[].forEach?
function(a,b){a.forEach(b)}:function(a,b){for(var c=0,l=a.length;c<l;++c)b(a[c])},z=1,u={};a.prototype.create=function(){var a=this.jd();a.type=this.type;return a};b.Rf=g;k.prototype={Pd:function(a){return this.start<a.end&&this.end>a.start},Tc:function(a){return new k(Math.min(this.start,a.start),Math.max(this.end,a.end))},Ga:function(a){return new k(Math.max(this.start,a.start),Math.min(this.end,a.end))},toString:function(){return"[CharacterRange("+this.start+", "+this.end+")]"}};k.Zb=function(a){return new k(a.start,
a.end)};var h={Ic:function(a,b){var c=a.getBookmark(b);return new k(c.start,c.end)},Ua:function(a,d,c){a=b.createRange(a);a.moveToBookmark({start:d.start,end:d.end,Tb:c});return a},zb:function(a,b){for(var c=a.X(),l=[],f=1==c.length&&a.$(),g=0,h=c.length;g<h;++g)l[g]={L:this.Ic(c[g],b),ma:f};return l},Mc:function(a,b,c){a.removeAllRanges();for(var l=a.z.document,f=0,g=b.length,h,k;f<g;++f)k=b[f],h=this.Ua(l,k.L,c),a.addRange(h,k.ma)}};g("textContent",function(){return h});g("TextRange",function(){var a;
return function(){if(!a){var d=b.wc.Ve;d?d.G||m(Error("TextRange module is present but not supported.")):m(Error("TextRange module is missing."));a={Ic:function(a,b){return k.Zb(a.Qc(b))},Ua:function(a,d,e){a=b.createRange(a);a.La(e,d.start,d.end);return a},zb:function(a,b){return a.oe(b)},Mc:function(a,b,d){a.me(d,b)}}}return a}}());n.prototype={Ad:function(){return this.$a?this.S.getElementById(this.$a):t(this.S)},kb:function(){return this.Aa.Ua(this.S,this.L,this.Ad())},Sc:function(){this.Wa.Be(this.kb());
this.Qa=E},apply:function(){this.Wa.$c(this.kb());this.Qa=p},toString:function(){return"[Highlight(ID: "+this.id+", class: "+this.Wa.V+", character range: "+this.L.start+" - "+this.L.end+")]"}};q.prototype={Wc:function(a){this.Xa[a.V]=a},le:function(a){for(var b=0,c=this.o.length,g;b<c;++b)g=this.o[b],y(a,g)&&(g.Sc(),this.o.splice(b--,1))},Cd:function(a){var b=[],c=this.o;x(a,function(a){x(c,function(c){a.lc(c.kb())&&!y(b,c)&&b.push(c)})});return b},Kd:function(a,d,c){var g,f,h,q=this.o,s=this.Aa,
t=this.S,u=[];a=this.Xa[a];c=c||v;var y;if(c&&(g=this.S.getElementById(c)))f=b.createRange(this.S),f.selectNodeContents(g),y=new k(0,f.toString().length),f.detach();var w,z;g=0;for(f=d.length;g<f;++g){w=d[g];y&&(w=w.Ga(y));for(h=0;h<q.length;++h)c==q[h].$a&&(z=q[h].L,z.Pd(w)&&(u.push(q[h]),q[h]=new n(t,z.Tc(w),a,s,v,c)));q.push(new n(t,w,a,s,v,c))}x(u,function(a){a.Sc()});var R=[];x(q,function(a){a.Qa||(a.apply(),R.push(a))});return R},Ld:function(a,d,c){var g=this.Aa;d=d||b.getSelection();var f=
this.Xa[a],h=d.z.document,h=c?h.getElementById(c):t(h);f||m(Error("No class applier found for class '"+a+"'"));var f=g.zb(d,h),n=[];x(f,function(a){n.push(k.Zb(a.L))});a=this.Kd(a,n,c);g.Mc(d,f,h);return a},De:function(a){a=a||b.getSelection();var d=this.Cd(a.X());this.le(d);a.removeAllRanges()}};b.Oe=q;b.bb=function(a,b){return new q(a,b)}});la.i("Serializer",function(b,a){function g(a,b){b=b||[];var c=a.nodeType,h=a.childNodes,f=h.length,k=[c,a.nodeName,f].join(":"),n="",q="";switch(c){case 3:n=a.nodeValue.replace(/</g,"&lt;").replace(/>/g,"&gt;");break;case 8:n="\x3c!--"+a.nodeValue.replace(/</g,"&lt;").replace(/>/g,"&gt;")+"--\x3e";break;default:n="<"+k+">",q="</>"}n&&b.push(n);for(c=0;c<f;++c)g(h[c],b);q&&b.push(q);return b}function k(a){a=g(a).join("");return u(a).toString(16)}function n(a,b,c){var g=[],f=a;for(c=c||h.m(a).documentElement;f&&
f!=c;)g.push(h.k(f,p)),f=f.parentNode;return g.join("/")+":"+b}function q(b,d,c){d||(d=(c||document).documentElement);b=b.split(":");c=b[0]?b[0].split("/"):[];for(var g=c.length,f;g--;)f=parseInt(c[g],10),f<d.childNodes.length?d=d.childNodes[f]:m(a.l("deserializePosition() failed: node "+h.ia(d)+" has no child with index "+f+", "+g));return new h.ka(d,parseInt(b[1],10))}function s(e,d,c){c=c||b.Oa.lb(e).documentElement;h.tb(c,e.commonAncestorContainer)||m(a.l("serializeRange(): range "+e.w()+" is not wholly contained within specified root node "+
h.ia(c)));e=n(e.startContainer,e.startOffset,c)+","+n(e.endContainer,e.endOffset,c);d||(e+="{"+k(c)+"}");return e}function y(e,d,c){d?c=c||h.m(d):(c=c||document,d=c.documentElement);e=/^([^,]+),([^,\{]+)(\{([^}]+)\})?$/.exec(e);var g=e[4],f=k(d);g&&g!==k(d)&&m(a.l("deserializeRange(): checksums of serialized range root node ("+g+") and target root node ("+f+") do not match"));g=q(e[1],d,c);d=q(e[2],d,c);c=b.createRange(c);c.n(g.a,g.offset,d.a,d.offset);return c}function t(a,b,c){b||(b=(c||document).documentElement);
a=/^([^,]+),([^,]+)(\{([^}]+)\})?$/.exec(a)[3];return!a||a===k(b)}function x(a,d,c){a=b.getSelection(a);a=a.X();for(var g=[],f=0,h=a.length;f<h;++f)g[f]=s(a[f],d,c);return g.join("|")}function z(a,d,c){d?c=c||h.mb(d):(c=c||window,d=c.document.documentElement);a=a.split("|");for(var g=b.getSelection(c),f=[],k=0,n=a.length;k<n;++k)f[k]=y(a[k],d,c.document);g.Na(f);return g}b.q(["WrappedSelection","WrappedRange"]);("undefined"==typeof encodeURIComponent||"undefined"==typeof decodeURIComponent)&&a.r("Global object is missing encodeURIComponent and/or decodeURIComponent method");
var u=function(){var a=v;return function(b){for(var c=[],g=0,f=b.length,h;g<f;++g)h=b.charCodeAt(g),128>h?c.push(h):2048>h?c.push(h>>6|192,h&63|128):c.push(h>>12|224,h>>6&63|128,h&63|128);b=-1;if(!a){for(var g=[],f=0,k;256>f;++f){k=f;for(h=8;h--;)k=1==(k&1)?k>>>1^3988292384:k>>>1;g[f]=k>>>0}a=g}g=a;f=0;for(h=c.length;f<h;++f)k=(b^c[f])&255,b=b>>>8^g[k];return(b^-1)>>>0}}(),h=b.B;b.dg=n;b.pf=q;b.Ma=s;b.qd=y;b.af=t;b.zb=x;b.cb=z;b.bf=function(a,b,c){var g;b?g=c?c.document:h.m(b):(c=c||window,b=c.document.documentElement);
a=a.split("|");c=0;for(var f=a.length;c<f;++c)if(!t(a[c],b,g))return E;return p};b.Wf=function(a){a=a||window;var b;a:{b=a.document.cookie.split(/[;,]/);for(var c=0,g=b.length,f;c<g;++c)if(f=b[c].split("="),"RangeManagerSerializedSelection"==f[0].replace(/^\s+/,"")&&(f=f[1])){b=decodeURIComponent(f.replace(/\s+$/,""));break a}b=v}b&&z(b,a.S)};b.Xf=function(a,d){a=a||window;d="object"==typeof d?d:{};var c=d.ud?";expires="+d.ud.toUTCString():"",g=d.path?";path="+d.path:"",f=d.domain?";domain="+d.domain:"",
h=d.Yf?";secure":"",k=x(b.getSelection(a));a.document.cookie=encodeURIComponent("RangeManagerSerializedSelection")+"="+encodeURIComponent(k)+c+g+f+h};b.hb=k;b.Nf=g});la.i("TextRange",function(b,a){function g(a,b){if(a){var c={};S(c,b);S(c,a);return c}return b}function k(a){var b,c;return a?(b=a.language||ea,c={},S(c,da[b]||da[ea]),S(c,a),c):da[ea]}function n(a,b){var c=$(a,"display",b),d=a.tagName.toLowerCase();return"block"==c&&X&&ka.hasOwnProperty(d)?ka[d]:c}function q(a){for(var b=a,c=[];b.parentNode;)c.unshift(b.parentNode),b=b.parentNode;a=c.concat([a]);b=0;for(c=a.length;b<c;++b)if(1==a[b].nodeType&&"none"==n(a[b]))return p;return E}function s(a,b){var c;
if(!b&&a.hasChildNodes())c=a.firstChild;else{for(c=a;c&&!c.nextSibling;)c=c.parentNode;c=!c?v:c.nextSibling}return c}function y(a){var b=a.previousSibling;if(b){for(a=b;a.hasChildNodes();)a=a.lastChild;return a}return(a=a.parentNode)&&1==a.nodeType?a:v}function t(a){if(!a||3!=a.nodeType)return E;var b=a.data;if(""===b)return p;var c=a.parentNode;if(!c||1!=c.nodeType)return E;a=$(a.parentNode,"whiteSpace");return/^[\t\n\r ]+$/.test(b)&&/^(normal|nowrap)$/.test(a)||/^[\t\r ]+$/.test(b)&&"pre-line"==
a}function x(a){return""===a.data?p:!t(a)?E:!a.parentNode||q(a)?p:E}function z(a){var b=a.nodeType,c;if(!(c=7==b)){if(!(b=8==b))if(!(b=q(a)))if(!(b=/^(script|style)$/i.test(a.nodeName)))var d,b=3==a.nodeType&&(d=a.parentNode)&&"hidden"==$(d,"visibility")||x(a);c=b}return c}function u(a,b){var c=a.nodeType;return 7==c||8==c||1==c&&"none"==n(a,b)}function h(){this.Bb={}}function e(a,b,c){return function(d){var e=this.za;if(e.hasOwnProperty(a))return ga++,e[a];fa++;d=b.call(this,c?this[c]:this,d);return e[a]=
d}}function d(a,b){this.node=this.a=a;this.F=b;this.za=new h;this.ae=new h}function c(a,b){this.offset=b;this.sa=a;this.a=a.a;this.F=a.F;this.za=new h}function l(){f();return ha=new ma}function f(){ha&&ha.detach();ha=v}function A(b,c,d,e){function f(){var a=v;c?(a=g,h||(g=g.U(),h=!g||d&&g.W(d))):h||(a=g=g.Ka(),h=!g||d&&g.W(d));h&&(g=v);return a}d&&(c?z(d.a)&&(d=b.U()):z(d.a)&&(d=d.Ka()));var g=b,h=E,k,l=E;return{next:function(){if(l)return l=E,k;for(var a,b;a=f();)if(b=a.ac(e))return k=a;return v},
ne:function(){k?l=p:m(a.l("createCharacterIterator: cannot rewind. Only one position can be rewound."))},H:function(){b=d=v}}}function B(a,b,c){function d(a){for(var b,c=[],r=a?e:f,g=E,h=E;a=r.next();){b=a.h;if(I.test(b))h&&(h=E,g=p);else if(g){r.ne();break}else h=p;c.push(a)}return c}var e=A(a,E,v,b),f=A(a,p,v,b),g=c.Ae;a=d(p);b=d(E).reverse();var h=g(b.concat(a),c),k=a.length?h.slice(oa(h,a[0].Rc)):[],l=b.length?h.slice(0,oa(h,b.pop().Rc)+1):[];return{vb:function(){for(var a,b;1==k.length&&!(a=
k[0]).ub&&0<(b=d(p)).length;)k=g(a.R.concat(b),c);return k.shift()},wb:function(){for(var a,b;1==l.length&&!(a=l[0]).ub&&0<(b=d(E)).length;)l=g(b.reverse().concat(a.R),c);return l.pop()},H:function(){e.H();f.H();k=l=v}}}function L(a,b,c,d){var e=a.I(b,p);a=a.I(b,E);return A(d?a:e,!!d,d?e:a,c)}function F(a,c,d,e,f){function g(a,c){var d=k[a].U(),e=k[c-1],r;if(!(r=!f.Uc)){var h=f.K;r=b.createRange(d.a);r.n(d.a,d.offset,e.a,e.offset);h=!r.expand("word",h);r.detach();r=h}return{Ab:d,eb:e,valid:r}}var h=
O(f.direction);a=A(a,h,a.F.I(e,h),f);e="";for(var k=[],l,n,q,s,t,u=v;l=a.next();)if(n=l.h,!d&&!f.Mb&&(n=n.toLowerCase()),h?(k.unshift(l),e=n+e):(k.push(l),e+=n),d){if(l=c.exec(e))if(t){if(q=l.index,s=q+l[0].length,!h&&s<e.length||h&&0<q){u=g(q,s);break}}else t=p}else if(-1!=(q=e.indexOf(c))){u=g(q,q+c.length);break}t&&(u=g(q,s));a.H();return u}function G(a){return function(){var b=!!ha,c=[ha||l()].concat(Y.ye(arguments)),c=a.apply(this,c);b||f();return c}}function H(a,b){return G(function(c,d,e,f){var h,
l;"undefined"==typeof e&&(e=d,d=R);f=g(f,ia);h=g(f.v,D);var n=k(f.K);f=a;b&&(f=0<=e,this.collapse(!f));c=c.I(this,f);var q=d;d=0;var s=c,t=Math.abs(e);if(0!==e){e=0>e;switch(q){case R:for(n=A(c,e,v,h);(l=n.next())&&d<t;)++d,s=l;n.H();break;case V:for(var n=B(c,h,n),u=e?n.wb:n.vb;(n=u())&&d<t;)n.ub&&(++d,s=e?n.R[0]:n.R[n.R.length-1]);break;default:m(Error("movePositionBy: unit '"+q+"' not implemented"))}e?(s=s.U(),d=-d):s&&s.qc&&(q==V&&(n=A(c,E,v,h),l=n.next(),n.H()),l&&(s=l.U()))}h=s;l=d;this[f?"setStart":
"setEnd"](h.a,h.offset);return l})}function w(a){return G(function(b,c){c=g(c,D);for(var d,e=L(b,this,c,!a),f=0;(d=e.next())&&I.test(d.h);)++f;e.H();if(d=0<f)this[a?"moveStart":"moveEnd"]("character",a?f:-f,{v:c});return d})}function T(a){return G(function(b,c){var d=E;this.Nb(function(b){d=b[a](c)||d});return d})}b.q(["WrappedSelection"]);var R="character",V="word",K=b.B,Y=b.b,S=Y.extend,N=K.Y,W=/^[ \t\f\r\n]+$/,U=/^[ \t\f\r]+$/,I=/^[\t-\r \u0085\u00A0\u1680\u180E\u2000-\u200B\u2028\u2029\u202F\u205F\u3000]+$/,
P=/^[\t \u00A0\u1680\u180E\u2000-\u200B\u202F\u205F\u3000]+$/,ea="en",O=b.Vc.Ud,M=E;(function(){var a=document.createElement("div");a.contentEditable="true";a.innerHTML="<p>1 </p><p></p>";var c=N(document),d=a.firstChild,e=b.getSelection();c.appendChild(a);e.collapse(d.lastChild,2);e.setStart(d.firstChild,0);a.innerHTML="1 <br>";e.collapse(a,2);e.setStart(a.firstChild,0);M=1==(""+e).length;c.removeChild(a);e.removeAllRanges()})();var D={ob:p,qb:p,pb:p},Z={ob:E,qb:!M,pb:p},da={en:{Ke:/[a-z0-9]+('[a-z0-9]+)*/gi,
jc:E,Ae:function(a,b){function c(b,d,e){var g=a.slice(b,d);b={ub:e,R:g,toString:function(){return g.join("")}};d=0;for(e=g.length;d<e;++d)g[d].Rc=b;f.push(b)}for(var d=a.join(""),e,f=[],g=0,h;e=b.Ke.exec(d);){h=e.index;e=h+e[0].length;h>g&&c(g,h,E);if(b.jc)for(;P.test(a[e]);)++e;c(h,e,p);g=e}g<a.length&&c(g,a.length,E);return f}}},Q={Mb:E,Je:v,Uc:E,Le:E,direction:"forward",K:v,v:v},ia={K:v,v:v},ja={K:v,v:v,trim:E,va:p,ua:p},ca={K:v,v:v,direction:"forward"},$=K.cc,X;(function(){var a=document.createElement("table"),
b=N(document);b.appendChild(a);X="block"==$(a,"display");b.removeChild(a)})();b.M.hg=X;var ka={gg:"table",caption:"table-caption",df:"table-column-group",cf:"table-column",mg:"table-header-group",ig:"table-row-group",kg:"table-footer-group",ng:"table-row",jg:"table-cell",lg:"table-cell"};h.prototype={get:function(a){return this.Bb.hasOwnProperty(a)?this.Bb[a]:v},set:function(a,b){return this.Bb[a]=b}};var ga=0,fa=0;b.Vf=function(){console.log("Cached: "+ga+", uncached: "+fa)};var C={D:function(a){var b=
this.ae;return b.get(a)||b.set(a,new c(this,a))},toString:function(){return"[NodeWrapper("+K.ia(this.a)+")]"}};d.prototype=C;S(C,{N:e("isCharacterDataNode",K.N,"node"),k:e("nodeIndex",K.k,"node"),ib:e("nodeLength",K.Ea,"node"),Ub:e("containsPositions",function(a){return K.N(a)||!/^(area|base|basefont|br|col|frame|hr|img|input|isindex|link|meta|param)$/i.test(a.nodeName)},"node"),Lf:e("isWhitespace",t,"node"),Df:e("isCollapsedWhitespace",x,"node"),bc:e("computedDisplay",n,"node"),isCollapsed:e("collapsed",
z,"node"),If:e("ignored",u,"node"),next:e("nextPos",s,"node"),Gc:e("previous",y,"node"),Jd:e("textNodeInfo",function(a){var b=v,c=E,d=$(a.parentNode,"whiteSpace"),e="pre-line"==d;if(e)b=U,c=p;else if("normal"==d||"nowrap"==d)b=W,c=p;return{a:a,text:a.data,te:b,gd:c,be:e}},"node"),hc:e("hasInnerText",function(a,b){for(var c=this.F,d=c.D(a.parentNode,this.k()+1),e=c.D(a,0),c=b?d:e,d=b?e:d;c!==d;){c.Ec();if(c.Td())return p;c=b?c.U():c.Ka()}return E},"node"),fc:e("trailingSpace",function(a){if("br"!=
a.tagName.toLowerCase())switch(this.bc()){case "inline":for(a=a.lastChild;a;){if(!u(a))return 1==a.nodeType?this.F.ga(a).fc():"";a=a.previousSibling}break;case "inline-block":case "inline-table":case "none":case "table-column":case "table-column-group":break;case "table-cell":return"\t";default:return this.hc(p)?"\n":""}return""},"node"),Dd:e("leadingSpace",function(){switch(this.bc()){case "inline":case "inline-block":case "inline-table":case "none":case "table-column":case "table-column-group":case "table-cell":break;
default:return this.hc(E)?"\n":""}return""},"node")});C={h:"",oa:"EMPTY",nc:E,Ec:function(){if(!this.Fc){var a=this.a,b=this.offset,c="",d="EMPTY",e=E;if(0<b)if(3==a.nodeType){var a=a.data,f=a.charAt(b-1),g=this.sa.Jd(),h=g.te;g.gd?h.test(f)?1<b&&h.test(a.charAt(b-2))||(g.be&&"\n"===a.charAt(b)?(c=" ",d="PRE_LINE_TRAILING_SPACE_BEFORE_LINE_BREAK"):(c=" ",d="COLLAPSIBLE_SPACE")):(c=f,d="NON_SPACE",e=p):(c=f,d="UNCOLLAPSIBLE_SPACE",e=p)}else{if((f=a.childNodes[b-1])&&1==f.nodeType&&!z(f))"br"==f.tagName.toLowerCase()?
(c="\n",this.nc=p,d="COLLAPSIBLE_SPACE",e=E):this.Pb=p;if(!c&&(b=a.childNodes[b])&&1==b.nodeType&&!z(b))this.Ob=p}this.Fc=p;this.h=c;this.oa=d;this.Sd=e}},Td:function(){var a=this.oa;return"NON_SPACE"==a||"UNCOLLAPSIBLE_SPACE"==a},Lc:function(){this.Fc||this.Ec();if(this.Pb){var a=this.F.ga(this.a.childNodes[this.offset-1]).fc();a&&(this.Ja=p,this.h=a,this.oa="COLLAPSIBLE_SPACE");this.Pb=E}if(this.Ob){if(a=this.F.ga(this.a.childNodes[this.offset]).Dd())this.qc=p,this.h=a,this.oa="COLLAPSIBLE_SPACE";
this.Ob=E}},Ed:function(a){for(var b=this,c;b=b.U();)if(c=b.ac(a),""!==c)return b;return v},ac:function(a){function b(){g||(f=h.Ed(a),g=p);return f}this.Lc();if(this.Sd)return this.h;var c=["character",a.qb,a.ob,a.pb].join("_"),d=this.za.get(c);if(d!==v)return d;var d="",e,f,g=E,h=this;if("COLLAPSIBLE_SPACE"==this.oa){if(!(" "==this.h&&(!b()||f.Ja||"\n"==f.h)))if("\n"==this.h&&this.qc)b()&&"\n"!=f.h&&(d="\n");else if(e=this.xc())if(e.nc?this.type="TRAILING_SPACE_BEFORE_BR":e.Ja&&"\n"==e.h&&(this.type=
"TRAILING_SPACE_IN_BLOCK"),"\n"===e.h){if("TRAILING_SPACE_BEFORE_BR"!=this.type||a.qb)"TRAILING_SPACE_IN_BLOCK"==this.type&&e.Ja&&!a.ob||"PRE_LINE_TRAILING_SPACE_BEFORE_LINE_BREAK"==this.type&&"NON_SPACE"==e.type&&!a.pb||("\n"===this.h?e.Ja||(d="\n"):" "===this.h&&(d=" "))}else d=this.h}else"\n"===this.h&&(e=this.xc());this.za.set(c,d);return d},W:function(a){return!!a&&this.a===a.a&&this.offset===a.offset},w:function(){return"[Position("+K.ia(this.a)+":"+this.offset+")]"},toString:function(){return this.h}};
c.prototype=C;S(C,{next:e("nextPos",function(a){var b=a.sa,c=a.a,d=a.offset;a=b.F;if(!c)return v;d==b.ib()?b=(c=c.parentNode)?b.k()+1:0:b.N()?b=d+1:(b=c.childNodes[d],a.ga(b).Ub()?(c=b,b=0):b=d+1);return c?a.D(c,b):v}),Gc:e("previous",function(a){var b=a.sa,c=a.a,d=a.offset;a=b.F;0==d?b=(c=c.parentNode)?b.k():0:b.N()?b=d-1:(b=c.childNodes[d-1],a.ga(b).Ub()?(c=b,b=K.Ea(b)):b=d-1);return c?a.D(c,b):v}),Ka:e("nextVisible",function(a){var b=a.next();if(!b)return v;a=b.sa;var c=b.a;a.isCollapsed()&&(b=
a.F.D(c.parentNode,a.k()+1));return b}),xc:e("nextUncollapsed",function(a){for(;a=a.Ka();)if(a.Lc(),""!==a.h)return a;return v}),U:e("previousVisible",function(a){var b=a.Gc();if(!b)return v;a=b.sa;var c=b.a;a.isCollapsed()&&(b=a.F.D(c.parentNode,a.k()));return b})});var ha=v,ma=function(){function a(b){var c=new h;return{get:function(a){var d=c.get(a[b]);if(d)for(var e=0,f;f=d[e++];)if(f.a===a)return f;return v},set:function(a){var d=a.a[b];(c.get(d)||c.set(d,[])).push(a)}}}function b(){this.Nd()}
var c=Y.Ha(document.documentElement,"uniqueID");b.prototype={Nd:function(){this.Xb=c?function(){var a=new h;return{get:function(b){return a.get(b.uniqueID)},set:function(b){a.set(b.a.uniqueID,b)}}}():a("tagName");this.Pc=a("data");this.Ac=a("nodeName")},ga:function(a){var b;switch(a.nodeType){case 1:b=this.Xb;break;case 3:b=this.Pc;break;default:b=this.Ac}var c=b.get(a);c||(c=new d(a,this),b.set(c));return c},D:function(a,b){return this.ga(a).D(b)},I:function(a,b){var c=b?"start":"end";return this.D(a[c+
"Container"],a[c+"Offset"])},detach:function(){this.Xb=this.Pc=this.Ac=v}};return b}();S(K,{Mf:s,Qf:y});var oa=Array.prototype.indexOf?function(a,b){return a.indexOf(b)}:function(a,b){for(var c=0,d=a.length;c<d;++c)if(a[c]===b)return c;return-1};S(b.Hc,{moveStart:H(p,E),moveEnd:H(E,E),move:H(p,p),va:w(p),ua:w(E),trim:G(function(a,b){var c=this.va(b),d=this.ua(b);return c||d}),expand:G(function(a,b,c){var d=E;c=g(c,ja);var e=g(c.v,D);b||(b=R);if(b==V){var f=k(c.K);b=a.I(this,p);a=a.I(this,E);var h=
B(b,e,f).vb(),l=h.R[0].U(),f=this.collapsed?h:B(a,e,f).wb(),f=f.R[f.R.length-1];l.W(b)||(this.setStart(l.a,l.offset),d=p);f&&!f.W(a)&&(this.setEnd(f.a,f.offset),d=p);c.trim&&(c.va&&(d=this.va(e)||d),c.ua&&(d=this.ua(e)||d));return d}return this.moveEnd(R,1,c)}),text:G(function(a,b){var c;if(this.collapsed)c="";else{var d=g(b,D);c=[];for(var d=L(a,this,d),e;e=d.next();)c.push(e);d.H();c=c.join("")}return c}),La:G(function(a,b,c,d,e){a={v:e};b||(b=N(this.m()));this.selectNodeContents(b);this.collapse(p);
this.moveStart("character",c,a);this.collapse(p);this.moveEnd("character",d-c,a)}),Qc:G(function(a,b,c){b||(b=N(this.m()));a=b.parentNode;b=K.k(b);var d=-1==K.Za(this.startContainer,this.endContainer,a,b),e=this.cloneRange();d?(e.n(this.startContainer,this.startOffset,a,b),a=-e.text(c).length):(e.n(a,b,this.startContainer,this.startOffset),a=e.text(c).length);c=a+this.text(c).length;return{start:a,end:c}}),findText:G(function(a,c,d){d=g(d,Q);d.Uc&&(d.K=k(d.K),d.K.jc=E);var e=O(d.direction),f=d.Je;
f||(f=b.createRange(),f.selectNodeContents(this.m()));var h=E;"string"==typeof c?d.Mb||(c=c.toLowerCase()):h=p;var l=a.I(this,!e),n=f.comparePoint(l.a,l.offset);-1===n?l=a.I(f,p):1===n&&(l=a.I(f,E));for(var q=l,n=E;;)if(q=F(q,c,h,f,d)){if(q.valid)return this.n(q.Ab.a,q.Ab.offset,q.eb.a,q.eb.offset),p;q=e?q.Ab:q.eb}else if(d.Le&&!n)f=f.cloneRange(),q=a.I(f,!e),f.se(l.a,l.offset,e),n=p;else return E}),Pf:function(a){this.deleteContents();if(a){a=this.createContextualFragment(a);var b=a.lastChild;this.insertNode(a);
this.fd(b)}}});S(b.pe,{expand:G(function(a,b,c){this.Nb(function(a){a.expand(b,c)})}),move:G(function(a,b,c,d){a=0;if(this.focusNode){this.collapse(this.focusNode,this.focusOffset);var e=this.getRangeAt(0);d||(d={});d.v=g(d.v,Z);a=e.move(b,c,d);this.ja(e)}return a}),va:T("trimStart"),ua:T("trimEnd"),trim:T("trim"),La:G(function(a,c,d,e,f,g){a=b.createRange(c);a.La(c,d,e,g);this.ja(a,f)}),oe:G(function(a,b,c){a=this.X();for(var d=[],e=1==a.length&&this.$(),f=0,g=a.length;f<g;++f)d[f]={L:a[f].Qc(b,
c),ma:e,v:c};return d}),me:G(function(a,c,d){this.removeAllRanges();a=0;for(var e=d.length,f,g,h;a<e;++a)g=d[a],h=g.L,f=b.createRange(c),f.La(c,h.start,h.end,g.v),this.addRange(f,g.ma)}),text:G(function(a,b){for(var c=[],d=0,e=this.rangeCount;d<e;++d)c[d]=this.getRangeAt(d).text(b);return c.join("")})});b.innerText=function(a,c){var d=b.createRange(a);d.selectNodeContents(a);var e=d.text(c);d.detach();return e};b.nf=function(a,b,c){var d=ha||l();c=g(c,ca);var e=g(c.v,D),f=k(c.K);a=d.D(a,b);var h=
B(a,e,f),n=O(c.direction);return{next:function(){return n?h.wb():h.vb()},H:function(){h.H();this.next=function(){}}}};b.Zd=function(a){var b=ha||l();a(b);f()};b.Zd.hf=G;b.ca={Cf:function(a){return a&&(1==a.nodeType&&!/^(inline(-block|-table)?|none)$/.test(n(a))||9==a.nodeType||11==a.nodeType)},Ef:x,mf:G(function(a,b,c){return a.D(b,c)})}});ba.$b&&ba.$b();
