/*
 Core JS for Betterlink

 Copyright 2013, Ben Getson
 Version: 0.3
 Build date: 2 September 2013
*/
function l(a){throw a;}var p=!0,v=null,D=!1;function aa(a){return function(){return a}}var ma;
ma=window.betterlink||function(){function a(){if(!G){G=p;if(!u.initialized&&!u.initialized){var b,c;for(c in q)(b=q[c])instanceof r&&b.Z();g.ae||w()}t(z)}}function e(b,f){var H=typeof b[f];return H==c||!!(H==d&&b[f])||"unknown"==H}function h(b,c){return!!(typeof b[c]==d&&b[c])}function k(c,d){return typeof c[d]!=b}function n(b){return function(c,d){for(var A=d.length;A--;)if(!b(c,d[A]))return D;return p}}function r(b,c){this.name=b;this.G=this.g=D;this.Z=c}function t(b){for(var c=0,d=b.length;c<d;++c)try{b[c](u)}catch(A){s("Betterlink listener threw an exception. Continuing. Detail: "+
(A.message||A.description||String(A)))}}function w(){u.initialized||(u.initialized=p,t(K))}function s(b){h(window,"console")&&e(window.console,"log")&&window.console.log(b)}function x(b){u.initialized=p;u.G=D;s("Betterlink is not supported on this page in your browser. Reason: "+b)}function y(b){s("Betterlink warning: "+b)}var u={version:"0.3",initialized:D},g={ae:p};u.config={};g.b={};var d="object",c="function",b="undefined";g.qa=e;g.qb=h;g.Ga=k;g.da=n(e);g.cd=n(h);g.Qa=n(k);var q={};g.uc=q;r.prototype=
{r:function(b){this.g=p;this.G=D;l(Error("Module '"+this.name+"' failed to load: "+b))},warn:function(b){u.warn("Module "+this.name+": "+b)},Ba:function(b,c){u.warn("DEPRECATED: "+b+" in module "+this.name+"is deprecated. Please use "+c+" instead")},k:function(b){return Error("Error in "+this.name+" module: "+b)}};u.h=function(b,c){if(!q[b]){var d=new r(b,function(){if(!d.g){d.g=p;try{c(u,g,d),d.G=p}catch(A){g.jd("Module '"+b+"' failed to load: "+(A.message||A.description||String(A)))}}});q[b]=d}};
u.q=function(b){for(var c=0,d=b.length,A,f;c<d;++c)f=b[c],A=q[f],(!A||!(A instanceof r))&&l(Error("required module '"+f+"' not found")),A.Z(),A.G||l(Error("required module '"+f+"' not supported"))};var f;e(document,"addEventListener")?f=function(b,c,d){b.addEventListener(c,d,D)}:e(document,"attachEvent")?f=function(b,c,d){b.attachEvent("on"+c,d)}:x("Document does not have required addEventListener or attachEvent method");g.addListener=f;var z=[];g.Xc=function(b){G?b(u):z.push(b)};var G=D;if(typeof window==
b)x("No window found");else if(typeof document==b)x("No document found");else{e(document,"addEventListener")&&document.addEventListener("DOMContentLoaded",a,D);f(window,"load",a);u.init=w;var K=[];g.Oa=function(b){u.initialized?b(u):K.push(b)};g.jd=s;g.r=x;g.warn=y;!u.initialized&&"complete"===document.readyState&&(u.Yb=a);return u}}();window.betterlink=ma;ma.h("HTTP",function(a,e){function h(c,b,q){if(s)u.push(arguments);else{var f=d.Ie;d.test&&(b.test=1);f&&(b.verbose=1);q&&!w?(b.callback=q,c+=".js"):c+=".json";b._=(new Date).getTime().toString();c+="?"+e.b.s.dd(b);if(w){var a=new XMLHttpRequest;a.open("GET",c,p);a.withCredentials=p;a.onreadystatechange=function(){if(4===a.readyState)if(201===a.status||200===a.status||204===a.status)q&&q(D,a.responseText);else{var b="Bad HTTP status: "+a.status+" "+a.statusText;q&&(f?q({status:p,error:b}):q(p))}};
a.send(v)}else{var h=window.document.createElement("script");h.type="text/javascript";h.async=p;h.defer=p;h.src=c;var k=window.document.getElementsByTagName("script")[0];k.parentNode.insertBefore(h,k)}}}function k(c,b){if(e.b.O(c))return v;if(w)return function(d,f){c(d,f,b)};var q=""+Math.floor(1E8*Math.random()),f=d.ed+'["'+q+'"]';g[q]=function(d,f){delete g[q];201===f||200===f?c(D,d,b):c(p)};return f}function n(){e.b.forEach(u,function(c){h.call(c)});delete u}a.q(["Util","Util.HTTP","Util.DOM"]);
var r=window.navigator.userAgent,t=window.document.referrer,w=window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest,s=!w&&-1==r.indexOf("MSIE"),x=/(google web preview|baiduspider|yandexbot)/i.test(r),y=e.b.B.Id(),u=[],g=[],d={Ie:p,wa:("https:"==window.document.location.protocol?"https://":"http://")+"localhost:3000",we:"/selection_submissions/submit",Je:"/selection_views/submit",se:"/selections/%%route:id%%",Ge:"/selection_submissions/%%route:id%%/update_submission_url",test:p,ed:"betterlink._jcb"};
e.Xc(function(){s=D;n()});e.xe=function(c,b){if(!e.b.O(typeof c))if(x)e.b.O(typeof b)||b(0);else{var q=e.b.extend({},{useragent:encodeURIComponent(r),referrer:encodeURIComponent(t),href:encodeURIComponent(window.document.location.href),domain:encodeURIComponent(window.document.location.hostname)},c);y&&(q.script_source=encodeURIComponent(y));var f=e.b.s.tc(q),f=e.b.s.Cb(f),f=e.b.s.Hb(f);h(d.wa+d.we,{data:f},k(b,q))}};e.getSelection=function(c,b){if(!e.b.O(typeof c))if(x)e.b.O(typeof b)||b(0);else{var q=
{},f=e.b.s.ic(d.se,{id:c});h(d.wa+f,q,k(b,q));return q}};e.ye=function(c,b){if(!e.b.O(typeof c))if(x)e.b.O(typeof b)||b(0);else{var q=e.b.extend({},{useragent:encodeURIComponent(r),referrer:encodeURIComponent(t)},{selection_id:c});y&&(q.script_source=encodeURIComponent(y));var f=e.b.s.tc(q),f=e.b.s.Cb(f),f=e.b.s.Hb(f);h(d.wa+d.Je,{data:f},k(b,q))}};e.Fe=function(c,b){if(!e.b.O(typeof c)){b=e.b.s.Cb(encodeURIComponent(b));var q={url:b},f=e.b.s.ic(d.Ge,{id:c});h(d.wa+f,q,k(void 0,q))}};e.dg=h;a._jcb=
g});ma.h("Range Manager",function(a,e){function h(){return!e.Ic?v:e.Hc.getSelection()}e.m={};e.Oa(function(){if(!e.Ic)if(e.Ic=p,X){X.Z();e.Hc=X;X=v;var a=e.Hc;e.m.bb=a.bb;e.m.La=a.La;e.m.gb=a.gb;e.m.createRange=a.createRange;e.ab=a.ab;e.$a=a.$a}else l(Error("Range Manager not found"))});e.m.pf=function(){var a=h();return a?a.isCollapsed:p};e.m.le=function(){var a=h();a&&a.removeAllRanges()};e.m.Jd=function(){var a=h();return a?a.X():[]}});ma.h("Util",function(a,e){e.b={O:function(a){return void 0===a},sc:function(a){return"[object String]"==Object.prototype.toString.call(a)},isArray:Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)},Yd:function(a){return a===Object(a)&&!e.b.isArray(a)},forEach:function(a,e,n){if(a!==v)if(Array.prototype.forEach&&a.forEach===Array.prototype.forEach)a.forEach(e,n);else if(a.length===+a.length)for(var r=0,t=a.length;r<t;r++)e.call(n,a[r],r,a);else for(r in a)Object.prototype.hasOwnProperty.call(a,
r)&&e.call(n,a[r],r,a)},extend:function(a){e.b.forEach(Array.prototype.slice.call(arguments,1),function(k){for(var n in k)e.b.O(k[n])||(a[n]=k[n])});return a},truncate:function(a,k){var n;e.b.sc(a)?n=a.slice(0,k):e.b.isArray(a)?(n=[],e.b.forEach(a,function(a){n.push(e.b.truncate(a,k))})):e.b.Yd(a)?(n={},e.b.forEach(a,function(a,h){n[h]=e.b.truncate(a,k)})):n=a;return n},Uf:function(a){var k={};e.b.forEach(a,function(a,h){e.b.sc(a)&&0<a.length&&(k[h]=a)});return k}}});ma.h("Util.DOM",function(a,e){var h="";e.b.B={af:function(a,e){var h=a.childNodes.length;if(0===h)a.appendChild(e);else if(1===h)a.replaceChild(e,a.childNodes[0]);else{for(;a.hasChildNodes();)a.removeChild(a.lastChild);a.appendChild(e)}},gf:function(a,e,h){var t=window.document.createElement("a");t.appendChild(document.createTextNode(a));t.href=e;h&&(t.target=h);return t},Ze:function(a,h,r){a="."+a+" "+h;r&&(a=r+a);return e.b.B.Ub(a)},$e:function(a,h){return e.b.B.Ub("#"+a+" "+h)},Ub:function(a){var e=
document.head||document.getElementsByTagName("head")[0],h=document.createElement("style");h.type="text/css";h.styleSheet?h.styleSheet.cssText=a:h.appendChild(document.createTextNode(a));e.appendChild(h);return h},Id:function(){if(!h)for(var a=document.getElementsByTagName("script"),e=0,r=a.length;e<r;e++)if(-1!==a[e].src.indexOf("betterlink-no-interface-0.3.js"))return h=a[e].getAttribute("data-script_source");return""}}});ma.h("Util.HTTP",function(a,e){a.q(["Util"]);e.b.s={Gd:function(a){var e={};a=decodeURIComponent((a?a:window.location.search).substr(1)).split("&");for(var n,r=a.length,t=0;t<r;t++)n=a[t].split("="),e[n[0]]=n[1];return e},dd:function(a){var k,n,r,t=[];"undefined"===typeof k&&(k="&");e.b.forEach(a,function(a,e){n=encodeURIComponent(a.toString());r=encodeURIComponent(e);t[t.length]=r+"="+n});return t.join(k)},ic:function(a,e){return a.replace(/%%route:([^%]+)%%/g,function(a,h){return e[h]})},zc:function(a){return"object"===
typeof a?a:JSON.parse(a)},tc:function(a){function e(a){var h=/[\\\"\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,k={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};h.lastIndex=0;return h.test(a)?'"'+a.replace(h,function(a){var e=k[a];return"string"===typeof e?e:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function n(a,h){var w="",s=0,x=s="",x=0,y=w,u=[],g=h[a];g&&("object"===
typeof g&&"function"===typeof g.toJSON)&&(g=g.toJSON(a));switch(typeof g){case "string":return e(g);case "number":return isFinite(g)?String(g):"null";case "boolean":case "null":return String(g);case "object":if(!g)return"null";w+="    ";u=[];if("[object Array]"===Object.prototype.toString.apply(g)){x=g.length;for(s=0;s<x;s+=1)u[s]=n(s,g)||"null";return x=0===u.length?"[]":w?"[\n"+w+u.join(",\n"+w)+"\n"+y+"]":"["+u.join(",")+"]"}for(s in g)Object.hasOwnProperty.call(g,s)&&(x=n(s,g))&&u.push(e(s)+(w?
": ":":")+x);return x=0===u.length?"{}":w?"{\n"+w+u.join(",\n"+w)+"\n"+y+"}":"{"+u.join(",")+"}"}}return n("",{"":a})},Hb:function(a){var e,n,r,t,w=0,s=0,x="",x=[];if(!a)return a;do e=a.charCodeAt(w++),n=a.charCodeAt(w++),r=a.charCodeAt(w++),t=e<<16|n<<8|r,e=t>>18&63,n=t>>12&63,r=t>>6&63,t&=63,x[s++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(n)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(r)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(t);while(w<a.length);x=x.join("");a=a.length%3;return(a?x.slice(0,a-3):x)+"===".slice(a||3)},Cb:function(a){return unescape(encodeURIComponent(a))},pg:function(a){return decodeURIComponent(escape(a))}}});ma.h("Event Messaging",function(a,e){function h(a){var h=Array.prototype.slice.call(arguments,1);e.b.forEach(a,function(a){a.ma.apply(a.oa,h)})}a.q(["Util"]);e.e={};var k=[],n=[],r=[],t=[],w=[];e.e.eb=function(a){h(k,a)};e.e.ke=function(a){k.push({oa:this,ma:a})};e.e.yd=function(){h(n)};e.e.ie=function(a){n.push({oa:this,ma:a})};e.e.zd=function(){h(r)};e.e.je=function(a){r.push({oa:this,ma:a})};e.e.wd=function(){h(t)};e.e.ge=function(a){t.push({oa:this,ma:a})};e.e.xd=function(a){h(w,a)};e.e.he=function(a){w.push({oa:this,
ma:a})}});ma.h("Sharing",function(a,e){function h(){if(a.initialized){var h="",x=r(n());e.xe(x,function(a,u){if(a)h="There was a problem building your share link",e.e.eb({success:D,message:h});else{var g=e.b.s.zc(u);if(Object.hasOwnProperty.call(g,w)){var d=g[t],g=k(g[w]);e.e.eb({success:p,message:g});e.Fe(d,g)}else h="There was a problem building your share link",e.e.eb({success:D,message:h})}})}else e.warn("not yet initialized")}function k(e){function h(a,b){return b+e}var y=a.config.highlightQueryParam,
u=y+"="+e,g=a.config.permalink?a.config.permalink:window.location.toString(),d=RegExp("([?&]"+y+"=)[^&#!]+"),c=/#[^&#]+$/,b,y=g;a.config.preserveHash&&(b=c.exec(g));y=y.replace(c,"");d.test(y)?y=y.replace(d,h):(g=y.indexOf("?"),y=-1!==g?y+(y.substr(g).indexOf("&"===-1)?"&"+u:"?"+u):y+("?"+u));b&&(y+=b);return y}function n(){var a=e.m.Jd()[0],h=a.text(),a=e.m.La(a),y=/{.*?}/.exec(a)[0];return{serialization:a.substr(0,a.indexOf(y)),checksum:y.replace(/[{}]/g,""),text_content:h}}function r(e){a.config.permalink&&
(e.permalink=a.config.permalink);return e}a.q(["Util.HTTP","HTTP","Range Manager","Event Messaging","Highlighting"]);var t="id",w="selection_id";e.e.ie(h);a.shareSelectedText=h});ma.h("Highlighting",function(a,e){function h(a){e.o.g?(e.o.Oc={g:p,options:a},e.mb.Wc(e.$a(a.cssClass,{pa:a.elementTagName,gc:p,ba:a.tagsToPreserve,T:a.elementProperties})),k()):t()}function k(a){e.o.g?r(function(a){if(a){var h=a.xb,d=a.Bb,c=p,b;if(b=a.Ua!==e.m.gb(document.documentElement)){var q;try{q=e.m.rd(h)}catch(f){q=D}b=!(q&&q.text()===d)}if(b&&(c=D,b=e.m.createRange(),b.selectNodeContents(document.body),d=b.findText(d)?b:D))h=e.m.La(d),c=p;if(c){try{var z=e.m.bb(h);e.o.Oc&&e.mb.Md(e.o.Oc.options.cssClass,
z);e.e.zd()}catch(G){}e.m.le();n(a.re)}}},a):t()}function n(a){e.ye(a,function(){})}function r(h,n){var g=n?n:e.b.s.Gd()[a.config.highlightQueryParam];g&&e.getSelection(g,function(a,c){if(a)h(D);else{var b;b=e.b.s.zc(c);(b=Object.hasOwnProperty.call(b,w)&&Object.hasOwnProperty.call(b,s)&&Object.hasOwnProperty.call(b,x)?{xb:b[w],Ua:b[s],Bb:b[x]}:D)?h({re:g,xb:b.xb,Ua:b.Ua,Bb:b.Bb}):h(D)}})}function t(){e.warn("Highlighting not yet initialized")}a.q(["HTTP","Util.HTTP","Event Messaging","Range Manager"]);
a.config.highlightQueryParam="hl";var w="serialization",s="checksum",x="text_content";e.o={};e.Oa(function(){if(!e.o.g){e.o.g=p;e.e.he(h);var a;a=e.ab();e.mb=a;e.e.wd()}});a.highlightRequestedSelections=k;a.removeHighlightFromSelectedText=function(){e.o.g?e.mb.Ee():t()}});ma.h("Exports for Public Interface",function(a,e){a.q(["Event Messaging"]);a.registerObserverForSubmissionDisplay=e.e.ke;a.fireNewSubmission=e.e.yd;a.registerObserverForSelectionHighlighted=e.e.je;a.registerObserverForHighlighterInitialized=e.e.ge;a.fireHighlighterStylesInitialized=e.e.xd});"object"!==typeof JSON&&(JSON={});
(function(){function a(a){return 10>a?"0"+a:a}function e(a){n.lastIndex=0;return n.test(a)?'"'+a.replace(n,function(a){var e=w[a];return"string"===typeof e?e:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function h(a,n){var k,g,d,c,b=r,q,f=n[a];f&&("object"===typeof f&&"function"===typeof f.toJSON)&&(f=f.toJSON(a));"function"===typeof s&&(f=s.call(n,a,f));switch(typeof f){case "string":return e(f);case "number":return isFinite(f)?String(f):"null";case "boolean":case "null":return String(f);
case "object":if(!f)return"null";r+=t;q=[];if("[object Array]"===Object.prototype.toString.apply(f)){c=f.length;for(k=0;k<c;k+=1)q[k]=h(k,f)||"null";d=0===q.length?"[]":r?"[\n"+r+q.join(",\n"+r)+"\n"+b+"]":"["+q.join(",")+"]";r=b;return d}if(s&&"object"===typeof s){c=s.length;for(k=0;k<c;k+=1)"string"===typeof s[k]&&(g=s[k],(d=h(g,f))&&q.push(e(g)+(r?": ":":")+d))}else for(g in f)Object.prototype.hasOwnProperty.call(f,g)&&(d=h(g,f))&&q.push(e(g)+(r?": ":":")+d);d=0===q.length?"{}":r?"{\n"+r+q.join(",\n"+
r)+"\n"+b+"}":"{"+q.join(",")+"}";r=b;return d}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":v},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var k=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
n=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,r,t,w={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},s;"function"!==typeof JSON.stringify&&(JSON.stringify=function(a,e,k){var g;t=r="";if("number"===typeof k)for(g=0;g<k;g+=1)t+=" ";else"string"===typeof k&&(t=k);(s=e)&&("function"!==typeof e&&("object"!==typeof e||"number"!==typeof e.length))&&l(Error("JSON.stringify"));return h("",{"":a})});
"function"!==typeof JSON.parse&&(JSON.parse=function(a,e){function h(a,c){var b,q,f=a[c];if(f&&"object"===typeof f)for(b in f)Object.prototype.hasOwnProperty.call(f,b)&&(q=h(f,b),void 0!==q?f[b]=q:delete f[b]);return e.call(a,c,f)}var g;a=String(a);k.lastIndex=0;k.test(a)&&(a=a.replace(k,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return g=eval("("+a+")"),"function"===typeof e?h({"":g},""):g;l(new SyntaxError("JSON.parse"))})})();var X;
X=X||function(){function a(){S||(S=p,E.g||x())}function e(a,b){var c=typeof a[b];return c==g||!!(c==u&&a[b])||"unknown"==c}function h(a,b){return!!(typeof a[b]==u&&a[b])}function k(a,b){return typeof a[b]!=d}function n(a){return function(b,c){for(var d=c.length;d--;)if(!a(b,c[d]))return D;return p}}function r(a){return a&&z(a,f)&&G(a,q)}function t(a){return h(a,"body")?a.body:a.getElementsByTagName("body")[0]}function w(a){h(window,"console")&&e(window.console,"log")&&window.console.log(a)}function s(a){E.g=
p;E.G=D;a="RangeManager is not supported on this page in your browser. Reason: "+a;E.ea.Yc?window.alert(a):w(a)}function x(){if(!E.g){var a,d=D,f=D;e(document,"createRange")&&(a=document.createRange(),z(a,b)&&G(a,c)&&(d=p),a.detach());a=t(document);if(!a||"body"!=a.nodeName.toLowerCase())s("No body element found");else if(a&&e(a,"createTextRange")&&(a=a.createTextRange(),r(a)&&(f=p)),!d&&!f)s("Neither Range nor TextRange are available");else{E.g=p;E.M={ha:d,Nd:f};var A,q;for(q in K)(A=K[q])instanceof y&&
A.Z();f=0;for(A=H.length;f<A;++f)try{H[f](E)}catch(h){d="RangeManager init listener threw an exception. Continuing. Detail: "+(h.message||h.description||String(h)),w(d)}}}}function y(a,b){this.name=a;this.G=this.g=D;this.Z=b}var u="object",g="function",d="undefined",c="startContainer startOffset endContainer endOffset collapsed commonAncestorContainer".split(" "),b="setStart setStartBefore setStartAfter setEnd setEndBefore setEndAfter collapse selectNode selectNodeContents compareBoundaryPoints deleteContents extractContents cloneContents insertNode surroundContents cloneRange toString detach".split(" "),
q="boundingHeight boundingLeft boundingTop boundingWidth htmlText text".split(" "),f="collapse compareEndPoints duplicate moveToElementText parentElement select setEndPoint getBoundingClientRect".split(" "),z=n(e),G=n(k),K={},E={version:"1.3alpha.772",g:D,G:p,b:{qa:e,qb:h,Ga:k,da:z,cd:n(h),Qa:G,Lf:r,Y:t},M:{},uc:K,ea:{Yc:p,Zc:D,Bc:D}};E.r=s;E.warn=function(a){a="RangeManager warning: "+a;E.ea.Zc?window.alert(a):w(a)};({}).hasOwnProperty?E.b.extend=function(a,b,c){var d,e,f;for(f in b)b.hasOwnProperty(f)&&
(d=a[f],e=b[f],c&&(d!==v&&"object"==typeof d&&e!==v&&"object"==typeof e)&&E.b.extend(d,e,p),a[f]=e);return a}:s("hasOwnProperty not supported");(function(){var a=document.createElement("div");a.appendChild(document.createElement("span"));var b=[].slice,c;try{1==b.call(a.childNodes,0)[0].nodeType&&(c=function(a){return b.call(a,0)})}catch(d){}c||(c=function(a){for(var b=[],c=0,d=a.length;c<d;++c)b[c]=a[c];return b});E.b.ze=c})();var F;e(document,"addEventListener")?F=function(a,b,c){a.addEventListener(b,
c,D)}:e(document,"attachEvent")?F=function(a,b,c){a.attachEvent("on"+b,c)}:s("Document does not have required addEventListener or attachEvent method");E.b.addListener=F;var H=[];E.Z=x;E.Oa=function(a){E.g?a(E):H.push(a)};var A=[];E.Fb=function(a){A.push(a)};E.mf=function(a){a=a||window;x();for(var b=0,c=A.length;b<c;++b)A[b](a)};y.prototype={r:function(a){this.g=p;this.G=D;l(Error("Module '"+this.name+"' failed to load: "+a))},warn:function(a){E.warn("Module "+this.name+": "+a)},Ba:function(a,b){E.warn("DEPRECATED: "+
a+" in module "+this.name+"is deprecated. Please use "+b+" instead")},k:function(a){return Error("Error in RangeManager "+this.name+" module: "+a)}};E.h=function(a,b){var c=new y(a,function(){if(!c.g){c.g=p;try{b(E,c),c.G=p}catch(d){w("Module '"+a+"' failed to load: "+(d.message||d.description||String(d)))}}});K[a]=c};E.q=function(a){for(var b=0,c=a.length,d,e;b<c;++b)e=a[b],d=K[e],(!d||!(d instanceof y))&&l(Error("required module '"+e+"' not found")),d.Z(),d.G||l(Error("required module '"+e+"' not supported"))};
var S=D;if(typeof window==d)s("No window found");else if(typeof document==d)s("No document found");else return e(document,"addEventListener")&&document.addEventListener("DOMContentLoaded",a,D),F(window,"load",a),E}();
X.h("DomUtil",function(a,e){function h(a,b){for(var c=a.length;c--;)if(a[c]===b)return p;return D}function k(a){for(var b=0;a=a.previousSibling;)++b;return b}function n(a,b){var c=[],d;for(d=a;d;d=d.parentNode)c.push(d);for(d=b;d;d=d.parentNode)if(h(c,d))return d;return v}function r(a,b,c){for(b=c?b:b.parentNode;b;){if(b===a)return p;b=b.parentNode}return D}function t(a,b,c){for(c=c?a:a.parentNode;c;){a=c.parentNode;if(a===b)return c;c=a}return v}function w(a){a=a.nodeType;return 3==a||4==a||8==a}
function s(a,b){var c=b.nextSibling,d=b.parentNode;c?d.insertBefore(a,c):d.appendChild(a);return a}function x(a){if(9==a.nodeType)return a;if(typeof a.ownerDocument!=z)return a.ownerDocument;if(typeof a.document!=z)return a.document;if(a.parentNode)return x(a.parentNode);l(e.k("getDocument: no document found for node"))}function y(a){a=x(a);if(typeof a.defaultView!=z)return a.defaultView;if(typeof a.parentWindow!=z)return a.parentWindow;l(e.k("Cannot get a window object for node"))}function u(a){if(typeof a.contentDocument!=
z)return a.contentDocument;if(typeof a.contentWindow!=z)return a.contentWindow.document;l(e.k("getIframeDocument: No Document object found for iframe element"))}function g(a){return a&&G.qa(a,"setTimeout")&&G.qb(a,"document")}function d(a){try{return a.parentNode,D}catch(b){return p}}function c(a){return!a?"[No node]":E&&d(a)?"[Broken node]":w(a)?'"'+a.data+'"':1==a.nodeType?"<"+a.nodeName+(a.id?' id="'+a.id+'"':"")+">["+a.childNodes.length+"]["+a.innerHTML.slice(0,20)+"]":a.nodeName}function b(a){this.A=
this.root=a}function q(a,b){this.a=a;this.offset=b}function f(a){this.code=this[a];this.Xa=a;this.message="DOMException: "+this.Xa}var z="undefined",G=a.b;G.da(document,["createDocumentFragment","createElement","createTextNode"])||e.r("document missing a Node creation method");G.qa(document,"getElementsByTagName")||e.r("document missing getElementsByTagName method");var K=document.createElement("div");G.da(K,["insertBefore","appendChild","cloneNode"])||e.r("Incomplete Element implementation");G.Ga(K,
"innerHTML")||e.r("Element is missing innerHTML property");G.da(document.createTextNode("test"),["splitText","deleteData","insertData","appendData","cloneNode"])||e.r("Incomplete Text Node implementation");var E=D;(function(){var b=document.createElement("b");b.innerHTML="1";var c=b.firstChild;b.innerHTML="<br>";E=d(c);a.M.md=E})();var F;typeof window.getComputedStyle!=z?F=function(a,b){return y(a).getComputedStyle(a,v)[b]}:typeof document.documentElement.currentStyle!=z?F=function(a,b){return a.currentStyle[b]}:
e.r("No means of obtaining computed style properties found");b.prototype={u:v,next:function(){var a=this.u=this.A,b;if(this.u){b=a.firstChild;if(!b)for(b=v;a!==this.root&&!(b=a.nextSibling);)a=a.parentNode;this.A=b}return this.u},detach:function(){this.u=this.A=this.root=v}};q.prototype={W:function(a){return!!a&&this.a===a.a&&this.offset==a.offset},w:function(){return"[DomPosition("+c(this.a)+":"+this.offset+")]"},toString:function(){return this.w()}};f.prototype={};f.prototype.toString=function(){return this.message};
a.B={Ra:h,nc:function(a){var b;return typeof a.namespaceURI==z||(b=a.namespaceURI)===v||"http://www.w3.org/1999/xhtml"==b},parentElement:function(a){a=a.parentNode;return 1==a.nodeType?a:v},j:k,Da:function(a){switch(a.nodeType){case 7:case 10:return 0;case 3:case 8:return a.length;default:return a.childNodes.length}},fb:n,kc:r,sb:function(a,b){return r(a,b,p)},Ad:t,N:w,Kf:function(a){if(!a)return D;a=a.nodeType;return 3==a||8==a},Pd:s,ve:function(a,b,c){var d=a.cloneNode(D);d.deleteData(0,b);a.deleteData(b,
a.length-b);s(d,a);if(c)for(var e=0,f;f=c[e++];)f.a==a&&f.offset>b?(f.a=d,f.offset-=b):f.a==a.parentNode&&f.offset>k(a)&&++f.offset;return d},l:x,lb:y,Cd:function(a){if(typeof a.contentWindow!=z)return a.contentWindow;if(typeof a.contentDocument!=z)return a.contentDocument.defaultView;l(e.k("getIframeWindow: No Window object found for iframe element"))},uf:u,Y:G.Y,Zd:g,bc:function(a,b,c){var d;a?G.Ga(a,"nodeType")?d=1==a.nodeType&&"iframe"==a.tagName.toLowerCase()?u(a):x(a):g(a)&&(d=a.document):d=
document;d||l(b.k(c+"(): Parameter must be a Window object or DOM node"));return d},Hd:function(a){for(var b;b=a.parentNode;)a=b;return a},Ya:function(a,b,c,d){var f;if(a==c)return b===d?0:b<d?-1:1;if(f=t(c,a,p))return b<=k(f)?-1:1;if(f=t(a,c,p))return k(f)<d?-1:1;b=n(a,c);a=a===b?b:t(a,b,p);c=c===b?b:t(c,b,p);a===c&&l(e.k("comparePoints got to case 4 and childA and childB are the same!"));for(b=b.firstChild;b;){if(b===a)return-1;if(b===c)return 1;b=b.nextSibling}},Sd:d,ia:c,ac:F,Wb:function(a){for(var b=
x(a).createDocumentFragment(),c;c=a.firstChild;)b.appendChild(c);return b},od:function(a){return new b(a)},ka:q};a.Db=f});
X.h("DomRange",function(a){function e(a,b){return 3!=a.nodeType&&(Z(a,b.startContainer)||Z(a,b.endContainer))}function h(a){return a.document||ca(a.startContainer)}function k(a){return new da(a.parentNode,C(a))}function n(a){return new da(a.parentNode,C(a)+1)}function r(a,b,c){var m=11==a.nodeType?a.firstChild:a;L(b)?c==b.length?I.Pd(a,b):b.parentNode.insertBefore(a,0==c?b:ia(b,c)):c>=b.childNodes.length?b.appendChild(a):b.insertBefore(a,b.childNodes[c]);return m}function t(a,b,c){A(a);A(b);h(b)!=
h(a)&&l(new N("WRONG_DOCUMENT_ERR"));var m=P(a.startContainer,a.startOffset,b.endContainer,b.endOffset);a=P(a.endContainer,a.endOffset,b.startContainer,b.startOffset);return c?0>=m&&0<=a:0>m&&0<a}function w(a){for(var b,c,m=h(a.aa).createDocumentFragment();c=a.next();)b=a.Ha(),c=c.cloneNode(!b),b&&(b=a.Ea(),c.appendChild(w(b)),b.detach(p)),10==c.nodeType&&l(new N("HIERARCHY_REQUEST_ERR")),m.appendChild(c);return m}function s(a,b,c){var m,d;for(c=c||{stop:D};m=a.next();)if(a.Ha())if(b(m)===D){c.stop=
p;break}else{if(m=a.Ea(),s(m,b,c),m.detach(p),c.stop)break}else for(m=I.od(m);d=m.next();)if(b(d)===D){c.stop=p;return}}function x(a){for(var b;a.next();)a.Ha()?(b=a.Ea(),x(b),b.detach(p)):a.remove()}function y(a){for(var b,c=h(a.aa).createDocumentFragment(),m;b=a.next();)a.Ha()?(b=b.cloneNode(D),m=a.Ea(),b.appendChild(y(m)),m.detach(p)):a.remove(),10==b.nodeType&&l(new N("HIERARCHY_REQUEST_ERR")),c.appendChild(b);return c}function u(a,b,c){var m=!(!b||!b.length),B,e=!!c;m&&(B=RegExp("^("+b.join("|")+
")$"));var f=[];s(new d(a,D),function(a){(!m||B.test(a.nodeType))&&(!e||c(a))&&f.push(a)});return f}function g(a){return"["+("undefined"==typeof a.getName?"Range":a.getName())+"("+I.ia(a.startContainer)+":"+a.startOffset+", "+I.ia(a.endContainer)+":"+a.endOffset+")]"}function d(a,b){this.aa=a;this.Ob=b;if(!a.collapsed){this.t=a.startContainer;this.sa=a.startOffset;this.C=a.endContainer;this.fa=a.endOffset;var c=a.commonAncestorContainer;this.t===this.C&&L(this.t)?(this.rc=p,this.P=this.Q=this.A=this.t):
(this.P=this.A=this.t===c&&!L(this.t)?this.t.childNodes[this.sa]:ja(this.t,c,p),this.Q=this.C===c&&!L(this.C)?this.C.childNodes[this.fa-1]:ja(this.C,c,p))}}function c(a){this.code=this[a];this.Xa=a;this.message="RangeException: "+this.Xa}function b(a){return function(b,c){for(var m,d=c?b:b.parentNode;d;){m=d.nodeType;if($(a,m))return d;d=d.parentNode}return v}}function q(a,b){m(a,b)&&l(new c("INVALID_NODE_TYPE_ERR"))}function f(a){a.startContainer||l(new N("INVALID_STATE_ERR"))}function z(a,b){$(b,
a.nodeType)||l(new c("INVALID_NODE_TYPE_ERR"))}function G(a,b){(0>b||b>(L(a)?a.length:a.childNodes.length))&&l(new N("INDEX_SIZE_ERR"))}function K(a,b){na(a,p)!==na(b,p)&&l(new N("WRONG_DOCUMENT_ERR"))}function E(a){oa(a,p)&&l(new N("NO_MODIFICATION_ALLOWED_ERR"))}function F(a,b){a||l(new N(b))}function H(a){return ka&&I.Sd(a)||!$(ea,a.nodeType)&&!na(a,p)}function A(a){f(a);(!a.startContainer||!a.endContainer||H(a.startContainer)||H(a.endContainer)||!(a.startOffset<=(L(a.startContainer)?a.startContainer.length:
a.startContainer.childNodes.length))||!(a.endOffset<=(L(a.endContainer)?a.endContainer.length:a.endContainer.childNodes.length)))&&l(Error("Range error: Range is no longer valid after DOM mutation ("+a.w()+")"))}function S(a,b){A(a);var c=a.startContainer,m=a.startOffset,d=a.endContainer,B=a.endOffset,e=c===d;L(d)&&(0<B&&B<d.length)&&ia(d,B,b);L(c)&&(0<m&&m<c.length)&&(c=ia(c,m,b),e?(B-=m,d=c):d==c.parentNode&&B>=C(c)&&B++,m=0);a.n(c,m,d,B)}function Q(){}function U(a){a.START_TO_START=pa;a.START_TO_END=
sa;a.END_TO_END=xa;a.END_TO_START=ta;a.Re=ua;a.Qe=va;a.Se=wa;a.Te=qa}function J(a){U(a);U(a.prototype)}function Y(a,b){return function(){A(this);var c=this.startContainer,m=this.startOffset,B=this.commonAncestorContainer,e=new d(this,p);c!==B&&(c=ja(c,B,p),m=n(c),c=m.a,m=m.offset);s(e,E);e.reset();B=a(e);e.detach();b(this,c,m,c,m);return B}}function R(a,b,c){function m(a,b){return function(c){f(this);z(c,fa);z(W(c),ea);c=(a?k:n)(c);(b?B:ha)(this,c.a,c.offset)}}function B(a,c,m){var d=a.endContainer,
e=a.endOffset;if(c!==a.startContainer||m!==a.startOffset){if(W(c)!=W(d)||1==P(c,m,d,e))d=c,e=m;b(a,c,m,d,e)}}function ha(a,c,m){var d=a.startContainer,B=a.startOffset;if(c!==a.endContainer||m!==a.endOffset){if(W(c)!=W(d)||-1==P(c,m,d,B))d=c,B=m;b(a,d,B,c,m)}}a.prototype=new Q;O.extend(a.prototype,{setStart:function(a,b){f(this);q(a,p);G(a,b);B(this,a,b)},setEnd:function(a,b){f(this);q(a,p);G(a,b);ha(this,a,b)},n:function(){f(this);var a=arguments,c=a[0],m=a[1],d=c,B=m;switch(a.length){case 3:B=a[2];
break;case 4:d=a[2],B=a[3]}b(this,c,m,d,B)},te:function(a,b,c){this["set"+(c?"Start":"End")](a,b)},setStartBefore:m(p,p),setStartAfter:m(D,p),setEndBefore:m(p,D),setEndAfter:m(D,D),collapse:function(a){A(this);a?b(this,this.startContainer,this.startOffset,this.startContainer,this.startOffset):b(this,this.endContainer,this.endOffset,this.endContainer,this.endOffset)},selectNodeContents:function(a){f(this);q(a,p);b(this,a,0,a,ba(a))},selectNode:function(a){f(this);q(a,D);z(a,fa);var c=k(a);a=n(a);b(this,
c.a,c.offset,a.a,a.offset)},extractContents:Y(y,b),deleteContents:Y(x,b),Jb:function(){A(this);E(this.startContainer);E(this.endContainer);var a=new d(this,p),b=a.P&&e(a.P,this)||a.Q&&e(a.Q,this);a.detach();return!b},detach:function(){c(this)},fg:function(){S(this)},Nc:function(a){S(this,a)},Pf:function(){function a(b){var c=b.previousSibling;if(c&&c.nodeType==b.nodeType){m=b;var f=b.length;d=c.length;b.insertData(0,c.data);c.parentNode.removeChild(c);m==B?(e+=d,B=m):B==b.parentNode&&(c=C(b),e==c?
(B=b,e=f):e>c&&e--)}}function c(a){var b=a.nextSibling;b&&b.nodeType==a.nodeType&&(B=a,e=a.length,a.appendData(b.data),b.parentNode.removeChild(b))}A(this);var m=this.startContainer,d=this.startOffset,B=this.endContainer,e=this.endOffset,f=p;L(B)?B.length==e&&c(B):(0<e&&(f=B.childNodes[e-1])&&L(f)&&c(f),f=!this.collapsed);f?L(m)?0==d&&a(m):d<m.childNodes.length&&(f=m.childNodes[d])&&L(f)&&a(f):(m=B,d=e);b(this,m,d,B,e)},Pb:function(a,b){f(this);q(a,p);G(a,b);this.n(a,b)}});J(a)}function M(a){a.collapsed=
a.startContainer===a.endContainer&&a.startOffset===a.endOffset;a.commonAncestorContainer=a.collapsed?a.startContainer:I.fb(a.startContainer,a.endContainer)}function V(a,b,c,m,d){a.startContainer=b;a.startOffset=c;a.endContainer=m;a.endOffset=d;a.document=I.l(b);M(a)}function T(a){this.startContainer=a;this.startOffset=0;this.endContainer=a;this.endOffset=0;this.document=a;M(this)}a.q(["DomUtil"]);var I=a.B,O=a.b,da=I.ka,N=a.Db,L=I.N,C=I.j,Z=I.sb,ca=I.l,P=I.Ya,ia=I.ve,ja=I.Ad,ba=I.Da,$=I.Ra,W=I.Hd,
ka=a.M.md;d.prototype={u:v,A:v,P:v,Q:v,rc:D,reset:function(){this.u=v;this.A=this.P},next:function(){var a=this.u=this.A;a&&(this.A=a!==this.Q?a.nextSibling:v,L(a)&&this.Ob&&(a===this.C&&(a=a.cloneNode(p)).deleteData(this.fa,a.length-this.fa),this.u===this.t&&(a=a.cloneNode(p)).deleteData(0,this.sa)));return a},remove:function(){var a=this.u,b,c;L(a)&&(a===this.t||a===this.C)?(b=a===this.t?this.sa:0,c=a===this.C?this.fa:a.length,b!=c&&a.deleteData(b,c-b)):a.parentNode&&a.parentNode.removeChild(a)},
Ha:function(){return e(this.u,this.aa)},Ea:function(){var a;if(this.rc)a=this.aa.cloneRange(),a.collapse(D);else{a=new T(h(this.aa));var b=this.u,c=b,m=0,B=b,e=ba(b);Z(b,this.t)&&(c=this.t,m=this.sa);Z(b,this.C)&&(B=this.C,e=this.fa);V(a,c,m,B,e)}return new d(a,this.Ob)},detach:function(a){a&&this.aa.detach();this.aa=this.u=this.A=this.P=this.Q=this.t=this.sa=this.C=this.fa=v}};c.prototype={};c.prototype.toString=function(){return this.message};var fa=[1,3,4,5,7,8,10],ea=[2,9,11],B=[1,3,4,5,7,8,10,
11],ga=[1,3,4,5,7,8],na=b([9,11]),oa=b([5,6,10,12]),m=b([6,10,12]),ha=document.createElement("style"),la=D;try{ha.innerHTML="<b>x</b>",la=3==ha.firstChild.nodeType}catch(ya){}a.M.yf=la;var ra="startContainer startOffset endContainer endOffset collapsed commonAncestorContainer".split(" "),pa=0,sa=1,xa=2,ta=3,ua=0,va=1,wa=2,qa=3;Q.prototype={compareBoundaryPoints:function(a,b){A(this);K(this.startContainer,b.startContainer);var c=a==ta||a==pa?"start":"end",m=a==sa||a==pa?"start":"end";return P(this[c+
"Container"],this[c+"Offset"],b[m+"Container"],b[m+"Offset"])},insertNode:function(a){A(this);z(a,B);E(this.startContainer);Z(a,this.startContainer)&&l(new N("HIERARCHY_REQUEST_ERR"));a=r(a,this.startContainer,this.startOffset);this.setStartBefore(a)},cloneContents:function(){A(this);var a,b;if(this.collapsed)return h(this).createDocumentFragment();if(this.startContainer===this.endContainer&&L(this.startContainer))return a=this.startContainer.cloneNode(p),a.data=a.data.slice(this.startOffset,this.endOffset),
b=h(this).createDocumentFragment(),b.appendChild(a),b;b=new d(this,p);a=w(b);b.detach();return a},Jb:function(){A(this);E(this.startContainer);E(this.endContainer);var a=new d(this,p),b=a.P&&e(a.P,this)||a.Q&&e(a.Q,this);a.detach();return!b},surroundContents:function(a){z(a,ga);this.Jb()||l(new c("BAD_BOUNDARYPOINTS_ERR"));var b=this.extractContents();if(a.hasChildNodes())for(;a.lastChild;)a.removeChild(a.lastChild);r(a,this.startContainer,this.startOffset);a.appendChild(b);this.selectNode(a)},cloneRange:function(){A(this);
for(var a=new T(h(this)),b=ra.length,c;b--;)c=ra[b],a[c]=this[c];return a},toString:function(){A(this);var a=this.startContainer;if(a===this.endContainer&&L(a))return 3==a.nodeType||4==a.nodeType?a.data.slice(this.startOffset,this.endOffset):"";var b=[],a=new d(this,p);s(a,function(a){(3==a.nodeType||4==a.nodeType)&&b.push(a.data)});a.detach();return b.join("")},compareNode:function(a){A(this);var b=a.parentNode,c=C(a);b||l(new N("NOT_FOUND_ERR"));a=this.comparePoint(b,c);b=this.comparePoint(b,c+
1);return 0>a?0<b?wa:ua:0<b?va:qa},comparePoint:function(a,b){A(this);F(a,"HIERARCHY_REQUEST_ERR");K(a,this.startContainer);return 0>P(a,b,this.startContainer,this.startOffset)?-1:0<P(a,b,this.endContainer,this.endOffset)?1:0},createContextualFragment:la?function(a){var b=this.startContainer,c=ca(b);b||l(new N("INVALID_STATE_ERR"));var m=v;1==b.nodeType?m=b:L(b)&&(m=I.parentElement(b));m=m===v||"HTML"==m.nodeName&&I.nc(ca(m).documentElement)&&I.nc(m)?c.createElement("body"):m.cloneNode(D);m.innerHTML=
a;return I.Wb(m)}:function(a){f(this);var b=h(this).createElement("body");b.innerHTML=a;return I.Wb(b)},Ae:function(){A(this);var a=this.commonAncestorContainer.parentNode.cloneNode(D);a.appendChild(this.cloneContents());return a.innerHTML},intersectsNode:function(a,b){A(this);F(a,"NOT_FOUND_ERR");if(ca(a)!==h(this))return D;var c=a.parentNode,m=C(a);F(c,"NOT_FOUND_ERR");var d=P(c,m,this.endContainer,this.endOffset),c=P(c,m+1,this.startContainer,this.startOffset);return b?0>=d&&0<=c:0>d&&0<c},isPointInRange:function(a,
b){A(this);F(a,"HIERARCHY_REQUEST_ERR");K(a,this.startContainer);return 0<=P(a,b,this.startContainer,this.startOffset)&&0>=P(a,b,this.endContainer,this.endOffset)},jc:function(a){return t(this,a,D)},Rd:function(a){return t(this,a,p)},Fa:function(a){if(this.jc(a)){var b=P(this.startContainer,this.startOffset,a.startContainer,a.startOffset),c=P(this.endContainer,this.endOffset,a.endContainer,a.endOffset),m=this.cloneRange();-1==b&&m.setStart(a.startContainer,a.startOffset);1==c&&m.setEnd(a.endContainer,
a.endOffset);return m}return v},Tc:function(a){if(this.Rd(a)){var b=this.cloneRange();-1==P(a.startContainer,a.startOffset,this.startContainer,this.startOffset)&&b.setStart(a.startContainer,a.startOffset);1==P(a.endContainer,a.endOffset,this.endContainer,this.endOffset)&&b.setEnd(a.endContainer,a.endOffset);return b}l(new c("Ranges do not intersect"))},containsNode:function(a,b){return b?this.intersectsNode(a,D):this.compareNode(a)==qa},ib:function(a,b){A(this);return u(this,a,b)},l:function(){return h(this)},
gd:function(a){f(this);this.setStartAfter(a);this.collapse(p)},getBookmark:function(b){var c=h(this),m=a.createRange(c);b=b||I.Y(c);m.selectNodeContents(b);var c=this.Fa(m),d=0,B=0;c&&(m.setEnd(c.startContainer,c.startOffset),d=m.toString().length,B=d+c.toString().length,m.detach());return{start:d,end:B,Rb:b}},moveToBookmark:function(a){var b=a.Rb,c=0;this.setStart(b,0);this.collapse(p);for(var b=[b],m,d=D,B=D,e,f;!B&&(m=b.pop());)if(3==m.nodeType)e=c+m.length,!d&&(a.start>=c&&a.start<=e)&&(this.setStart(m,
a.start-c),d=p),d&&(a.end>=c&&a.end<=e)&&(this.setEnd(m,a.end-c),B=p),c=e;else{f=m.childNodes;for(e=f.length;e--;)b.push(f[e])}},getName:aa("DomRange"),W:function(a){return T.wb(this,a)},w:function(){return g(this)}};R(T,V,function(a){f(a);a.startContainer=a.startOffset=a.endContainer=a.endOffset=a.document=v;a.collapsed=a.commonAncestorContainer=v});a.Fc=Q.prototype;O.extend(T,{ee:ra,Ve:d,ld:J,pd:R,w:g,kb:h,wb:function(a,b){return a.startContainer===b.startContainer&&a.startOffset===b.startOffset&&
a.endContainer===b.endContainer&&a.endOffset===b.endOffset}});a.Na=T;a.Ue=c});
X.h("WrappedRange",function(a,e){a.q(["DomUtil","DomRange"]);var h,k,n=a.B,r=a.b,t=n.ka,w=a.Na,s=n.Y,x=n.bc,y=n.N;a.M.ha&&function(){function c(a){for(var b=d.length,c;b--;)c=d[b],a[c]=a.c[c];a.collapsed=a.startContainer===a.endContainer&&a.startOffset===a.endOffset}var b,d=w.ee,f;h=function(a){a||l(e.k("WrappedRange: Range must be specified"));this.c=a;c(this)};w.pd(h,function(a,b,c,d,e){var f=a.endContainer!==d||a.endOffset!=e,q=!a.W(a.c);if(a.startContainer!==b||a.startOffset!=c||f||q)a.setEnd(d,
e),a.setStart(b,c)},function(a){a.c.detach();a.sd=p;for(var b=d.length;b--;)a[d[b]]=v});b=h.prototype;b.selectNode=function(a){this.c.selectNode(a);c(this)};b.cloneContents=function(){return this.c.cloneContents()};b.surroundContents=function(a){this.c.surroundContents(a);c(this)};b.collapse=function(a){this.c.collapse(a);c(this)};b.cloneRange=function(){return new h(this.c.cloneRange())};b.refresh=function(){c(this)};b.toString=function(){return this.c.toString()};var z=document.createTextNode("test");
s(document).appendChild(z);var g=document.createRange();g.setStart(z,0);g.setEnd(z,0);try{g.setStart(z,1),b.setStart=function(a,b){this.c.setStart(a,b);c(this)},b.setEnd=function(a,b){this.c.setEnd(a,b);c(this)},f=function(a){return function(b){this.c[a](b);c(this)}}}catch(k){b.setStart=function(a,b){try{this.c.setStart(a,b)}catch(d){this.c.setEnd(a,b),this.c.setStart(a,b)}c(this)},b.setEnd=function(a,b){try{this.c.setEnd(a,b)}catch(d){this.c.setStart(a,b),this.c.setEnd(a,b)}c(this)},f=function(a,
b){return function(d){try{this.c[a](d)}catch(e){this.c[b](d),this.c[a](d)}c(this)}}}b.setStartBefore=f("setStartBefore","setEndBefore");b.setStartAfter=f("setStartAfter","setEndAfter");b.setEndBefore=f("setEndBefore","setStartBefore");b.setEndAfter=f("setEndAfter","setStartAfter");g.selectNodeContents(z);b.selectNodeContents=g.startContainer==z&&g.endContainer==z&&0==g.startOffset&&g.endOffset==z.length?function(a){this.c.selectNodeContents(a);c(this)}:function(a){this.n(a,0,n.Da(a))};g.selectNodeContents(z);
g.setEnd(z,3);f=document.createRange();f.selectNodeContents(z);f.setEnd(z,4);f.setStart(z,2);-1==g.compareBoundaryPoints(g.START_TO_END,f)&&1==g.compareBoundaryPoints(g.END_TO_START,f)?b.compareBoundaryPoints=function(a,b){b=b.c||b;a==b.START_TO_END?a=b.END_TO_START:a==b.END_TO_START&&(a=b.START_TO_END);return this.c.compareBoundaryPoints(a,b)}:b.compareBoundaryPoints=function(a,b){return this.c.compareBoundaryPoints(a,b.c||b)};var t=document.createElement("div");t.innerHTML="123";var u=t.firstChild,
y=s(document);y.appendChild(t);g.setStart(u,1);g.setEnd(u,2);g.deleteContents();"13"==u.data&&(b.deleteContents=function(){this.c.deleteContents();c(this)},b.extractContents=function(){var a=this.c.extractContents();c(this);return a});y.removeChild(t);y=v;r.qa(g,"createContextualFragment")&&(b.createContextualFragment=function(a){return this.c.createContextualFragment(a)});s(document).removeChild(z);g.detach();f.detach();b.getName=aa("WrappedRange");a.va=h;a.Aa=function(a){a=x(a,e,"createNativeRange");
return a.createRange()}}();if(a.M.Nd){var u=function(a,b,d,e,h){var g=a.duplicate();g.collapse(d);var k=g.parentElement();n.sb(b,k)||(k=b);if(!k.canHaveHTML)return k=new t(k.parentNode,n.j(k)),{xa:k,xc:{wc:k.offset,Qb:k.a}};b=n.l(k).createElement("span");b.parentNode&&b.parentNode.removeChild(b);var r,s=d?"StartToStart":"StartToEnd",u=h&&h.Qb==k?h.wc:0,x=k.childNodes.length,w=x;for(h=w;;){h==x?k.appendChild(b):k.insertBefore(b,k.childNodes[h]);g.moveToElementText(b);r=g.compareEndPoints(s,a);if(0==
r||u==w)break;else if(-1==r)if(w==u+1)break;else u=h;else w=w==u+1?u:h;h=Math.floor((u+w)/2);k.removeChild(b)}s=b.nextSibling;if(-1==r&&s&&y(s)){g.setEndPoint(d?"EndToStart":"EndToEnd",a);if(/[\r\n]/.test(s.data)){d=g.duplicate();e=d.text.replace(/\r\n/g,"\r").length;for(e=d.moveStart("character",e);-1==d.compareEndPoints("StartToEnd",d);)e++,d.moveStart("character",1)}else e=g.text.length;d=new t(s,e)}else a=(e||!d)&&b.previousSibling,d=(d=(e||d)&&b.nextSibling)&&y(d)?new t(d,0):a&&y(a)?new t(a,
a.data.length):new t(k,n.j(b));b.parentNode.removeChild(b);return{xa:d,xc:{wc:h,Qb:k}}},g=function(a,b){var d,e,h=a.offset,g=n.l(a.a),k=s(g).createTextRange(),r=y(a.a);r?(d=a.a,e=d.parentNode):(d=a.a.childNodes,d=h<d.length?d[h]:v,e=a.a);g=g.createElement("span");g.innerHTML="&#feff;";d?e.insertBefore(g,d):e.appendChild(g);k.moveToElementText(g);k.collapse(!b);e.removeChild(g);if(r)k[b?"moveStart":"moveEnd"]("character",h);return k};k=function(a){this.ca=a;this.refresh()};k.prototype=new w(document);
k.prototype.refresh=function(){var a,b,d;d=this.ca;a=d.parentElement();var e=d.duplicate();e.collapse(p);b=e.parentElement();e=d.duplicate();e.collapse(D);d=e.parentElement();b=b==d?b:n.fb(b,d);d=b==a?b:n.fb(a,b);0==this.ca.compareEndPoints("StartToEnd",this.ca)?b=a=u(this.ca,d,p,p).xa:(b=u(this.ca,d,p,D),a=b.xa,b=u(this.ca,d,D,D,b.xc).xa);this.setStart(a.a,a.offset);this.setEnd(b.a,b.offset)};k.prototype.getName=aa("WrappedTextRange");w.ld(k);k.fe=function(a){if(a.collapsed)return g(new t(a.startContainer,
a.startOffset),p);var b=g(new t(a.startContainer,a.startOffset),p),d=g(new t(a.endContainer,a.endOffset),D);a=s(w.kb(a)).createTextRange();a.setEndPoint("StartToStart",b);a.setEndPoint("EndToEnd",d);return a};a.Xe=k;if(!a.M.ha||a.ea.Bc){var d=function(){return this}();"undefined"==typeof d.Eb&&(d.Eb=k);a.Aa=function(a){a=x(a,e,"createNativeRange");return s(a).createTextRange()};a.va=k}}a.createRange=function(c){c=x(c,e,"createRange");return new a.va(a.Aa(c))};a.qd=function(a){a=x(a,e,"createRangeManagerRange");
return new w(a)};a.kf=function(c){e.Ba("createIframeRange()","createRange(iframeEl)");return a.createRange(c)};a.lf=function(c){e.Ba("createIframeRangeManagerRange()","createRangeManagerRange(iframeEl)");return a.qd(c)};a.Fb(function(c){var b=c.document;"undefined"==typeof b.createRange&&(b.createRange=function(){return a.createRange(b)});b=c=v})});
X.h("WrappedSelection",function(a,e){function h(b,c){var d=b.X();b.removeAllRanges();for(var e=0,m=d.length;e<m;++e)a.wb(c,d[e])||b.addRange(d[e]);b.rangeCount||x(b)}function k(a){if(a&&a instanceof b)return a.refresh(),a;a=r(a,"getNativeSelection");var c=f(a),d=Y(a),e=da?w(a):v;c?(c.p=d,c.i=e,c.refresh()):(c=new b(d,e,a),W.push({z:a,selection:c}));return c}function n(a){return"string"==typeof a?"backward"==a:!!a}function r(a,c){if(a){if(F.Zd(a))return a;if(a instanceof b)return a.z;var d=F.bc(a,
e,c);return F.lb(d)}return window}function t(a){return r(a,"getWinSelection").getSelection()}function w(a){return r(a,"getDocSelection").document.selection}function s(a,b,c){var d=c?"end":"start";c=c?"start":"end";a.anchorNode=b[d+"Container"];a.anchorOffset=b[d+"Offset"];a.focusNode=b[c+"Container"];a.focusOffset=b[c+"Offset"]}function x(a){a.anchorNode=a.focusNode=v;a.anchorOffset=a.focusOffset=0;a.rangeCount=0;a.isCollapsed=p;a.d.length=0}function y(b){var c;b instanceof S?(c=a.Aa(b.l()),c.setEnd(b.endContainer,
b.endOffset),c.setStart(b.startContainer,b.startOffset)):b instanceof Q?c=b.c:M.ha&&b instanceof F.lb(b.startContainer).Eb&&(c=b);return c}function u(a){var b=a.ib(),c;a:if(!b.length||1!=b[0].nodeType)c=D;else{c=1;for(var d=b.length;c<d;++c)if(!F.kc(b[0],b[c])){c=D;break a}c=p}c||l(e.k("getSingleElementFromRange: range "+a.w()+" did not consist of a single element"));return b[0]}function g(a,b){var c=new Q(b);a.d=[c];s(a,c,D);a.rangeCount=1;a.isCollapsed=c.collapsed}function d(b){b.d.length=0;if("None"==
b.i.type)x(b);else{var c=b.i.createRange();if(c&&"undefined"!=typeof c.text)g(b,c);else{b.rangeCount=c.length;for(var d,e=V(c.item(0)),m=0;m<b.rangeCount;++m)d=a.createRange(e),d.selectNode(c.item(m)),b.d.push(d);b.isCollapsed=1==b.rangeCount&&b.d[0].collapsed;s(b,b.d[b.rangeCount-1],D)}}}function c(a,b){for(var c=a.i.createRange(),f=u(b),m=V(c.item(0)),m=T(m).createControlRange(),ha=0,la=c.length;ha<la;++ha)m.add(c.item(ha));try{m.add(f)}catch(O){l(e.k("addRange(): Element within the specified Range could not be added to control selection (does it have layout?)"))}m.select();
d(a)}function b(a,b,c){this.p=a;this.i=b;this.d=[];this.z=c;this.refresh()}function q(a){a.z=a.anchorNode=a.focusNode=a.d=v;a.rangeCount=a.anchorOffset=a.focusOffset=0;a.sd=p}function f(a,b){for(var c=W.length,d,m;c--;)if(d=W[c],m=d.selection,"deleteAll"==b)q(m);else if(d.z==a)return"delete"==b?(W.splice(c,1),p):m;"deleteAll"==b&&(W.length=0);return v}function z(a,b){for(var c=V(b[0].startContainer),c=T(c).createControlRange(),f=0,m;f<b.length;++f){m=u(b[f]);try{c.add(m)}catch(ha){l(e.k("setRanges(): Element within the one of the specified Ranges could not be added to control selection (does it have layout?)"))}}c.select();
d(a)}function G(a,b){a.z.document!=V(b)&&l(new U("WRONG_DOCUMENT_ERR"))}function K(b){return function(c,d){var e;this.rangeCount?(e=this.getRangeAt(0),e["set"+(b?"Start":"End")](c,d)):(e=a.createRange(this.z.document),e.n(c,d));this.ja(e,this.$())}}function E(a){var b=[],c=new J(a.anchorNode,a.anchorOffset),d=new J(a.focusNode,a.focusOffset),m="function"==typeof a.getName?a.getName():"Selection";if("undefined"!=typeof a.rangeCount)for(var e=0,f=a.rangeCount;e<f;++e)b[e]=S.w(a.getRangeAt(e));return"["+
m+"(Ranges: "+b.join(", ")+")(anchor: "+c.w()+", focus: "+d.w()+"]"}a.q(["DomUtil","DomRange","WrappedRange"]);a.ea.fd=p;var F=a.B,H=a.b,A=H.qa,S=a.Na,Q=a.va,U=a.Db,J=F.ka,Y,R,M=a.M,V=F.l,T=F.Y,I=S.wb,O=A(window,"getSelection"),da=H.qb(document,"selection");M.Bf=O;var N=(M.Af=da)&&(!O||a.ea.Bc);N?(Y=w,a.qc=function(a){a=r(a,"isSelectionValid").document;var b=a.selection;return"None"!=b.type||V(b.createRange().parentElement())==a}):O?(Y=t,a.qc=aa(p)):e.r("Neither document.selection or window.getSelection() detected.");
a.wf=Y;var O=Y(),L=a.Aa(document),C=T(document),Z=H.Qa(O,["anchorNode","focusNode","anchorOffset","focusOffset"]);M.$f=Z;var ca=A(O,"extend");M.ag=ca;var P="number"==typeof O.rangeCount;M.bg=P;var ia=D,ja=p;H.da(O,["addRange","getRangeAt","removeAllRanges"])&&("number"==typeof O.rangeCount&&M.ha)&&function(){var a=window.getSelection();if(a){var b=T(document),c=b.appendChild(document.createElement("div"));c.contentEditable="false";var d=c.appendChild(document.createTextNode("\u00a0\u00a0\u00a0")),
m=document.createRange();m.setStart(d,1);m.collapse(p);a.addRange(m);ja=1==a.rangeCount;a.removeAllRanges();var e=m.cloneRange();m.setStart(d,0);e.setEnd(d,3);e.setStart(d,2);a.addRange(m);a.addRange(e);ia=2==a.rangeCount;b.removeChild(c);a.removeAllRanges();m.detach();e.detach()}}();M.cg=ia;M.ff=ja;var ba=D;C&&A(C,"createControlRange")&&(C=C.createControlRange(),H.Qa(C,["item","add"])&&(ba=p));M.zf=ba;R=Z?function(a){return a.anchorNode===a.focusNode&&a.anchorOffset===a.focusOffset}:function(a){return a.rangeCount?
a.getRangeAt(a.rangeCount-1).collapsed:D};var $;A(O,"getRangeAt")?$=function(a,b){try{return a.getRangeAt(b)}catch(c){return v}}:Z&&($=function(b){var c=V(b.anchorNode),c=a.createRange(c);c.n(b.anchorNode,b.anchorOffset,b.focusNode,b.focusOffset);c.collapsed!==this.isCollapsed&&c.n(b.focusNode,b.focusOffset,b.anchorNode,b.anchorOffset);return c});var W=[];a.getSelection=k;a.vf=function(b){e.Ba("getIframeSelection()","getSelection(iframeEl)");return a.getSelection(F.Cd(b))};C=b.prototype;if(!N&&Z&&
H.da(O,["removeAllRanges","addRange"])){C.removeAllRanges=function(){this.p.removeAllRanges();x(this)};var ka=function(b,c){var d=S.kb(c),d=a.createRange(d);d.Pb(c.endContainer,c.endOffset);b.p.addRange(y(d));b.p.extend(c.startContainer,c.startOffset);b.refresh()};C.addRange=P?function(b,d){if(ba&&da&&"Control"==this.i.type)c(this,b);else if(n(d)&&ca)ka(this,b);else{var e;ia?e=this.rangeCount:(this.removeAllRanges(),e=0);this.p.addRange(y(b).cloneRange());this.rangeCount=this.p.rangeCount;this.rangeCount==
e+1?(a.ea.fd&&(e=$(this.p,this.rangeCount-1))&&!I(e,b)&&(b=new Q(e)),this.d[this.rangeCount-1]=b,s(this,b,ea(this.p)),this.isCollapsed=R(this)):this.refresh()}}:function(a,b){n(b)&&ca?ka(this,a):(this.p.addRange(y(a)),this.refresh())};C.Ma=function(a){if(ba&&1<a.length)z(this,a);else{this.removeAllRanges();for(var b=0,c=a.length;b<c;++b)this.addRange(a[b])}}}else if(A(O,"empty")&&A(L,"select")&&ba&&N)C.removeAllRanges=function(){try{if(this.i.empty(),"None"!=this.i.type){var a;if(this.anchorNode)a=
V(this.anchorNode);else if("Control"==this.i.type){var b=this.i.createRange();b.length&&(a=V(b.item(0)))}a&&(T(a).createTextRange().select(),this.i.empty())}}catch(c){}x(this)},C.addRange=function(a){"Control"==this.i.type?c(this,a):(Q.fe(a).select(),this.d[0]=a,this.rangeCount=1,this.isCollapsed=this.d[0].collapsed,s(this,a,D))},C.Ma=function(a){this.removeAllRanges();var b=a.length;1<b?z(this,a):b&&this.addRange(a[0])};else return e.r("No means of selecting a Range or TextRange was found"),D;C.getRangeAt=
function(a){(0>a||a>=this.rangeCount)&&l(new U("INDEX_SIZE_ERR"));return this.d[a].cloneRange()};var fa;if(N)fa=function(b){var c;a.qc(b.z)?c=b.i.createRange():(c=T(b.z.document).createTextRange(),c.collapse(p));"Control"==b.i.type?d(b):c&&"undefined"!=typeof c.text?g(b,c):x(b)};else if(A(O,"getRangeAt")&&"number"==typeof O.rangeCount)fa=function(b){if(ba&&da&&"Control"==b.i.type)d(b);else if(b.d.length=b.rangeCount=b.p.rangeCount,b.rangeCount){for(var c=0,e=b.rangeCount;c<e;++c)b.d[c]=new a.va(b.p.getRangeAt(c));
s(b,b.d[b.rangeCount-1],ea(b.p));b.isCollapsed=R(b)}else x(b)};else if(Z&&"boolean"==typeof O.isCollapsed&&"boolean"==typeof L.collapsed&&M.ha)fa=function(a){var b;b=a.p;b.anchorNode?(b=$(b,0),a.d=[b],a.rangeCount=1,b=a.p,a.anchorNode=b.anchorNode,a.anchorOffset=b.anchorOffset,a.focusNode=b.focusNode,a.focusOffset=b.focusOffset,a.isCollapsed=R(a)):x(a)};else return e.r("No means of obtaining a Range or TextRange from the user's selection was found"),D;C.refresh=function(a){var b=a?this.d.slice(0):
v,c=this.anchorNode,d=this.anchorOffset;fa(this);if(a){a=b.length;if(a!=this.d.length||this.anchorNode!=c||this.anchorOffset!=d)return p;for(;a--;)if(!I(b[a],this.d[a]))return p;return D}};C.removeRange=ba?function(a){if("Control"==this.i.type){var b=this.i.createRange();a=u(a);for(var c=V(b.item(0)),c=T(c).createControlRange(),e,m=D,f=0,la=b.length;f<la;++f)e=b.item(f),e!==a||m?c.add(b.item(f)):m=p;c.select();d(this)}else h(this,a)}:function(a){h(this,a)};var ea;!N&&Z&&M.ha?(ea=function(a){var b=
D;a.anchorNode&&(b=1==F.Ya(a.anchorNode,a.anchorOffset,a.focusNode,a.focusOffset));return b},C.$=function(){return ea(this)}):ea=C.$=aa(D);C.Cf=C.$;C.toString=function(){for(var a=[],b=0,c=this.rangeCount;b<c;++b)a[b]=""+this.d[b];return a.join("")};C.collapse=function(b,c){G(this,b);var d=a.createRange(b);d.Pb(b,c);this.ja(d);this.isCollapsed=p};C.collapseToStart=function(){if(this.rangeCount){var a=this.d[0];this.collapse(a.startContainer,a.startOffset)}else l(new U("INVALID_STATE_ERR"))};C.collapseToEnd=
function(){if(this.rangeCount){var a=this.d[this.rangeCount-1];this.collapse(a.endContainer,a.endOffset)}else l(new U("INVALID_STATE_ERR"))};C.selectAllChildren=function(b){G(this,b);var c=a.createRange(b);c.selectNodeContents(b);this.removeAllRanges();this.addRange(c)};C.deleteFromDocument=function(){if(ba&&da&&"Control"==this.i.type){for(var a=this.i.createRange(),b;a.length;)b=a.item(0),a.remove(b),b.parentNode.removeChild(b);this.refresh()}else if(this.rangeCount&&(a=this.X(),a.length)){this.removeAllRanges();
b=0;for(var c=a.length;b<c;++b)a[b].deleteContents();this.addRange(a[c-1])}};C.Ca=function(a,b){for(var c=0,d=this.d.length;c<d;++c)if(a(this.getRangeAt(c)))return b};C.X=function(){var a=[];this.Ca(function(b){a.push(b)});return a};C.ja=function(a,b){this.removeAllRanges();this.addRange(a,b)};C.Ib=function(a,b){var c=[];this.Ca(function(d){c.push(d[a].apply(d,b))});return c};C.setStart=K(p);C.setEnd=K(D);a.Fc.select=function(a){k(this.l()).ja(this,a)};C.Lb=function(a){var b=[],c=this.$();this.Ca(function(c){a(c);
b.push(c)});this.removeAllRanges();c&&1==b.length?this.addRange(b[0],"backward"):this.Ma(b)};C.containsNode=function(a,b){return this.Ca(function(c){return c.containsNode(a,b)},p)};C.getBookmark=function(a){return{la:this.$(),de:this.Ib("getBookmark",[a])}};C.moveToBookmark=function(b){for(var c=[],d=0,e,m;e=b.de[d++];)m=a.createRange(this.z),m.moveToBookmark(e),c.push(m);b.la?this.ja(c[0],"backward"):this.Ma(c)};C.Ae=function(){return this.Ib("toHtml").join("")};C.getName=aa("WrappedSelection");
C.w=function(){return E(this)};C.detach=function(){f(this.z,"delete");q(this)};b.rf=function(){f(v,"deleteAll")};b.w=E;b.Vd=n;a.Vc=b;a.qe=C;a.Fb(function(a){"undefined"==typeof a.getSelection&&(a.getSelection=function(){return k(a)});a=v})});X.h("CssClassApplier",function(a,e){function h(a,b){return a.className&&RegExp("(?:^|\\s)"+b+"(?:\\s|$)").test(a.className)}function k(a,b){a.className?h(a,b)||(a.className+=" "+b):a.className=b}function n(a){return a.split(/\s+/).sort().join(" ")}function r(a,b){return n(a.className)==n(b.className)}function t(a,b,c,d){-1==c&&(c=b.childNodes.length);for(var e=a.parentNode,f=H.j(a),h=0,q;q=d[h++];){var g=q.a,k=q.offset,z=g,n=k;g==b&&k>c&&n++;if(g==e&&(k==f||k==f+1))z=b,n+=c-f;g==e&&k>f+1&&n--;q.a=
z;q.offset=n}b.childNodes.length==c?b.appendChild(a):b.insertBefore(a,b.childNodes[c])}function w(a,b){for(var c=a.parentNode,d=H.j(a),e,f=[];e=a.firstChild;)t(e,c,d++,b),f.push(e);a.parentNode.removeChild(a);return f}function s(a,b){var c=a.cloneRange();c.selectNodeContents(b);var d=c.Fa(a),d=d?d.toString():"";c.detach();return""!=d}function x(a){for(var b=a.ib([3]),c=0,d;(d=b[c])&&!s(a,d);)++c;for(var e=b.length-1;(d=b[e])&&!s(a,d);)--e;return b.slice(c,e+1)}function y(a,b){if(a.attributes.length!=
b.attributes.length)return D;for(var c=0,d=a.attributes.length,e,f;c<d;++c)if(e=a.attributes[c],f=e.name,"class"!=f&&(f=b.attributes.getNamedItem(f),e.specified!=f.specified||e.specified&&e.nodeValue!==f.nodeValue))return D;return p}function u(a,b){for(var c=0,d=a.attributes.length,e;c<d;++c)if(e=a.attributes[c].name,(!b||!S(b,e))&&a.attributes[c].specified&&"class"!=e)return p;return D}function g(a,b){var c,d;for(d in b)if(b.hasOwnProperty(d))if(c=b[d],"object"==typeof c){if(!g(a[d],c))return D}else if(a[d]!==
c)return D;return p}function d(a){var b;return a&&1==a.nodeType&&((b=a.parentNode)&&9==b.nodeType&&"on"==b.designMode||J(a)&&!J(a.parentNode))}function c(a){return(J(a)||1!=a.nodeType&&J(a.parentNode))&&!d(a)}function b(a){return a&&1==a.nodeType&&!Y.test(U(a,"display"))}function q(a){if(0==a.data.length)return p;if(R.test(a.data))return D;switch(U(a.parentNode,"whiteSpace")){case "pre":case "pre-wrap":case "-moz-pre-wrap":return D;case "pre-line":if(/[\r\n]/.test(a.data))return D}return b(a.previousSibling)||
b(a.nextSibling)}function f(a){var b=[],c,d;for(c=0;d=a[c++];)b.push(new A(d.startContainer,d.startOffset),new A(d.endContainer,d.endOffset));return b}function z(a,b){for(var c=0,d,e,f,h=a.length;c<h;++c)d=a[c],e=b[2*c],f=b[2*c+1],d.n(e.a,e.offset,f.a,f.offset)}function G(a,b,c,d){var f,h;h=0==c;if(H.kc(b,a))return a;H.N(b)&&(f=H.j(b),0==c?c=f:c==b.length?c=f+1:l(e.k("splitNodeAt() should not be called with offset in the middle of a data node ("+c+" in "+b.data)),b=b.parentNode);if(H.N(b)?0==c?b.previousSibling:
c==b.length?b.nextSibling:1:0<c&&c<b.childNodes.length){f=b.cloneNode(D);h=b.parentNode;f.id&&f.removeAttribute("id");for(var q,g=0;q=b.childNodes[c];)t(q,f,g++,d);t(f,h,H.j(b)+1,d);return b==a?f:G(a,h,H.j(f),d)}return a!=b?(f=b.parentNode,b=H.j(b),h||b++,G(a,f,b,d)):a}function K(a){var b=a?"nextSibling":"previousSibling";return function(c,d){var e=c.parentNode,f=c[b];if(f){if(f&&3==f.nodeType)return f}else if(d&&(f=e[b])&&1==f.nodeType&&e.tagName==f.tagName&&r(e,f)&&y(e,f)&&"inline"==U(e,"display")&&
"inline"==U(f,"display"))return f[a?"firstChild":"lastChild"];return v}}function E(a){this.Wd=1==a.nodeType;this.J=[];(a=this.Wd?a.lastChild:a)&&(this.J[0]=a)}function F(a,b,c){this.V=a;var d,e,f=v;if("object"==typeof b&&b!==v){c=b.ba;f=b.T;for(d=0;e=T[d++];)b.hasOwnProperty(e)&&(this[e]=b[e]);d=b.normalize}else d=b;this.normalize="undefined"==typeof d?p:d;this.Sa=[];d=document.createElement(this.pa);this.T=this.Tb(f,d,p);this.ud=this.T.hasOwnProperty("className")?this.T.className:a;this.Gb=D;a=typeof c;
if("string"==a)"*"==c?this.Gb=p:this.ba=c.toLowerCase().replace(/^\s\s*/,"").replace(/\s\s*$/,"").split(/\s*,\s*/);else if("object"==a&&"number"==typeof c.length){this.ba=[];d=0;for(a=c.length;d<a;++d)"*"==c[d]?this.Gb=p:this.ba.push(c[d].toLowerCase())}else this.ba=[this.pa]}a.q(["WrappedSelection","WrappedRange"]);var H=a.B,A=H.ka,S=H.Ra,Q=function(){function a(b,c,d){return c&&d?" ":""}return function(b,c){b.className&&(b.className=b.className.replace(RegExp("(^|\\s)"+c+"(\\s|$)"),a))}}(),U=H.ac,
J;(function(){J="boolean"==typeof document.createElement("div").isContentEditable?function(a){return a&&1==a.nodeType&&a.isContentEditable}:function(a){return!a||1!=a.nodeType||"false"==a.contentEditable?D:"true"==a.contentEditable||J(a.parentNode)}})();var Y=/^inline(-block|-table)?$/i,R=/[^\r\n\t\f \u200B]/,M=K(D),V=K(p);E.prototype={td:function(a){var b=this.J,c=b[0];if(1<b.length){for(var d=[],e=0,f,h,q=0,g=b.length,k;q<g;++q){f=b[q];h=f.parentNode;if(0<q&&(h.removeChild(f),h.hasChildNodes()||
h.parentNode.removeChild(h),a))for(h=0;k=a[h++];)k.a==f&&(k.a=c,k.offset+=e);d[q]=f.data;e+=f.data.length}c.data=d.join("")}return c.data},hb:function(){for(var a=this.J.length,b=0;a--;)b+=this.J[a].length;return b},toString:function(){for(var a=[],b=0,c=this.J.length;b<c;++b)a[b]="'"+this.J[b].data+"'";return"[Merge("+a.join(",")+")]"}};var T=["elementTagName","ignoreWhiteSpace","applyToEditableOnly","useExistingElements","removeEmptyElements"],I={};F.prototype={pa:"mark",T:{},gc:p,$c:D,He:p,Kc:p,
Tb:function(a,b,c){var d,e,f={},h,q,g;for(g in a)if(a.hasOwnProperty(g))if(q=a[g],e=b[g],"className"==g)k(b,q),k(b,this.V),b[g]=n(b[g]),c&&(f[g]=b[g]);else if("style"==g){c&&(f[g]=h={});for(d in a[g])e[d]=q[d],c&&(h[d]=e[d]);this.Sa.push(g)}else b[g]=q,c&&(f[g]=b[g],q=I.hasOwnProperty(g)?I[g]:g,this.Sa.push(q));return c?f:""},ec:function(a){return 1==a.nodeType&&S(this.ba,a.tagName.toLowerCase())&&h(a,this.V)},cc:function(a){for(;a;){if(this.ec(a))return a;a=a.parentNode}return v},rb:function(a){return!this.$c||
c(a)},Xd:function(a){return this.gc&&a&&3==a.nodeType&&q(a)},Ac:function(a,b,c,d){for(var e=a[0],f=a[a.length-1],h=[],g,q=e,k=f,n=0,z=f.length,r,t,s=0,u=a.length;s<u;++s)r=a[s],(t=M(r,!d))?(g||(g=new E(t),h.push(g)),g.J.push(r),r===e&&(q=g.J[0],n=q.length),r===f&&(k=g.J[0],z=g.hb())):g=v;if(a=V(f,!d))g||(g=new E(f),h.push(g)),g.J.push(a);if(h.length){s=0;for(u=h.length;s<u;++s)h[s].td(c);b.n(q,n,k,z)}},nd:function(a){a=a.createElement(this.pa);this.Tb(this.T,a,D);k(a,this.V);return a},bd:function(a){var b=
a.parentNode;1==b.childNodes.length&&this.He&&S(this.ba,b.tagName.toLowerCase())&&g(b,this.T)?k(b,this.V):(b=this.nd(H.l(a)),a.parentNode.insertBefore(b,a),b.appendChild(a))},pc:function(a){return a.tagName.toLowerCase()==this.pa&&n(a.className)==this.ud&&g(a,this.T)&&!u(a,this.Sa)&&this.rb(a)},mc:function(a){var b=a.childNodes.length;return 1==a.nodeType&&this.pc(a)&&(0==b||1==b&&this.mc(a.firstChild))},Jc:function(a){var b=this;a=a.ib([1],function(a){return b.mc(a)});for(var c=0,d;d=a[c++];)d.parentNode.removeChild(d)},
De:function(a,b,c,d){b.containsNode(c)||(a=b.cloneRange(),a.selectNode(c),a.isPointInRange(b.endContainer,b.endOffset)&&(G(c,b.endContainer,b.endOffset,d),b.setEndAfter(c)),a.isPointInRange(b.startContainer,b.startOffset)&&(c=G(c,b.startContainer,b.startOffset,d)));this.pc(c)?w(c,d):Q(c,this.V)},ad:function(a,b){b=b||[];var c=f(b||[]);a.Nc(c);this.Kc&&this.Jc(a);var d=x(a);if(d.length){for(var e=0,g;g=d[e++];)!this.Xd(g)&&(!this.cc(g)&&this.rb(g))&&this.bd(g,c);g=d[d.length-1];a.n(d[0],0,g,g.length);
this.normalize&&this.Ac(d,a,c,D);z(b,c)}},Ce:function(a,b){b=b||[];var c=f(b);a.Nc(c);this.Kc&&this.Jc(a,c);var d=x(a),e,g,h=d[d.length-1];if(d.length){for(var q=0,k=d.length;q<k;++q)e=d[q],(g=this.cc(e))&&this.rb(e)&&this.De(e,a,g,c),a.n(d[0],0,h,h.length);this.normalize&&this.Ac(d,a,c,p);z(b,c)}},detach:function(){}};F.b={ec:h,Ye:k,Tf:Q,xf:r,Vf:w,tf:y,sf:u,gg:G,Hf:J,If:d,Gf:c};a.Oe=a.Ne=F;a.$a=a.hf=function(a,b,c){return new F(a,b,c)}});X.h("Highlighter",function(a){function e(a,c){this.type=a;this.kd=c}function h(a,c){u[a]=new e(a,c)}function k(a,c){this.start=a;this.end=c}function n(a,c,b,e,f,g){f?(this.id=f,y=Math.max(y,f+1)):this.id=y++;this.L=c;this.S=a;this.Va=b;this.za=e;this.Za=g||v;this.Pa=D}function r(a,c){this.S=a||document;this.Wa={};this.o=[];var b;var g=c||"textContent",f=u[g];f instanceof e?b=f.create():l(Error("Highlighter type '"+g+"' is not valid"));this.za=b}a.q(["CssClassApplier"]);var t=a.B,w=t.Ra,s=t.Y,x=[].forEach?
function(a,c){a.forEach(c)}:function(a,c){for(var b=0,e=a.length;b<e;++b)c(a[b])},y=1,u={};e.prototype.create=function(){var a=this.kd();a.type=this.type;return a};a.Sf=h;k.prototype={Qd:function(a){return this.start<a.end&&this.end>a.start},Tc:function(a){return new k(Math.min(this.start,a.start),Math.max(this.end,a.end))},Fa:function(a){return new k(Math.max(this.start,a.start),Math.min(this.end,a.end))},toString:function(){return"[CharacterRange("+this.start+", "+this.end+")]"}};k.Xb=function(a){return new k(a.start,
a.end)};var g={Gc:function(a,c){var b=a.getBookmark(c);return new k(b.start,b.end)},Ta:function(d,c,b){d=a.createRange(d);d.moveToBookmark({start:c.start,end:c.end,Rb:b});return d},yb:function(a,c){for(var b=a.X(),e=[],f=1==b.length&&a.$(),g=0,h=b.length;g<h;++g)e[g]={L:this.Gc(b[g],c),la:f};return e},Mc:function(a,c,b){a.removeAllRanges();for(var e=a.z.document,f=0,g=c.length,h,k;f<g;++f)k=c[f],h=this.Ta(e,k.L,b),a.addRange(h,k.la)}};h("textContent",function(){return g});h("TextRange",function(){var d;
return function(){if(!d){var c=a.uc.We;c?c.G||l(Error("TextRange module is present but not supported.")):l(Error("TextRange module is missing."));d={Gc:function(a,c){return k.Xb(a.Qc(c))},Ta:function(b,c,d){b=a.createRange(b);b.Ka(d,c.start,c.end);return b},yb:function(a,c){return a.pe(c)},Mc:function(a,c,d){a.ne(d,c)}}}return d}}());n.prototype={Bd:function(){return this.Za?this.S.getElementById(this.Za):s(this.S)},jb:function(){return this.za.Ta(this.S,this.L,this.Bd())},Sc:function(){this.Va.Ce(this.jb());
this.Pa=D},apply:function(){this.Va.ad(this.jb());this.Pa=p},toString:function(){return"[Highlight(ID: "+this.id+", class: "+this.Va.V+", character range: "+this.L.start+" - "+this.L.end+")]"}};r.prototype={Wc:function(a){this.Wa[a.V]=a},me:function(a){for(var c=0,b=this.o.length,e;c<b;++c)e=this.o[c],w(a,e)&&(e.Sc(),this.o.splice(c--,1))},Dd:function(a){var c=[],b=this.o;x(a,function(a){x(b,function(b){a.jc(b.jb())&&!w(c,b)&&c.push(b)})});return c},Ld:function(d,c,b){var e,f,g,h=this.o,r=this.za,
s=this.S,t=[];d=this.Wa[d];b=b||v;var u;if(b&&(e=this.S.getElementById(b)))f=a.createRange(this.S),f.selectNodeContents(e),u=new k(0,f.toString().length),f.detach();var w,y;e=0;for(f=c.length;e<f;++e){w=c[e];u&&(w=w.Fa(u));for(g=0;g<h.length;++g)b==h[g].Za&&(y=h[g].L,y.Qd(w)&&(t.push(h[g]),h[g]=new n(s,y.Tc(w),d,r,v,b)));h.push(new n(s,w,d,r,v,b))}x(t,function(a){a.Sc()});var Q=[];x(h,function(a){a.Pa||(a.apply(),Q.push(a))});return Q},Md:function(d,c,b){var e=this.za;c=c||a.getSelection();var f=
this.Wa[d],g=c.z.document,g=b?g.getElementById(b):s(g);f||l(Error("No class applier found for class '"+d+"'"));var f=e.yb(c,g),h=[];x(f,function(a){h.push(k.Xb(a.L))});d=this.Ld(d,h,b);e.Mc(c,f,g);return d},Ee:function(d){d=d||a.getSelection();var c=this.Dd(d.X());this.me(c);d.removeAllRanges()}};a.Pe=r;a.ab=function(a,c){return new r(a,c)}});X.h("Serializer",function(a,e){function h(a,c){c=c||[];var b=a.nodeType,e=a.childNodes,f=e.length,g=[b,a.nodeName,f].join(":"),k="",n="";switch(b){case 3:k=a.nodeValue.replace(/</g,"&lt;").replace(/>/g,"&gt;");break;case 8:k="\x3c!--"+a.nodeValue.replace(/</g,"&lt;").replace(/>/g,"&gt;")+"--\x3e";break;default:k="<"+g+">",n="</>"}k&&c.push(k);for(b=0;b<f;++b)h(e[b],c);n&&c.push(n);return c}function k(a){a=h(a).join("");return u(a).toString(16)}function n(a,c,b){var e=[],f=a;for(b=b||g.l(a).documentElement;f&&
f!=b;)e.push(g.j(f,p)),f=f.parentNode;return e.join("/")+":"+c}function r(a,c,b){c||(c=(b||document).documentElement);a=a.split(":");b=a[0]?a[0].split("/"):[];for(var h=b.length,f;h--;)f=parseInt(b[h],10),f<c.childNodes.length?c=c.childNodes[f]:l(e.k("deserializePosition() failed: node "+g.ia(c)+" has no child with index "+f+", "+h));return new g.ka(c,parseInt(a[1],10))}function t(d,c,b){b=b||a.Na.kb(d).documentElement;g.sb(b,d.commonAncestorContainer)||l(e.k("serializeRange(): range "+d.w()+" is not wholly contained within specified root node "+
g.ia(b)));d=n(d.startContainer,d.startOffset,b)+","+n(d.endContainer,d.endOffset,b);c||(d+="{"+k(b)+"}");return d}function w(d,c,b){c?b=b||g.l(c):(b=b||document,c=b.documentElement);d=/^([^,]+),([^,\{]+)(\{([^}]+)\})?$/.exec(d);var h=d[4],f=k(c);h&&h!==k(c)&&l(e.k("deserializeRange(): checksums of serialized range root node ("+h+") and target root node ("+f+") do not match"));h=r(d[1],c,b);c=r(d[2],c,b);b=a.createRange(b);b.n(h.a,h.offset,c.a,c.offset);return b}function s(a,c,b){c||(c=(b||document).documentElement);
a=/^([^,]+),([^,]+)(\{([^}]+)\})?$/.exec(a)[3];return!a||a===k(c)}function x(d,c,b){d=a.getSelection(d);d=d.X();for(var e=[],f=0,g=d.length;f<g;++f)e[f]=t(d[f],c,b);return e.join("|")}function y(d,c,b){c?b=b||g.lb(c):(b=b||window,c=b.document.documentElement);d=d.split("|");for(var e=a.getSelection(b),f=[],h=0,k=d.length;h<k;++h)f[h]=w(d[h],c,b.document);e.Ma(f);return e}a.q(["WrappedSelection","WrappedRange"]);("undefined"==typeof encodeURIComponent||"undefined"==typeof decodeURIComponent)&&e.r("Global object is missing encodeURIComponent and/or decodeURIComponent method");
var u=function(){var a=v;return function(c){for(var b=[],e=0,f=c.length,g;e<f;++e)g=c.charCodeAt(e),128>g?b.push(g):2048>g?b.push(g>>6|192,g&63|128):b.push(g>>12|224,g>>6&63|128,g&63|128);c=-1;if(!a){for(var e=[],f=0,h;256>f;++f){h=f;for(g=8;g--;)h=1==(h&1)?h>>>1^3988292384:h>>>1;e[f]=h>>>0}a=e}e=a;f=0;for(g=b.length;f<g;++f)h=(c^b[f])&255,c=c>>>8^e[h];return(c^-1)>>>0}}(),g=a.B;a.eg=n;a.qf=r;a.La=t;a.rd=w;a.bf=s;a.yb=x;a.bb=y;a.cf=function(a,c,b){var e;c?e=b?b.document:g.l(c):(b=b||window,c=b.document.documentElement);
a=a.split("|");b=0;for(var f=a.length;b<f;++b)if(!s(a[b],c,e))return D;return p};a.Xf=function(a){a=a||window;var c;a:{c=a.document.cookie.split(/[;,]/);for(var b=0,e=c.length,f;b<e;++b)if(f=c[b].split("="),"RangeManagerSerializedSelection"==f[0].replace(/^\s+/,"")&&(f=f[1])){c=decodeURIComponent(f.replace(/\s+$/,""));break a}c=v}c&&y(c,a.S)};a.Yf=function(d,c){d=d||window;c="object"==typeof c?c:{};var b=c.vd?";expires="+c.vd.toUTCString():"",e=c.path?";path="+c.path:"",f=c.domain?";domain="+c.domain:"",
g=c.Zf?";secure":"",h=x(a.getSelection(d));d.document.cookie=encodeURIComponent("RangeManagerSerializedSelection")+"="+encodeURIComponent(h)+b+e+f+g};a.gb=k;a.Of=h});X.h("TextRange",function(a,e){function h(a,b){if(a){var c={};R(c,b);R(c,a);return c}return b}function k(a){var b,c;return a?(b=a.language||da,c={},R(c,ca[b]||ca[da]),R(c,a),c):ca[da]}function n(a,b){var c=$(a,"display",b),d=a.tagName.toLowerCase();return"block"==c&&W&&ka.hasOwnProperty(d)?ka[d]:c}function r(a){for(var b=a,c=[];b.parentNode;)c.unshift(b.parentNode),b=b.parentNode;a=c.concat([a]);b=0;for(c=a.length;b<c;++b)if(1==a[b].nodeType&&"none"==n(a[b]))return p;return D}function t(a,b){var c;
if(!b&&a.hasChildNodes())c=a.firstChild;else{for(c=a;c&&!c.nextSibling;)c=c.parentNode;c=!c?v:c.nextSibling}return c}function w(a){var b=a.previousSibling;if(b){for(a=b;a.hasChildNodes();)a=a.lastChild;return a}return(a=a.parentNode)&&1==a.nodeType?a:v}function s(a){if(!a||3!=a.nodeType)return D;var b=a.data;if(""===b)return p;var c=a.parentNode;if(!c||1!=c.nodeType)return D;a=$(a.parentNode,"whiteSpace");return/^[\t\n\r ]+$/.test(b)&&/^(normal|nowrap)$/.test(a)||/^[\t\r ]+$/.test(b)&&"pre-line"==
a}function x(a){return""===a.data?p:!s(a)?D:!a.parentNode||r(a)?p:D}function y(a){var b=a.nodeType,c;if(!(c=7==b)){if(!(b=8==b))if(!(b=r(a)))if(!(b=/^(script|style)$/i.test(a.nodeName)))var d,b=3==a.nodeType&&(d=a.parentNode)&&"hidden"==$(d,"visibility")||x(a);c=b}return c}function u(a,b){var c=a.nodeType;return 7==c||8==c||1==c&&"none"==n(a,b)}function g(){this.Ab={}}function d(a,b,c){return function(d){var e=this.ya;if(e.hasOwnProperty(a))return fa++,e[a];ea++;d=b.call(this,c?this[c]:this,d);return e[a]=
d}}function c(a,b){this.node=this.a=a;this.F=b;this.ya=new g;this.be=new g}function b(a,b){this.offset=b;this.ra=a;this.a=a.a;this.F=a.F;this.ya=new g}function q(){f();return ga=new na}function f(){ga&&ga.detach();ga=v}function z(a,b,c,d){function f(){var a=v;b?(a=g,h||(g=g.U(),h=!g||c&&g.W(c))):h||(a=g=g.Ja(),h=!g||c&&g.W(c));h&&(g=v);return a}c&&(b?y(c.a)&&(c=a.U()):y(c.a)&&(c=c.Ja()));var g=a,h=D,k,n=D;return{next:function(){if(n)return n=D,k;for(var a,b;a=f();)if(b=a.Zb(d))return k=a;return v},
oe:function(){k?n=p:l(e.k("createCharacterIterator: cannot rewind. Only one position can be rewound."))},H:function(){a=c=v}}}function G(a,b,c){function d(a){for(var b,c=[],m=a?e:f,g=D,h=D;a=m.next();){b=a.f;if(I.test(b))h&&(h=D,g=p);else if(g){m.oe();break}else h=p;c.push(a)}return c}var e=z(a,D,v,b),f=z(a,p,v,b),g=c.Be;a=d(p);b=d(D).reverse();var h=g(b.concat(a),c),k=a.length?h.slice(oa(h,a[0].Rc)):[],n=b.length?h.slice(0,oa(h,b.pop().Rc)+1):[];return{ub:function(){for(var a,b;1==k.length&&!(a=
k[0]).tb&&0<(b=d(p)).length;)k=g(a.R.concat(b),c);return k.shift()},vb:function(){for(var a,b;1==n.length&&!(a=n[0]).tb&&0<(b=d(D)).length;)n=g(b.reverse().concat(a.R),c);return n.pop()},H:function(){e.H();f.H();k=n=v}}}function K(a,b,c,d){var e=a.I(b,p);a=a.I(b,D);return z(d?a:e,!!d,d?e:a,c)}function E(b,c,d,e,f){function g(b,c){var d=k[b].U(),e=k[c-1],m;if(!(m=!f.Uc)){var h=f.K;m=a.createRange(d.a);m.n(d.a,d.offset,e.a,e.offset);h=!m.expand("word",h);m.detach();m=h}return{zb:d,cb:e,valid:m}}var h=
N(f.direction);b=z(b,h,b.F.I(e,h),f);e="";for(var k=[],n,q,r,s,t,u=v;n=b.next();)if(q=n.f,!d&&!f.Kb&&(q=q.toLowerCase()),h?(k.unshift(n),e=q+e):(k.push(n),e+=q),d){if(n=c.exec(e))if(t){if(r=n.index,s=r+n[0].length,!h&&s<e.length||h&&0<r){u=g(r,s);break}}else t=p}else if(-1!=(r=e.indexOf(c))){u=g(r,r+c.length);break}t&&(u=g(r,s));b.H();return u}function F(a){return function(){var b=!!ga,c=[ga||q()].concat(Y.ze(arguments)),c=a.apply(this,c);b||f();return c}}function H(a,b){return F(function(c,d,e,f){var g,
n;"undefined"==typeof e&&(e=d,d=Q);f=h(f,ia);g=h(f.v,C);var q=k(f.K);f=a;b&&(f=0<=e,this.collapse(!f));c=c.I(this,f);var r=d;d=0;var s=c,t=Math.abs(e);if(0!==e){e=0>e;switch(r){case Q:for(q=z(c,e,v,g);(n=q.next())&&d<t;)++d,s=n;q.H();break;case U:for(var q=G(c,g,q),u=e?q.vb:q.ub;(q=u())&&d<t;)q.tb&&(++d,s=e?q.R[0]:q.R[q.R.length-1]);break;default:l(Error("movePositionBy: unit '"+r+"' not implemented"))}e?(s=s.U(),d=-d):s&&s.oc&&(r==U&&(q=z(c,D,v,g),n=q.next(),q.H()),n&&(s=n.U()))}g=s;n=d;this[f?"setStart":
"setEnd"](g.a,g.offset);return n})}function A(a){return F(function(b,c){c=h(c,C);for(var d,e=K(b,this,c,!a),f=0;(d=e.next())&&I.test(d.f);)++f;e.H();if(d=0<f)this[a?"moveStart":"moveEnd"]("character",a?f:-f,{v:c});return d})}function S(a){return F(function(b,c){var d=D;this.Lb(function(b){d=b[a](c)||d});return d})}a.q(["WrappedSelection"]);var Q="character",U="word",J=a.B,Y=a.b,R=Y.extend,M=J.Y,V=/^[ \t\f\r\n]+$/,T=/^[ \t\f\r]+$/,I=/^[\t-\r \u0085\u00A0\u1680\u180E\u2000-\u200B\u2028\u2029\u202F\u205F\u3000]+$/,
O=/^[\t \u00A0\u1680\u180E\u2000-\u200B\u202F\u205F\u3000]+$/,da="en",N=a.Vc.Vd,L=D;(function(){var b=document.createElement("div");b.contentEditable="true";b.innerHTML="<p>1 </p><p></p>";var c=M(document),d=b.firstChild,e=a.getSelection();c.appendChild(b);e.collapse(d.lastChild,2);e.setStart(d.firstChild,0);b.innerHTML="1 <br>";e.collapse(b,2);e.setStart(b.firstChild,0);L=1==(""+e).length;c.removeChild(b);e.removeAllRanges()})();var C={nb:p,pb:p,ob:p},Z={nb:D,pb:!L,ob:p},ca={en:{Le:/[a-z0-9]+('[a-z0-9]+)*/gi,
hc:D,Be:function(a,b){function c(b,d,e){var g=a.slice(b,d);b={tb:e,R:g,toString:function(){return g.join("")}};d=0;for(e=g.length;d<e;++d)g[d].Rc=b;f.push(b)}for(var d=a.join(""),e,f=[],g=0,h;e=b.Le.exec(d);){h=e.index;e=h+e[0].length;h>g&&c(g,h,D);if(b.hc)for(;O.test(a[e]);)++e;c(h,e,p);g=e}g<a.length&&c(g,a.length,D);return f}}},P={Kb:D,Ke:v,Uc:D,Me:D,direction:"forward",K:v,v:v},ia={K:v,v:v},ja={K:v,v:v,trim:D,ua:p,ta:p},ba={K:v,v:v,direction:"forward"},$=J.ac,W;(function(){var a=document.createElement("table"),
b=M(document);b.appendChild(a);W="block"==$(a,"display");b.removeChild(a)})();a.M.ig=W;var ka={hg:"table",caption:"table-caption",ef:"table-column-group",df:"table-column",ng:"table-header-group",jg:"table-row-group",lg:"table-footer-group",og:"table-row",kg:"table-cell",mg:"table-cell"};g.prototype={get:function(a){return this.Ab.hasOwnProperty(a)?this.Ab[a]:v},set:function(a,b){return this.Ab[a]=b}};var fa=0,ea=0;a.Wf=function(){console.log("Cached: "+fa+", uncached: "+ea)};var B={D:function(a){var c=
this.be;return c.get(a)||c.set(a,new b(this,a))},toString:function(){return"[NodeWrapper("+J.ia(this.a)+")]"}};c.prototype=B;R(B,{N:d("isCharacterDataNode",J.N,"node"),j:d("nodeIndex",J.j,"node"),hb:d("nodeLength",J.Da,"node"),Sb:d("containsPositions",function(a){return J.N(a)||!/^(area|base|basefont|br|col|frame|hr|img|input|isindex|link|meta|param)$/i.test(a.nodeName)},"node"),Mf:d("isWhitespace",s,"node"),Ef:d("isCollapsedWhitespace",x,"node"),$b:d("computedDisplay",n,"node"),isCollapsed:d("collapsed",
y,"node"),Jf:d("ignored",u,"node"),next:d("nextPos",t,"node"),Ec:d("previous",w,"node"),Kd:d("textNodeInfo",function(a){var b=v,c=D,d=$(a.parentNode,"whiteSpace"),e="pre-line"==d;if(e)b=T,c=p;else if("normal"==d||"nowrap"==d)b=V,c=p;return{a:a,text:a.data,ue:b,hd:c,ce:e}},"node"),fc:d("hasInnerText",function(a,b){for(var c=this.F,d=c.D(a.parentNode,this.j()+1),e=c.D(a,0),c=b?d:e,d=b?e:d;c!==d;){c.Cc();if(c.Ud())return p;c=b?c.U():c.Ja()}return D},"node"),dc:d("trailingSpace",function(a){if("br"!=
a.tagName.toLowerCase())switch(this.$b()){case "inline":for(a=a.lastChild;a;){if(!u(a))return 1==a.nodeType?this.F.ga(a).dc():"";a=a.previousSibling}break;case "inline-block":case "inline-table":case "none":case "table-column":case "table-column-group":break;case "table-cell":return"\t";default:return this.fc(p)?"\n":""}return""},"node"),Ed:d("leadingSpace",function(){switch(this.$b()){case "inline":case "inline-block":case "inline-table":case "none":case "table-column":case "table-column-group":case "table-cell":break;
default:return this.fc(D)?"\n":""}return""},"node")});B={f:"",na:"EMPTY",lc:D,Cc:function(){if(!this.Dc){var a=this.a,b=this.offset,c="",d="EMPTY",e=D;if(0<b)if(3==a.nodeType){var a=a.data,f=a.charAt(b-1),g=this.ra.Kd(),h=g.ue;g.hd?h.test(f)?1<b&&h.test(a.charAt(b-2))||(g.ce&&"\n"===a.charAt(b)?(c=" ",d="PRE_LINE_TRAILING_SPACE_BEFORE_LINE_BREAK"):(c=" ",d="COLLAPSIBLE_SPACE")):(c=f,d="NON_SPACE",e=p):(c=f,d="UNCOLLAPSIBLE_SPACE",e=p)}else{if((f=a.childNodes[b-1])&&1==f.nodeType&&!y(f))"br"==f.tagName.toLowerCase()?
(c="\n",this.lc=p,d="COLLAPSIBLE_SPACE",e=D):this.Nb=p;if(!c&&(b=a.childNodes[b])&&1==b.nodeType&&!y(b))this.Mb=p}this.Dc=p;this.f=c;this.na=d;this.Td=e}},Ud:function(){var a=this.na;return"NON_SPACE"==a||"UNCOLLAPSIBLE_SPACE"==a},Lc:function(){this.Dc||this.Cc();if(this.Nb){var a=this.F.ga(this.a.childNodes[this.offset-1]).dc();a&&(this.Ia=p,this.f=a,this.na="COLLAPSIBLE_SPACE");this.Nb=D}if(this.Mb){if(a=this.F.ga(this.a.childNodes[this.offset]).Ed())this.oc=p,this.f=a,this.na="COLLAPSIBLE_SPACE";
this.Mb=D}},Fd:function(a){for(var b=this,c;b=b.U();)if(c=b.Zb(a),""!==c)return b;return v},Zb:function(a){function b(){g||(f=h.Fd(a),g=p);return f}this.Lc();if(this.Td)return this.f;var c=["character",a.pb,a.nb,a.ob].join("_"),d=this.ya.get(c);if(d!==v)return d;var d="",e,f,g=D,h=this;if("COLLAPSIBLE_SPACE"==this.na){if(!(" "==this.f&&(!b()||f.Ia||"\n"==f.f)))if("\n"==this.f&&this.oc)b()&&"\n"!=f.f&&(d="\n");else if(e=this.vc())if(e.lc?this.type="TRAILING_SPACE_BEFORE_BR":e.Ia&&"\n"==e.f&&(this.type=
"TRAILING_SPACE_IN_BLOCK"),"\n"===e.f){if("TRAILING_SPACE_BEFORE_BR"!=this.type||a.pb)"TRAILING_SPACE_IN_BLOCK"==this.type&&e.Ia&&!a.nb||"PRE_LINE_TRAILING_SPACE_BEFORE_LINE_BREAK"==this.type&&"NON_SPACE"==e.type&&!a.ob||("\n"===this.f?e.Ia||(d="\n"):" "===this.f&&(d=" "))}else d=this.f}else"\n"===this.f&&(e=this.vc());this.ya.set(c,d);return d},W:function(a){return!!a&&this.a===a.a&&this.offset===a.offset},w:function(){return"[Position("+J.ia(this.a)+":"+this.offset+")]"},toString:function(){return this.f}};
b.prototype=B;R(B,{next:d("nextPos",function(a){var b=a.ra,c=a.a,d=a.offset;a=b.F;if(!c)return v;d==b.hb()?b=(c=c.parentNode)?b.j()+1:0:b.N()?b=d+1:(b=c.childNodes[d],a.ga(b).Sb()?(c=b,b=0):b=d+1);return c?a.D(c,b):v}),Ec:d("previous",function(a){var b=a.ra,c=a.a,d=a.offset;a=b.F;0==d?b=(c=c.parentNode)?b.j():0:b.N()?b=d-1:(b=c.childNodes[d-1],a.ga(b).Sb()?(c=b,b=J.Da(b)):b=d-1);return c?a.D(c,b):v}),Ja:d("nextVisible",function(a){var b=a.next();if(!b)return v;a=b.ra;var c=b.a;a.isCollapsed()&&(b=
a.F.D(c.parentNode,a.j()+1));return b}),vc:d("nextUncollapsed",function(a){for(;a=a.Ja();)if(a.Lc(),""!==a.f)return a;return v}),U:d("previousVisible",function(a){var b=a.Ec();if(!b)return v;a=b.ra;var c=b.a;a.isCollapsed()&&(b=a.F.D(c.parentNode,a.j()));return b})});var ga=v,na=function(){function a(b){var c=new g;return{get:function(a){var d=c.get(a[b]);if(d)for(var e=0,f;f=d[e++];)if(f.a===a)return f;return v},set:function(a){var d=a.a[b];(c.get(d)||c.set(d,[])).push(a)}}}function b(){this.Od()}
var d=Y.Ga(document.documentElement,"uniqueID");b.prototype={Od:function(){this.Vb=d?function(){var a=new g;return{get:function(b){return a.get(b.uniqueID)},set:function(b){a.set(b.a.uniqueID,b)}}}():a("tagName");this.Pc=a("data");this.yc=a("nodeName")},ga:function(a){var b;switch(a.nodeType){case 1:b=this.Vb;break;case 3:b=this.Pc;break;default:b=this.yc}var d=b.get(a);d||(d=new c(a,this),b.set(d));return d},D:function(a,b){return this.ga(a).D(b)},I:function(a,b){var c=b?"start":"end";return this.D(a[c+
"Container"],a[c+"Offset"])},detach:function(){this.Vb=this.Pc=this.yc=v}};return b}();R(J,{Nf:t,Rf:w});var oa=Array.prototype.indexOf?function(a,b){return a.indexOf(b)}:function(a,b){for(var c=0,d=a.length;c<d;++c)if(a[c]===b)return c;return-1};R(a.Fc,{moveStart:H(p,D),moveEnd:H(D,D),move:H(p,p),ua:A(p),ta:A(D),trim:F(function(a,b){var c=this.ua(b),d=this.ta(b);return c||d}),expand:F(function(a,b,c){var d=D;c=h(c,ja);var e=h(c.v,C);b||(b=Q);if(b==U){var f=k(c.K);b=a.I(this,p);a=a.I(this,D);var g=
G(b,e,f).ub(),n=g.R[0].U(),f=this.collapsed?g:G(a,e,f).vb(),f=f.R[f.R.length-1];n.W(b)||(this.setStart(n.a,n.offset),d=p);f&&!f.W(a)&&(this.setEnd(f.a,f.offset),d=p);c.trim&&(c.ua&&(d=this.ua(e)||d),c.ta&&(d=this.ta(e)||d));return d}return this.moveEnd(Q,1,c)}),text:F(function(a,b){var c;if(this.collapsed)c="";else{var d=h(b,C);c=[];for(var d=K(a,this,d),e;e=d.next();)c.push(e);d.H();c=c.join("")}return c}),Ka:F(function(a,b,c,d,e){a={v:e};b||(b=M(this.l()));this.selectNodeContents(b);this.collapse(p);
this.moveStart("character",c,a);this.collapse(p);this.moveEnd("character",d-c,a)}),Qc:F(function(a,b,c){b||(b=M(this.l()));a=b.parentNode;b=J.j(b);var d=-1==J.Ya(this.startContainer,this.endContainer,a,b),e=this.cloneRange();d?(e.n(this.startContainer,this.startOffset,a,b),a=-e.text(c).length):(e.n(a,b,this.startContainer,this.startOffset),a=e.text(c).length);c=a+this.text(c).length;return{start:a,end:c}}),findText:F(function(b,c,d){d=h(d,P);d.Uc&&(d.K=k(d.K),d.K.hc=D);var e=N(d.direction),f=d.Ke;
f||(f=a.createRange(),f.selectNodeContents(this.l()));var g=D;"string"==typeof c?d.Kb||(c=c.toLowerCase()):g=p;var n=b.I(this,!e),q=f.comparePoint(n.a,n.offset);-1===q?n=b.I(f,p):1===q&&(n=b.I(f,D));for(var r=n,q=D;;)if(r=E(r,c,g,f,d)){if(r.valid)return this.n(r.zb.a,r.zb.offset,r.cb.a,r.cb.offset),p;r=e?r.zb:r.cb}else if(d.Me&&!q)f=f.cloneRange(),r=b.I(f,!e),f.te(n.a,n.offset,e),q=p;else return D}),Qf:function(a){this.deleteContents();if(a){a=this.createContextualFragment(a);var b=a.lastChild;this.insertNode(a);
this.gd(b)}}});R(a.qe,{expand:F(function(a,b,c){this.Lb(function(a){a.expand(b,c)})}),move:F(function(a,b,c,d){a=0;if(this.focusNode){this.collapse(this.focusNode,this.focusOffset);var e=this.getRangeAt(0);d||(d={});d.v=h(d.v,Z);a=e.move(b,c,d);this.ja(e)}return a}),ua:S("trimStart"),ta:S("trimEnd"),trim:S("trim"),Ka:F(function(b,c,d,e,f,g){b=a.createRange(c);b.Ka(c,d,e,g);this.ja(b,f)}),pe:F(function(a,b,c){a=this.X();for(var d=[],e=1==a.length&&this.$(),f=0,g=a.length;f<g;++f)d[f]={L:a[f].Qc(b,
c),la:e,v:c};return d}),ne:F(function(b,c,d){this.removeAllRanges();b=0;for(var e=d.length,f,g,h;b<e;++b)g=d[b],h=g.L,f=a.createRange(c),f.Ka(c,h.start,h.end,g.v),this.addRange(f,g.la)}),text:F(function(a,b){for(var c=[],d=0,e=this.rangeCount;d<e;++d)c[d]=this.getRangeAt(d).text(b);return c.join("")})});a.innerText=function(b,c){var d=a.createRange(b);d.selectNodeContents(b);var e=d.text(c);d.detach();return e};a.of=function(a,b,c){var d=ga||q();c=h(c,ba);var e=h(c.v,C),f=k(c.K);a=d.D(a,b);var g=
G(a,e,f),n=N(c.direction);return{next:function(){return n?g.vb():g.ub()},H:function(){g.H();this.next=function(){}}}};a.$d=function(a){var b=ga||q();a(b);f()};a.$d.jf=F;a.ca={Df:function(a){return a&&(1==a.nodeType&&!/^(inline(-block|-table)?|none)$/.test(n(a))||9==a.nodeType||11==a.nodeType)},Ff:x,nf:F(function(a,b,c){return a.D(b,c)})}});ma.Yb&&ma.Yb();
